In [1]:
%load_ext jupyternotify

/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/jupyternotify/jupyternotify.py:11: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename

In [34]:
!pip install accelerate

Requirement already satisfied: accelerate in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (1.10.1)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from accelerate) (7.2.1)
Requirement already satisfied: pyyaml in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from accelerate) (2.8.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from accelerate) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub>=0.21.0->accelerate) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub>=0.21.0->accelerate) (2025.10.0)
Requirement already satisfied: requests in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub>=0.21.0->accelerate) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub>=0.21.0->accelerate) (1.2.0)
Requirement already satisfied: sympy>=1.13.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (3.2.1)
Requirement already satisfied: jinja2 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch>=2.0.0->accelerate) (3.4.0)
Requirement already satisfied: setuptools>=40.8.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from triton==3.4.0->torch>=2.0.0->accelerate) (80.10.2)
Requirement already satisfied: importlib-metadata in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from triton==3.4.0->torch>=2.0.0->accelerate) (8.7.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from importlib-metadata->triton==3.4.0->torch>=2.0.0->accelerate) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->huggingface_hub>=0.21.0->accelerate) (2026.1.4)

[notice] A new release of pip is available: 20.0.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [9]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.48.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from bitsandbytes) (2.8.0)
Requirement already satisfied: numpy>=1.17 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (3.2.1)
Requirement already satisfied: jinja2 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (2025.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from torch<3,>=2.3->bitsandbytes) (3.4.0)
Requirement already satisfied: setuptools>=40.8.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from triton==3.4.0->torch<3,>=2.3->bitsandbytes) (80.10.2)
Requirement already satisfied: importlib-metadata in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from triton==3.4.0->torch<3,>=2.3->bitsandbytes) (8.7.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from importlib-metadata->triton==3.4.0->torch<3,>=2.3->bitsandbytes) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.48.2-py3-none-manylinux_2_24_x86_64.whl (59.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 MB 87.3 MB/s  0:00:006m0:00:0100:01
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.48.2

[notice] A new release of pip is available: 20.0.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [11]:
!pip install "huggingface_hub[cli]"

Requirement already satisfied: huggingface_hub[cli] in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (0.36.0)
Requirement already satisfied: filelock in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub[cli]) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub[cli]) (2025.10.0)
Requirement already satisfied: packaging>=20.9 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub[cli]) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub[cli]) (6.0.3)
Requirement already satisfied: requests in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub[cli]) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub[cli]) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub[cli]) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface_hub[cli]) (1.2.0)
Collecting InquirerPy==0.3.4 (from huggingface_hub[cli])
  Downloading InquirerPy-0.3.4-py3-none-any.whl.metadata (8.1 kB)
Collecting pfzy<0.4.0,>=0.3.1 (from InquirerPy==0.3.4->huggingface_hub[cli])
  Downloading pfzy-0.3.4-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from InquirerPy==0.3.4->huggingface_hub[cli]) (3.0.52)
Requirement already satisfied: wcwidth in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from prompt-toolkit<4.0.0,>=3.0.1->InquirerPy==0.3.4->huggingface_hub[cli]) (0.2.14)
Requirement already satisfied: charset_normalizer<4,>=2 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->huggingface_hub[cli]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->huggingface_hub[cli]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->huggingface_hub[cli]) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->huggingface_hub[cli]) (2026.1.4)
Downloading InquirerPy-0.3.4-py3-none-any.whl (67 kB)
Downloading pfzy-0.3.4-py3-none-any.whl (8.5 kB)
Installing collected packages: pfzy, InquirerPy
ERROR: Could not install packages due to an OSError: [Errno 122] Disk quota exceeded: '/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/pfzy'

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/2 [pfzy]
WARNING: There was an error checking the latest version of pip.

In [1]:
import os
from transformers import pipeline, BitsAndBytesConfig, AutoTokenizer, AutoModelForCausalLM
import torch
from huggingface_hub import login
import pandas as pd
import json
from tqdm import tqdm
import re
import ast
import gc
from torch.utils.data import Dataset
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [34]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import classification_report

In [3]:
codebook = {}
supercategories = [100, 200, 300, 400, 500, 600, 700, 800, 1000, 1200, 1300, 1400, 1500, 1600, 1800, 1900, 2000]
supercat_names = ['Macroeconomics', 'Civil Rights', 'Health', 'Agriculture', 'Labour and Employment', 'Education', 'Environment', 'Energy', 'Transportation', 'Law, Crime, and Family Issues', 'Social Welfare', 'Planning and Housing Issues', 'Finance and Domestic Commerce', 'Defence', 'Foreign Trade', 'International Affairs', 'Government Operations']

In [4]:
len(supercategories)

17

In [4]:
for i in range(len(supercategories)):
    codebook[str(supercategories[i])] = {'name': supercat_names[i], 'subs':{}}

In [5]:
subcategories = {
    'subs_100':[101,103,104,105,107,108],
    'subs_100_names': ['Inflation, prices, and interest rates', 'Unemployment rate',
                      'Monetary Supply, Central Bank, and the Treasury','National Budget, Debt, public spending',
                     'Taxation, Tax policy, and Tax Reform', 'Industrial Policy, Privatisation, Nationalisation'],

    'subs_200': [201,202,207,208,230],
    'subs_200_names': [
        'Ethnic Minority and Racial Group Discrimination',
        'Gender and Sexual Orientation Discrimination',
        'Freedom of Speech & Religion',
        'Right to Privacy and Access to Government Information',
        'Immigration'
    ],

    'subs_300': [301,321,325,331,332,334,344],
    'subs_300_names': [
        'Health Care Reform',
        'Regulation of Drug Industry, Medical Devices, and Clinical Labs',
        'Health Manpower and Training',
        'Prevention, Communicable Diseases and Health Promotion',
        'Infants and Children',
        'Long-Term Care, Home Health, and Rehabilitation',
        'Drug and Alcohol or Substance Abuse Treatment'
    ],

    'subs_400': [401,406,408],
    'subs_400_names': [
        'Agricultural Trade',
        'Animal Welfare',
        'Fisheries and Fishing'
    ],

    'subs_500': [502,503,504,505,506,508,529],
    'subs_500_names': [
        'Employment Training and Workforce Development',
        'Employee Benefits',
        'Employee Relations and Labour Unions',
        'Fair Labour Standards',
        'Youth Employment and Child Labour',
        'Parental Leave and Child Care',
        'Migrant and Seasonal Workers'
    ],

    'subs_600': [601,602,603,604,606],
    'subs_600_names': [
        'Higher Education',
        'Elementary and Secondary Education',
        'Education of Underprivileged Students',
        'Vocational Education',
        'Special Education'
    ],

    'subs_700': [701,703,705,709],
    'subs_700_names': [
        'Water Pollution',
        'Waste Disposal',
        'Air Pollution, Global Warming, and Noise Pollution',
        'Species and Forest Protection'
    ],

    'subs_800': [801,803,805,806,807],
    'subs_800_names': [
        'Nuclear Energy and Nuclear Regulatory Issues',
        'Natural Gas and Oil',
        'Coal',
        'Alternative and Renewable Energy',
        'Energy Conservation'
    ],

    'subs_1000': [1001,1002,1003,1005,1006],
    'subs_1000_names': [
        'Mass and Public Transportation and Safety',
        'Highway (Road) Construction, Maintenance, and Safety',
        'Airports, Airlines, Air Traffic Control and Safety',
        'Railroad Transportation and Safety',
        'Truck and Automobile Transportation and Safety'
    ],

    'subs_1200': [1202,1203,1205,1206,1207,1208,1209,1211],
    'subs_1200_names': [
        'White Collar Crime and Organized Crime',
        'Illegal Drug Production, Trafficking, and Control',
        'Prison System',
        'Juvenile Crime and the Juvenile Justice System',
        'Child Abuse',
        'Family Issues',
        'Police, Fire, and Weapons Control',
        'Riots and Crime Prevention'
    ],

    'subs_1300': [1302,1303,1304,1305],
    'subs_1300_names': [
        'Poverty and Assistance for Low-Income Families',
        'Elderly Issues and Elderly Assistance Programs, State Pensions',
        'Assistance to the Disabled and Handicapped',
        'Social Services and Volunteer Associations'
    ],

    'subs_1400': [1401,1406,1407,1409,1410],
    'subs_1400_names': [
        'Housing and Community Development',
        'Low and Middle Income Housing Programs and Needs',
        'Veterans Housing Assistance and Military Housing Programs',
        'Housing Assistance for Homeless and Homeless Issues',
        'Mortgages'
    ],

    'subs_1500': [1501,1521,1524],
    'subs_1500_names': [
        'Banking System and Financial Institution Regulation',
        'Small Business Issues',
        'Tourism'
    ],

    'subs_1600': [1603,1608,1609,1610,1627],
    'subs_1600_names': [
        'Military Intelligence, Intelligence Services, Espionage',
        'Manpower, Military Personnel and Dependents',
        'Veterans Issues',
        'Military Procurement and Weapons System Acquisitions and Evaluation',
        'Domestic and International Terrorism'
    ],

    'subs_1800': [1803,1806],
    'subs_1800_names': [
        'Export Promotion and Regulation, Export Credit Agencies',
        'Productivity and Competitiveness of U.K. Business, U.K. Balance of Payments'
    ],

    'subs_1900': [1901,1907,1909,1910,1911,1920,1926,1930],
    'subs_1900_names': [
        'Foreign Aid',
        'China',
        'Eastern Europe',
        'Western Europe, Common Market Issues',
        'Africa',
        'Middle East',
        'International Organizations other than Finance',
        'North America and North Atlantic Ocean'
    ],

    'subs_2000': [2001,2011,2012,2032],
    'subs_2000_names': [
        'Intergovernmental Relations',
        'Executive-Legislative Relations and Parliamentary Operations',
        'Political Parties, Campaigns, and Voter Registration',
        'Prime Ministerial or Ministerial Scandals and Resignations'
    ]
}

In [6]:
# codebook['100']['subs']['101'] = 'Inflation'

for i in range(len(supercategories)):
    c = supercategories[i]
    sublist = subcategories[f"subs_{c}"]
    subnames = subcategories[f"subs_{c}_names"]
    for j in range(len(sublist)):
        codebook[str(c)]['subs'][str(sublist[j])] = subnames[j]

In [7]:
codebook

{'100': {'name': 'Macroeconomics',
  'subs': {'101': 'Inflation, prices, and interest rates',
   '103': 'Unemployment rate',
   '104': 'Monetary Supply, Central Bank, and the Treasury',
   '105': 'National Budget, Debt, public spending',
   '107': 'Taxation, Tax policy, and Tax Reform',
   '108': 'Industrial Policy, Privatisation, Nationalisation'}},
 '200': {'name': 'Civil Rights',
  'subs': {'201': 'Ethnic Minority and Racial Group Discrimination',
   '202': 'Gender and Sexual Orientation Discrimination',
   '207': 'Freedom of Speech & Religion',
   '208': 'Right to Privacy and Access to Government Information',
   '230': 'Immigration'}},
 '300': {'name': 'Health',
  'subs': {'301': 'Health Care Reform',
   '321': 'Regulation of Drug Industry, Medical Devices, and Clinical Labs',
   '325': 'Health Manpower and Training',
   '331': 'Prevention, Communicable Diseases and Health Promotion',
   '332': 'Infants and Children',
   '334': 'Long-Term Care, Home Health, and Rehabilitation',
   '344': 'Drug and Alcohol or Substance Abuse Treatment'}},
 '400': {'name': 'Agriculture',
  'subs': {'401': 'Agricultural Trade',
   '406': 'Animal Welfare',
   '408': 'Fisheries and Fishing'}},
 '500': {'name': 'Labour and Employment',
  'subs': {'502': 'Employment Training and Workforce Development',
   '503': 'Employee Benefits',
   '504': 'Employee Relations and Labour Unions',
   '505': 'Fair Labour Standards',
   '506': 'Youth Employment and Child Labour',
   '508': 'Parental Leave and Child Care',
   '529': 'Migrant and Seasonal Workers'}},
 '600': {'name': 'Education',
  'subs': {'601': 'Higher Education',
   '602': 'Elementary and Secondary Education',
   '603': 'Education of Underprivileged Students',
   '604': 'Vocational Education',
   '606': 'Special Education'}},
 '700': {'name': 'Environment',
  'subs': {'701': 'Water Pollution',
   '703': 'Waste Disposal',
   '705': 'Air Pollution, Global Warming, and Noise Pollution',
   '709': 'Species and Forest Protection'}},
 '800': {'name': 'Energy',
  'subs': {'801': 'Nuclear Energy and Nuclear Regulatory Issues',
   '803': 'Natural Gas and Oil',
   '805': 'Coal',
   '806': 'Alternative and Renewable Energy',
   '807': 'Energy Conservation'}},
 '1000': {'name': 'Transportation',
  'subs': {'1001': 'Mass and Public Transportation and Safety',
   '1002': 'Highway (Road) Construction, Maintenance, and Safety',
   '1003': 'Airports, Airlines, Air Traffic Control and Safety',
   '1005': 'Railroad Transportation and Safety',
   '1006': 'Truck and Automobile Transportation and Safety'}},
 '1200': {'name': 'Law, Crime, and Family Issues',
  'subs': {'1202': 'White Collar Crime and Organized Crime',
   '1203': 'Illegal Drug Production, Trafficking, and Control',
   '1205': 'Prison System',
   '1206': 'Juvenile Crime and the Juvenile Justice System',
   '1207': 'Child Abuse',
   '1208': 'Family Issues',
   '1209': 'Police, Fire, and Weapons Control',
   '1211': 'Riots and Crime Prevention'}},
 '1300': {'name': 'Social Welfare',
  'subs': {'1302': 'Poverty and Assistance for Low-Income Families',
   '1303': 'Elderly Issues and Elderly Assistance Programs, State Pensions',
   '1304': 'Assistance to the Disabled and Handicapped',
   '1305': 'Social Services and Volunteer Associations'}},
 '1400': {'name': 'Planning and Housing Issues',
  'subs': {'1401': 'Housing and Community Development',
   '1406': 'Low and Middle Income Housing Programs and Needs',
   '1407': 'Veterans Housing Assistance and Military Housing Programs',
   '1409': 'Housing Assistance for Homeless and Homeless Issues',
   '1410': 'Mortgages'}},
 '1500': {'name': 'Finance and Domestic Commerce',
  'subs': {'1501': 'Banking System and Financial Institution Regulation',
   '1521': 'Small Business Issues',
   '1524': 'Tourism'}},
 '1600': {'name': 'Defence',
  'subs': {'1603': 'Military Intelligence, Intelligence Services, Espionage',
   '1608': 'Manpower, Military Personnel and Dependents',
   '1609': 'Veterans Issues',
   '1610': 'Military Procurement and Weapons System Acquisitions and Evaluation',
   '1627': 'Domestic and International Terrorism'}},
 '1800': {'name': 'Foreign Trade',
  'subs': {'1803': 'Export Promotion and Regulation, Export Credit Agencies',
   '1806': 'Productivity and Competitiveness of U.K. Business, U.K. Balance of Payments'}},
 '1900': {'name': 'International Affairs',
  'subs': {'1901': 'Foreign Aid',
   '1907': 'China',
   '1909': 'Eastern Europe',
   '1910': 'Western Europe, Common Market Issues',
   '1911': 'Africa',
   '1920': 'Middle East',
   '1926': 'International Organizations other than Finance',
   '1930': 'North America and North Atlantic Ocean'}},
 '2000': {'name': 'Government Operations',
  'subs': {'2001': 'Intergovernmental Relations',
   '2011': 'Executive-Legislative Relations and Parliamentary Operations',
   '2012': 'Political Parties, Campaigns, and Voter Registration',
   '2032': 'Prime Ministerial or Ministerial Scandals and Resignations'}}}

In [3]:
login("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")

In [8]:
model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"

quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)

llm_model = pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={
        "quantization_config": quant_config,
        "low_cpu_mem_usage": True,
        "torch_dtype": torch.bfloat16
    },
    device_map="auto"
)

`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0

In [9]:
terminators = [
    llm_model.tokenizer.eos_token_id,
    llm_model.tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

In [91]:
if 'llm_model' in globals():
    del llm_model

gc.collect()

torch.cuda.empty_cache()

In [9]:
# Enabling batching

llm_model = pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={
        "quantization_config": quant_config,
        "low_cpu_mem_usage": True,
        "torch_dtype": torch.bfloat16
    },
    device_map="auto",
    batch_size=4
)

llm_model.tokenizer.pad_token = llm_model.tokenizer.eos_token
llm_model.tokenizer.padding_side = "left"

`torch_dtype` is deprecated! Use `dtype` instead!

ValueError: Could not load model meta-llama/Meta-Llama-3.1-8B-Instruct with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class 'transformers.models.llama.modeling_llama.LlamaForCausalLM'>). See the original errors:

while loading with AutoModelForCausalLM, an error is thrown:
Traceback (most recent call last):
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/pipelines/base.py", line 293, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 604, in from_pretrained
    return model_class.from_pretrained(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 5029, in from_pretrained
    device_map = _get_device_map(model, device_map, max_memory, hf_quantizer, dtype, keep_in_fp32_regex)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1365, in _get_device_map
    hf_quantizer.validate_environment(device_map=device_map)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 127, in validate_environment
    raise ValueError(
ValueError: Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules in 32-bit, you need to set `llm_int8_enable_fp32_cpu_offload=True` and pass a custom `device_map` to `from_pretrained`. Check https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu for more details.

while loading with LlamaForCausalLM, an error is thrown:
Traceback (most recent call last):
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/pipelines/base.py", line 293, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 5029, in from_pretrained
    device_map = _get_device_map(model, device_map, max_memory, hf_quantizer, dtype, keep_in_fp32_regex)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1365, in _get_device_map
    hf_quantizer.validate_environment(device_map=device_map)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 127, in validate_environment
    raise ValueError(
ValueError: Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules in 32-bit, you need to set `llm_int8_enable_fp32_cpu_offload=True` and pass a custom `device_map` to `from_pretrained`. Check https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu for more details.

In [3]:
!huggingface-cli scan-cache

⚠️  Warning: 'huggingface-cli scan-cache' is deprecated. Use 'hf cache scan' instead.
REPO ID                                REPO TYPE SIZE ON DISK NB FILES LAST_ACCESSED LAST_MODIFIED REFS             LOCAL PATH
-------------------------------------- --------- ------------ -------- ------------- ------------- ---------------- ------------------------------------------------------------------------------------
GateNLP/stance-bertweet-target-aware   model           541.6M        7 3 months ago  3 months ago  main             /home2/pwfb75/.cache/huggingface/hub/models--GateNLP--stance-bertweet-target-aware
bert-base-cased                        model           436.4M        5 2 days ago    2 days ago    main             /home2/pwfb75/.cache/huggingface/hub/models--bert-base-cased
bert-base-german-cased                 model           439.6M        5 2 months ago  2 months ago  main             /home2/pwfb75/.cache/huggingface/hub/models--bert-base-german-cased
google/gemma-2-9b-it                   model            39.9K        2 1 week ago    1 week ago    main             /home2/pwfb75/.cache/huggingface/hub/models--google--gemma-2-9b-it
microsoft/deberta-v3-base              model           744.7M        5 1 day ago     1 day ago     main, refs/pr/14 /home2/pwfb75/.cache/huggingface/hub/models--microsoft--deberta-v3-base
roberta-base                           model           501.5M        6 19 hours ago  19 hours ago  main             /home2/pwfb75/.cache/huggingface/hub/models--roberta-base
sentence-transformers/all-MiniLM-L6-v2 model            91.6M       11 1 week ago    1 week ago    main             /home2/pwfb75/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2
unsloth/gemma-2-9b-it-bnb-4bit         model             6.2G        7 1 week ago    1 week ago    main             /home2/pwfb75/.cache/huggingface/hub/models--unsloth--gemma-2-9b-it-bnb-4bit
vinai/bertweet-base                    model             1.1G        6 4 months ago  4 months ago  main, refs/pr/6  /home2/pwfb75/.cache/huggingface/hub/models--vinai--bertweet-base

Done in 0.0s. Scanned 9 repo(s) for a total of 10.0G.
Got 1 warning(s) while scanning. Use -vvv to print details.

In [2]:
!du -sh /home2/pwfb75/.cache/huggingface/hub/

27G	/home2/pwfb75/.cache/huggingface/hub/

In [13]:
!rm -rf /home2/pwfb75/.cache/huggingface/hub/models--unsloth--Mistral-Nemo-Instruct-2407-bnb-4bit
!rm -rf /home2/pwfb75/.cache/huggingface/hub/models--openai--clip-vit-base-patch32


print("Cache cleared.")

Cache cleared.

In [7]:
!rm -rf /home2/pwfb75/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-8B-Instruct
print("Cache cleared.")

Cache cleared.

In [25]:
!rm -rf /home2/pwfb75/.cache/huggingface/hub/models--NousResearch--Nous-Hermes-2-SOLAR-10.7B
print("Cache cleared.")

Cache cleared.

In [27]:
!rm -rf /home2/pwfb75/.cache/huggingface/hub/tmp*
print("Cache cleared")

Cache cleared

In [29]:
!rm -rf /home2/pwfb75/.cache/huggingface/hub/models--Systran--faster-whisper-large-v2
!rm -rf /home2/pwfb75/.cache/huggingface/hub/models--jonatasgrosman--wav2vec2-large-xlsr-53-chinese-zh-cn
print("Cache cleared")

Cache cleared

In [9]:
model_id_gemma = "unsloth/gemma-2-9b-it-bnb-4bit" 

quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)


llm_model_gemma = pipeline(
    "text-generation",
    model=model_id_gemma,
    model_kwargs={
        "low_cpu_mem_usage": True,
        "dtype": torch.bfloat16 
    },
    device_map="auto"
)
terminators = [
    llm_model_gemma.tokenizer.eos_token_id,
    llm_model_gemma.tokenizer.convert_tokens_to_ids("<end_of_turn>")
]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/6.13G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

Device set to use cuda:0

In [8]:
model_id_nemo = "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit"

llm_model_nemo = pipeline(
    "text-generation",
    model=model_id_nemo,
    model_kwargs={
        "low_cpu_mem_usage": True,
        "dtype": torch.bfloat16 
    },
    device_map="auto"
)

terminators = [
    llm_model_nemo.tokenizer.eos_token_id,
    llm_model_nemo.tokenizer.convert_tokens_to_ids("</s>"),
    llm_model_nemo.tokenizer.convert_tokens_to_ids("<|im_end|>")
]

llm_model_nemo.tokenizer.pad_token = llm_model_nemo.tokenizer.eos_token
llm_model_nemo.tokenizer.padding_side = "left"

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

In [2]:
model_id_hermes = "NousResearch/Nous-Hermes-2-SOLAR-10.7B"

quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)

llm_model_hermes = pipeline(
    "text-generation",
    model=model_id_hermes,
    model_kwargs={
        "quantization_config": quant_config,
        "low_cpu_mem_usage": True
    },
    device_map="auto"
)

terminators = [
    llm_model_hermes.tokenizer.eos_token_id,
    llm_model_hermes.tokenizer.convert_tokens_to_ids("<|im_end|>")
]

llm_model_hermes.tokenizer.pad_token = llm_model_hermes.tokenizer.eos_token

config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

model-00001-of-00005.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00002-of-00005.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00005.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00005-of-00005.safetensors:   0%|          | 0.00/1.69G [00:00<?, ?B/s]

model-00004-of-00005.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

Ignored error while writing commit hash to /home2/pwfb75/.cache/huggingface/hub/models--NousResearch--Nous-Hermes-2-SOLAR-10.7B/refs/main: [Errno 122] Disk quota exceeded.

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

model-00002-of-00005.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00005.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00001-of-00005.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00004-of-00005.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

ValueError: Could not load model NousResearch/Nous-Hermes-2-SOLAR-10.7B with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class 'transformers.models.llama.modeling_llama.LlamaForCausalLM'>). See the original errors:

while loading with AutoModelForCausalLM, an error is thrown:
Traceback (most recent call last):
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1720, in _download_to_tmp_and_move
    xet_get(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 626, in xet_get
    download_files(
RuntimeError: Data processing error: CAS service error : IO Error: Input/output error (os error 5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/pipelines/base.py", line 293, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 604, in from_pretrained
    return model_class.from_pretrained(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4900, in from_pretrained
    checkpoint_files, sharded_metadata = _get_resolved_checkpoint_files(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1200, in _get_resolved_checkpoint_files
    checkpoint_files, sharded_metadata = get_checkpoint_shard_files(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 1084, in get_checkpoint_shard_files
    cached_filenames = cached_files(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 567, in cached_files
    raise e
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 494, in cached_files
    snapshot_download(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/_snapshot_download.py", line 332, in snapshot_download
    thread_map(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/tqdm/notebook.py", line 250, in __iter__
    for obj in it:
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/_snapshot_download.py", line 306, in _inner_hf_hub_download
    return hf_hub_download(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1007, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1168, in _hf_hub_download_to_cache_dir
    _download_to_tmp_and_move(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1735, in _download_to_tmp_and_move
    http_get(
OSError: [Errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/pipelines/base.py", line 311, in infer_framework_load_model
    model = model_class.from_pretrained(model, **fp32_kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 604, in from_pretrained
    return model_class.from_pretrained(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4900, in from_pretrained
    checkpoint_files, sharded_metadata = _get_resolved_checkpoint_files(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1200, in _get_resolved_checkpoint_files
    checkpoint_files, sharded_metadata = get_checkpoint_shard_files(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 1084, in get_checkpoint_shard_files
    cached_filenames = cached_files(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 567, in cached_files
    raise e
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 494, in cached_files
    snapshot_download(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/_snapshot_download.py", line 332, in snapshot_download
    thread_map(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/tqdm/notebook.py", line 250, in __iter__
    for obj in it:
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/_snapshot_download.py", line 306, in _inner_hf_hub_download
    return hf_hub_download(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1007, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1168, in _hf_hub_download_to_cache_dir
    _download_to_tmp_and_move(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1735, in _download_to_tmp_and_move
    http_get(
OSError: [Errno 122] Disk quota exceeded

while loading with LlamaForCausalLM, an error is thrown:
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/pipelines/base.py", line 293, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4843, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/configuration_utils.py", line 622, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/configuration_utils.py", line 662, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/configuration_utils.py", line 721, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 322, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 567, in cached_files
    raise e
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 479, in cached_files
    hf_hub_download(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1007, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1130, in _hf_hub_download_to_cache_dir
    _cache_commit_hash_for_specific_revision(storage_folder, revision, commit_hash)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 768, in _cache_commit_hash_for_specific_revision
    ref_path.write_text(commit_hash)
  File "/usr/lib/python3.9/pathlib.py", line 1286, in write_text
    return f.write(data)
OSError: [Errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/pipelines/base.py", line 311, in infer_framework_load_model
    model = model_class.from_pretrained(model, **fp32_kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4843, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/configuration_utils.py", line 622, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/configuration_utils.py", line 662, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/configuration_utils.py", line 721, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 322, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 567, in cached_files
    raise e
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/transformers/utils/hub.py", line 479, in cached_files
    hf_hub_download(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1007, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1130, in _hf_hub_download_to_cache_dir
    _cache_commit_hash_for_specific_revision(storage_folder, revision, commit_hash)
  File "/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 768, in _cache_commit_hash_for_specific_revision
    ref_path.write_text(commit_hash)
  File "/usr/lib/python3.9/pathlib.py", line 1286, in write_text
    return f.write(data)
OSError: [Errno 122] Disk quota exceeded

In [7]:
def format_codebook_for_prompt(codebook_dict):
    formatted_lines = []
    for supercat, data in codebook_dict.items():        
        formatted_lines.append(f"{supercat}: {data['name']}")
        for sub, sub_name in data['subs'].items():
            formatted_lines.append(f"  - {sub}: {sub_name}")        
        formatted_lines.append("") 
    
    return "\n".join(formatted_lines)

codebook_string = format_codebook_for_prompt(codebook)

In [8]:
print(codebook_string)

100: Macroeconomics
  - 101: Inflation, prices, and interest rates
  - 103: Unemployment rate
  - 104: Monetary Supply, Central Bank, and the Treasury
  - 105: National Budget, Debt, public spending
  - 107: Taxation, Tax policy, and Tax Reform
  - 108: Industrial Policy, Privatisation, Nationalisation

200: Civil Rights
  - 201: Ethnic Minority and Racial Group Discrimination
  - 202: Gender and Sexual Orientation Discrimination
  - 207: Freedom of Speech & Religion
  - 208: Right to Privacy and Access to Government Information
  - 230: Immigration

300: Health
  - 301: Health Care Reform
  - 321: Regulation of Drug Industry, Medical Devices, and Clinical Labs
  - 325: Health Manpower and Training
  - 331: Prevention, Communicable Diseases and Health Promotion
  - 332: Infants and Children
  - 334: Long-Term Care, Home Health, and Rehabilitation
  - 344: Drug and Alcohol or Substance Abuse Treatment

400: Agriculture
  - 401: Agricultural Trade
  - 406: Animal Welfare
  - 408: Fisheries and Fishing

500: Labour and Employment
  - 502: Employment Training and Workforce Development
  - 503: Employee Benefits
  - 504: Employee Relations and Labour Unions
  - 505: Fair Labour Standards
  - 506: Youth Employment and Child Labour
  - 508: Parental Leave and Child Care
  - 529: Migrant and Seasonal Workers

600: Education
  - 601: Higher Education
  - 602: Elementary and Secondary Education
  - 603: Education of Underprivileged Students
  - 604: Vocational Education
  - 606: Special Education

700: Environment
  - 701: Water Pollution
  - 703: Waste Disposal
  - 705: Air Pollution, Global Warming, and Noise Pollution
  - 709: Species and Forest Protection

800: Energy
  - 801: Nuclear Energy and Nuclear Regulatory Issues
  - 803: Natural Gas and Oil
  - 805: Coal
  - 806: Alternative and Renewable Energy
  - 807: Energy Conservation

1000: Transportation
  - 1001: Mass and Public Transportation and Safety
  - 1002: Highway (Road) Construction, Maintenance, and Safety
  - 1003: Airports, Airlines, Air Traffic Control and Safety
  - 1005: Railroad Transportation and Safety
  - 1006: Truck and Automobile Transportation and Safety

1200: Law, Crime, and Family Issues
  - 1202: White Collar Crime and Organized Crime
  - 1203: Illegal Drug Production, Trafficking, and Control
  - 1205: Prison System
  - 1206: Juvenile Crime and the Juvenile Justice System
  - 1207: Child Abuse
  - 1208: Family Issues
  - 1209: Police, Fire, and Weapons Control
  - 1211: Riots and Crime Prevention

1300: Social Welfare
  - 1302: Poverty and Assistance for Low-Income Families
  - 1303: Elderly Issues and Elderly Assistance Programs, State Pensions
  - 1304: Assistance to the Disabled and Handicapped
  - 1305: Social Services and Volunteer Associations

1400: Planning and Housing Issues
  - 1401: Housing and Community Development
  - 1406: Low and Middle Income Housing Programs and Needs
  - 1407: Veterans Housing Assistance and Military Housing Programs
  - 1409: Housing Assistance for Homeless and Homeless Issues
  - 1410: Mortgages

1500: Finance and Domestic Commerce
  - 1501: Banking System and Financial Institution Regulation
  - 1521: Small Business Issues
  - 1524: Tourism

1600: Defence
  - 1603: Military Intelligence, Intelligence Services, Espionage
  - 1608: Manpower, Military Personnel and Dependents
  - 1609: Veterans Issues
  - 1610: Military Procurement and Weapons System Acquisitions and Evaluation
  - 1627: Domestic and International Terrorism

1800: Foreign Trade
  - 1803: Export Promotion and Regulation, Export Credit Agencies
  - 1806: Productivity and Competitiveness of U.K. Business, U.K. Balance of Payments

1900: International Affairs
  - 1901: Foreign Aid
  - 1907: China
  - 1909: Eastern Europe
  - 1910: Western Europe, Common Market Issues
  - 1911: Africa
  - 1920: Middle East
  - 1926: International Organizations other than Finance
  - 1930: North America and North Atlantic Ocean

2000: Government Operations
  - 2001: Intergovernmental Relations
  - 2011: Executive-Legislative Relations and Parliamentary Operations
  - 2012: Political Parties, Campaigns, and Voter Registration
  - 2032: Prime Ministerial or Ministerial Scandals and Resignations

In [12]:
examples_string = """
Excerpt: "We must cap energy bills immediately to protect families from the soaring cost of gas and electricity this winter."
JSON Response: {"codes": [800, 803, 807]}
# Logic: 800 (Energy) is the super; 803 (Gas/Oil) and 807 (Conservation/Bills) are the subs.

Excerpt: "The crisis in our prisons is a direct result of the failure to tackle illegal drug trafficking on our streets."
JSON Response: {"codes": [1200, 1203, 1205]}
# Logic: 1200 (Law/Crime) is the super; 1203 (Trafficking) and 1205 (Prisons) are the subs.

Excerpt: "Investing in high-speed rail will not only improve our transport infrastructure but also create thousands of high-skilled jobs for young people."
JSON Response: {"codes": [1000, 1005, 500, 506]}
# Logic: Multi-label across Transportation (1000/1005) and Labour (500/506).

Excerpt: "We are committed to protecting the rights of EU citizens living here while ensuring our border points have the resources to manage migration flows."
JSON Response: {"codes": [200, 230, 500, 529]}
# Logic: Distinguishes between the right to be here (200/230) and the administrative/worker aspect (500/529).

Excerpt: "Yes, I will."
JSON Response: {"codes": []}
# Logic: No category is relevant to this excerpt so the list of labels is empty
"""

In [13]:
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your task is to annotate debate excerpts using a specific hierarchical coding schema.
RULES:
1. Every subcategory must be preceded by its parent supercategory.
2. If a text discusses multiple topics (e.g., both Tax and Health), provide all relevant codes.
3. Only use codes provided in the codebook below.
4. Return ONLY a valid JSON object. Do not include introductory text.
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}
<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
JSON Response:<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

In [11]:
df_val=pd.read_csv('labelling_validation.csv')
df_val

,ID,Text,Claim_Labels
0,0,"So knife crime's going to go up, because the e...","1200, 1211"
1,1,Of course Gordon Brown's right to say there's ...,"100, 107, 1300, 1302, 600, 602, 603, 1200, 1208"
2,2,"You won't admit the truth, will you? The truth...",NaN
3,3,"I tell you how we pay for it. We would, for in...","100, 107,"
4,4,"You just, look, there's no point in speculatin...",NaN
...,...,...,...
364,1426,I think the lady makes a very important point....,"100, 103, 1200, 1207, 1900, 1910, 500, 506"
365,1756,I've met some of the people who have rightly c...,"1200, 1207"
366,2601,"Well, I share the frustration of both our ques...","1900, 1910, 400, 406, 200, 202, 230"
367,3070,You're saying people voted for 10% tariffs on ...,"1000, 1006"
368,3356,I think this question of enthusiasm is really ...,"2000, 2032, 1200, 1208"

In [16]:
with open("all_turns_shuffled.txt", "r") as f:
    lines = f.read().split("\n")
    
lines

['0',
 "So knife crime's going to go up, because the evidence is there, Carla. Reduce stop-and-search, knife crime soars. No, it doesn't.",
 '',
 '1',
 "Of course Gordon Brown's right to say there's a link. Michael, you know this better than we do. You know there's a link between poverty at home and underperformance in the classroom. It's that link which is holding back so many children. That's what's unfair. That link is the link that I want to help solve. We would do it partly through the tax proposals I've talked about earlier, giving people £700 back in their pocket by raising the income tax threshold to £10,000 so that people on ordinary incomes who aren't being helped at the moment are helped. And through our proposal, we call it - it's a slightly technocratic phrase - we call it a pupil premium. It basically means extra money, £2.5 billion. That would, for instance, allow our schools to reduce the average class size in an average primary school down to 20. I have three young children. Two of them go to a local school, at eight and five. I see myself as a father that what happens to a young child in a reception class, years one, two and three, is so important in developing their self-confidence, their social skills, their willingness to learn. Get it right at that early age, and we can really help people later in life. That's what I believe in.",
 '',
 '2',
 "You won't admit the truth, will you? The truth is there's nothing we can do.",
 '',
 '3',
 'I tell you how we pay for it. We would, for instance, stop the huge unfair loopholes that only benefit the very wealthy at the top of the tax system. At the moment, the top 10% earners in this country get twice as much tax subsidy from all of the rest of you when they make contributions to their pension pot than everybody else. We say give people tax relief on their pension contributions, but make sure that they are the same and use that money so that no-one pays any income tax on the first £10,000 they earn.',
 '',
 '4',
 "You just, look, there's no point in speculating about that at the moment, cos we're a long way off taking the decision.",
 '',
 '5',
 "I'm just talking numbers. We haven't even mentioned housing yet. Oh, no, I ignore that nonsense. Complete nonsense. I'm just talking pure facts. Housing. We have to build one new home every two minutes just to cope with legal net migration under this Conservative government. It is literally impossible. And as for the numbers coming in, I would respond to this. 50% of the three quarters of a million who are coming in a year are dependents. They're not wealth creators. And mass migration is making us poorer. You'll hear, oh, GDP's going up. Well, of course it is. There are more people. GDP per capita, our relative wealth, has declined for the last six consecutive quarters.",
 '',
 '6',
 "We need strong big business in this country. We do, and one thing, can I just come in on that David? Yes, yes. But one thing I think business needs, and again this is a difference of view, I think we need to stay within the European Union. Because I think it would be a disaster for our businesses. I mean, give David Cameron credit, he believes in us staying in the EU, but I'm afraid he's being dragged by his party to exit from the EU. Now again, I've got to say to this audience, I've got to say to this audience, I think that would be a real problem for our country.",
 '',
 '7',
 "have to spend money wisely. Folks, I've explained to you, we've massively increased over the last few years the percentage of the national cake we put into the NHS for a worse return. Does nobody else acknowledge we need to spend the money better?",
 '',
 '8',
 "Let me perhaps draw out one of them. David Cameron keeps repeating we've got nothing to say. We're the only party, actually, in this general election campaign who've got a plan fully costed to get people off benefits and into work. That's been independently recognised. I think it's a general... It's almost a philosophical issue here. Do you think the best way to help people who are vulnerable or poor is to constantly giving them more benefits through greater dependency on the state? Or do you provide incentives to let them help themselves where they can? That is what our very, very radical tax switch, so you keep more money when you start working, would precisely do - it would get people off that benefits dependency into work. I think that's what most people agree is the absolute priority these days.",
 '',
 '9',
 "Well, we won't be able to do anything unless we win the election. We've obviously only been in opposition so far. I have been frustrated, if I'm honest, that these strikes have gone on as long as they have gone on. The strikes are very bad for patients. People are very anxious about the strikes. I don't think doctors want to be on strike. As I said earlier, my wife works in one of the big London hospitals, so I know first-hand and relayed every night, pressure that NHS staff are under. It's been unrelenting during Covid, unrelenting now because of waiting lists. So what we would do is instead of arguing about who gets in the room first to negotiate with the doctors, we would roll up our sleeves in a grown-up way, get in the room and settle this dispute so that patients can get the care they need. Doctors can get back to work, and the country can move forward, because we can't go on like this anymore. And the sooner we have a bit of grown-up politics in this, the better, I think, because we absolutely need to move forward as a country.",
 '',
 '10',
 "So Scotland has a migration problem. The problem is we don't have enough migrants because Scotland has a declining working age population. So we need people to come. And you know what? I am genuinely fed up going to speak to businesses. going to speak to health care workers, going to speak to people in our social care sector, in our schools and beyond, who say that they need more colleagues. Businesses who want to expand, who need people to come and work with them and for them. That's why I'm in favour of migration. And this race to the right that is happening in Westminster is so, so wrong. We can do better. We must demand better, not just from the Tories, but from the Labour Party too. And the SNP will always do that.",
 '',
 '11',
 "The reality is the SNP can't do just the same as Tory does. On the point of the anti-austerity motion that Ed Miliband talks about...",
 '',
 '12',
 'I believe in making a success of Brexit.',
 '',
 '13',
 "Thank you, Julie, and everyone watching tonight. Firstly, I want to express my condolences to everyone affected by Friday's attack. This atrocity should give us all pause for thought. None of us yet know the full details, so politicians should avoid knee-jerk responses. But we do know that our justice system has been hollowed out. Violent crime is up. Our prison's in crisis. Our police overstretched. Listen to nurses and they'll say the same about our National Health Service. Teachers the same about our schools. Deep cuts to vital public services. The fabric of our communities. Happened at the same time the government made huge tax giveaways to the richest few and to big business. Labour will make very different choices. We will be on your side, rebuilding our country for the many, not the few.",
 '',
 '14',
 "What happened was completely wrong and the Prime Minister has rightly apologised for that, apologised to veterans but also to all of us because he was representing all of us. I'm from Portsmouth, I've also been Defence Secretary and my wish at the end of this week is that all of our veterans feel completely treasured. And I'm hoping tonight to convince you of some things that are important to them, important to their legacy. And I couldn't do that if I wasn't straight with you on that issue.",
 '',
 '15',
 "I would like to see a levelling upwards when it comes to fairness, because what I'm deeply worried about is the kinds of rules, for example, that will break up families, that will end up in things like immigration detention, that has things like a minimum income rule. I think all of those are deeply unfair. Family reunion ought to be supported, so we need fair immigration rules.",
 '',
 '16',
 "No, I voted for remain. I wanted to remain, but now we've left and there's no going back. But... Sorry? No, I'm not. No, that is not our policy. Never has been our policy. I voted for remain, but we voted to leave. We're out. I accept that. We're not going back. Do you not see here... But we do need... We've got a very botched deal. If you talk to any business that's trying to trade, they will tell you it's not good enough. I think we can do more on defence and security, by the way, with our European partners. But we're not going back in. We're not going back into the single market, the customs union, and we're not going back to freedom of movement. That is very, very clear and set out in our manifesto, because we did have a referendum, it split us down the middle, and we do not want to go through that again. But you can see why.",
 '',
 '17',
 "Tell me how you're going to balance the books.",
 '',
 '18',
 "But you said that you had a point about the policy. I'm just telling you, I disagree with you. 15 other European countries just a few weeks ago decided that they agree with me. Did the Supreme Court call it unlawful? Well, I've been crystal clear, and that's why we've passed a new piece of legislation to address the concerns of our court, because I respect our court. They raised concerns, that's why we passed a new piece of legislation, and that's why their flights will now go if I'm Prime Minister. And when it comes to the ECHR, I am crystal clear. I believe everything that we are doing is in compliance with our international obligations, but if a foreign court, including the European Court, forces me to choose between our country's national security and membership of that court, I'm going to choose this country's national security every single time.",
 '',
 '19',
 "And there'd be more refugees then, yeah?",
 '',
 '20',
 'Greens holding you to account on that in the Parliament. Doing a good job.',
 '',
 '21',
 'You voted for the Bedroom Tax nine times, are you proud about that as well?',
 '',
 '22',
 "No, no, no. What I do think we need to do is we've got to provide more council housing and more social housing, but to restore people's trust, I think it has to be done by local councils and it must be for local people.",
 '',
 '23',
 "I want to thank you for watching tonight. A vote for Labour is a vote for hope. We are the party that created our NHS, introduced the minimum wage and will end NHS privatisation, introduce a living wage of at least £10 an hour and end the scandalous crisis in social care that leaves 1.5 million older people without the care they need. A Labour government will support you and invest in your community. We are on your side. Let's bring real change to our country so that it works for the many, not the few. Vote Labour on the 12th of December.",
 '',
 '24',
 "You've just admitted, if the population's growing by 2.5 million people in the last three years alone, you haven't got a labour shortage. You've got to make work pay, you've got to train your own people. We haven't got a people shortage. There's no labour shortage. Does anyone else agree there's no labour shortage? We haven't got a people shortage, but too many people, work doesn't pay.",
 '',
 '25',
 "Plaid Cymru want to build 10,000 new affordable houses over the next 10 years. But we also want to make owning and running a household more affordable. So we want to create a Welsh energy company, Ynni Cymru, that will allow us to use Welsh natural resources to bring down the cost of energy for families and houses across Wales. We want to scrap the cruel and unnecessary bedroom tax. And we want to scrap letting agency fees so that it's cheaper to rent.",
 '',
 '26',
 "But, Nick, The Institute of Fiscal Studies that you were quoting a few minutes ago says that your proposals for financing your tax cuts are highly speculative, they don't know how you'e going to get the money. That's what they say about your proposals. They're not thought out, you're too big a risk on the economy, just like David is. We are trying to get people back to work in difficult situations, low inflation, low interest rates, get the economy moving, don't take money and shrink the economy now. That's the way to get people back to work.",
 '',
 '27',
 "Well, the truth is that trust has absolutely collapsed in politicians, because people are sick and tired of politicians promising things and then not delivering. And we saw that with Labour Party manifestos. We saw it with the referendum, of course, when the £9 million Conservative government leaflet promised to carry out the will of the people, and it's not yet been done. We have to get it done, and after that, trust can start to be rebuilt.",
 '',
 '28',
 "Well, Carly, politics is about choices. So inevitably, people will have differing views. And the electors decide who they want to carry out that policy for the next four or five years. But I did in a previous question talk about the National Health Service. There are areas where it seems everybody wants the same thing. And when it comes to resolving the care crisis, when it comes to the National Health Service being free at the point of delivery, there is actually quite broad agreement across all the parties. So there should be areas in which parties can work together. Whilst everybody here agrees on climate change, I've got a slight issue with that, in that what we're doing is putting a lot of people out of work and making the poor give lots of money to the rich. Yes, we want a cleaner planet, but I don't think the way we're currently doing it is right. So there'll always be disagreement.",
 '',
 '29',
 "Well it's possibly the question that is uppermost in everybody's mind right now and of course all of our thoughts remain with those affected by that horrific and cowardly attack in the centre of London on Saturday night and of course with the people of Manchester as well. This is one of the greatest responsibilities for any politician. and I think the first thing politicians need to do is be honest. There are no easy answers and often the knee-jerk responses are the wrong ones. Firstly, we've got to tackle and address and challenge extremism wherever we find it. And I believe very strongly that we have to do that with the Muslim community. We mustn't scapegoat the Muslim community, because it's wrong. Most Muslims are as appalled at these attacks as the rest of us. But it would also be counterproductive. because we're going to find it easier to root out extremism if we're working in partnership with that community. Secondly, we've got to make sure we invest in our security and intelligence services, and we've got to make sure we invest in our police. Obviously, one of the big issues of debate today has been the reduction in police numbers in England, 20,000 fewer police officers. In Scotland, we've maintained police numbers and we've increased the numbers of police officers who are trained to bear firearms. So after the Manchester attack, Police Scotland was able to have an increased level of policing from within its own resources without calling on the military, although we're very grateful for the offer of help from the military. So these are the things we've got to do. Two final points I would make are these. I've made one of them already about not scapegoating particular communities. But secondly, we must make sure that in our determination, and all of us share it to keep the population safe, we don't start to undermine our own freedoms and civil liberties, because these are part of what makes us who we are.",
 '',
 '30',
 "Well, absolutely right. The gentleman has got it nailed on the head. I mean, north of England is the most disenfranchised part of the United Kingdom. Look, I want Scotland to be independent. I'm not here to advocate for Yorkshire independence. I'll leave you to do that if you wish. But look, I absolutely see the benefit that Scotland has had, even with the limited powers of devolution that we have. So yes, of course, the people of northern England, I think, have been the most disenfranchised. I just want to touch upon one or two things that were said by Katrina, and I think the question was exceptionally important. We're believers in a proportional system. In Scotland we have a hybrid proportional system which works well in the Scottish Parliament. It's designed not to have a majority. There's only been one majority in the history of devolution and that's because we literally broke the system. But it's never been, it's not designed for a majority and it forces the SNP, who's the government at the moment, to work with other parties to find a compromise. So we definitely would support that. Also support, I should say, the abolition of the House of Lords. We've never taken a peerage, never ever will.",
 '',
 '31',
 "Charlotte, you're right. We've got to live within our means as a country. And that's why under my plan, we'll cut the deficit every year and we'll balance the books. But we'll do it a different way from David Cameron. And I reject his plan to double the spending cuts next year, because I think for you and so many people in this audience who rely on our NHS, that would be a disaster. So here's our plan. Our plan is to have fair taxes, to reverse David Cameron's tax cut for millionaires, which has given every millionaire in Britain £43,000 a year. It's to clamp down on that tax avoidance and raise seven and a half billion pounds a year. It's to protect education and health. But outside some key areas like that, to see spending fall. And it's also about something else. Because by raising living standards of working people in this country, we can get more tax revenues in, and we can get the deficit down. It's a fair plan. It's a better plan. A better plan from David Cameron's carrying on as he is.",
 '',
 '32',
 'Yes.',
 '',
 '33',
 "Look, what I'm being really clear to people about is that I want to make sure we maximise the Liberal Democrat number of MPs. We're basically going to beat lots of Conservative MPs, I hope, a few in Scotland, a few SNP MPs, but I'm determined to focus in on that. I've been in politics... OK, so that's not a question you're going to answer, just to be clear. Well, I'll explain why, Fiona. I've been in politics a little while. I've seen a lot of Lib Dem leaders. And sometimes they focus on what happens after the election. And I've noticed that when they do that, they don't focus on the job in hand, which is trying to win local champions and Liberal Democrats across the country. And I'm going to try and do that.",
 '',
 '34',
 "And we have, not they do have problems, but what they don't have are the alternative systems for people to make use of. All the indications show that the public will use public transport, if it's reliable, if it's affordable, and if it's safe. There wasn't adequate alternative methods of transportation in both those cities at the time. The ground work could not be done. Contrast and compare.",
 '',
 '35',

In [17]:
for i in range(3688):
    target_i = lines.index(str(i))
    repl = lines[target_i+1]
    df_val.loc[(df_val['Text'].isna()) & (df_val['ID']==i), 'Text'] = repl
df_val

,ID,Text,Claim_Labels
0,0,"So knife crime's going to go up, because the e...","1200, 1211"
1,1,Of course Gordon Brown's right to say there's ...,"100, 107, 1300, 1302, 600, 602, 603, 1200, 1208"
2,2,"You won't admit the truth, will you? The truth...",NaN
3,3,"I tell you how we pay for it. We would, for in...","100, 107,"
4,4,"You just, look, there's no point in speculatin...",NaN
...,...,...,...
364,1426,I think the lady makes a very important point....,"100, 103, 1200, 1207, 1900, 1910, 500, 506"
365,1756,I've met some of the people who have rightly c...,"1200, 1207"
366,2601,"Well, I share the frustration of both our ques...","1900, 1910, 400, 406, 200, 202, 230"
367,3070,You're saying people voted for 10% tariffs on ...,"1000, 1006"
368,3356,I think this question of enthusiasm is really ...,"2000, 2032, 1200, 1208"

In [18]:
df_val['Claim_Labels'] = df_val['Claim_Labels'].fillna('')
df_val

,ID,Text,Claim_Labels
0,0,"So knife crime's going to go up, because the e...","1200, 1211"
1,1,Of course Gordon Brown's right to say there's ...,"100, 107, 1300, 1302, 600, 602, 603, 1200, 1208"
2,2,"You won't admit the truth, will you? The truth...",
3,3,"I tell you how we pay for it. We would, for in...","100, 107,"
4,4,"You just, look, there's no point in speculatin...",
...,...,...,...
364,1426,I think the lady makes a very important point....,"100, 103, 1200, 1207, 1900, 1910, 500, 506"
365,1756,I've met some of the people who have rightly c...,"1200, 1207"
366,2601,"Well, I share the frustration of both our ques...","1900, 1910, 400, 406, 200, 202, 230"
367,3070,You're saying people voted for 10% tariffs on ...,"1000, 1006"
368,3356,I think this question of enthusiasm is really ...,"2000, 2032, 1200, 1208"

In [19]:
df_val.to_csv("labelling_validation.csv")

In [ ]:
results = []
with torch.no_grad():
    for index, row in tqdm(df_val.iterrows(), total=len(df_val)):
        prompt = create_labelling_prompt(row['Text'], examples_string, codebook_string)
        
        output = llm_model(
            prompt,
            max_new_tokens=100,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        generated_text = output[0]['generated_text'].split("assistant")[-1].strip()
        
        json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
        if json_match:
            codes = json.loads(json_match.group())['codes']
        else:
            codes = []
            
        results.append({
        "id": row['ID'],
        "llm_predicted_codes": codes
        })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_1.csv", index=False)

  2%|▏         | 7/369 [00:36<31:36,  5.24s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
 63%|██████▎   | 234/369 [20:32<11:19,  5.03s/it]

In [45]:
len(results)

369

In [46]:
results_df

       id                                llm_predicted_codes
0       0                                 [1200, 1207, 1209]
1       1                [600, 603, 500, 508, 100, 107, 105]
2       2                                                 []
3       3                          [100, 107, 105, 500, 508]
4       4                                                 []
..    ...                                                ...
364  1426  [500, 506, 1000, 1002, 1006, 1005, 600, 601, 6...
365  1756                               [200, 207, 600, 601]
366  2601                                                 []
367  3070                                       [1800, 1803]
368  3356  [200, 201, 202, 2032, 1000, 1001, 500, 502, 50...

[369 rows x 2 columns]

Next Iteration

In [21]:
elaborate = {
    101: ["Discussion of the importance of lowering inflation/interest rates", "Downplaying the importance of inflation/interest rate falls"],
    103: [],
    104: ["Emphasising the importance of the Bank of England and Treasury", "Disregard for the Bank of England or Treasury"],
    105: ["Greater public spending", "Lower public spending"],
    107: ["Tax increases", "Tax reductions"],
    108: ["Support for nationalisation, or opposition to privatisation", "Opposition to nationalisation"],
    201: ["Speaking against racial discrimination, recognising discrimination as a problem", "Downplaying the importance of racial discrimination"],
    202: ["Recognising gender/sexual orientation discrimination as a problem", "Downplaying importance of gender/sexual orientation discrimination"],
    207: ["Support for freedom of expression, including protest. Also, freedom of religion", "Opposition to freedom-of-speech actions such as protests"],
    208: ["Supporting the need to preserve privacy and rights against government interference", "Prioritising security needs over the need for privacy"],
    230: ["Support for immigrants (that would be blocked by strict border control)", "Opposition to immigration"],
    301: ["Support for reforming healthcare", "Support for the NHS as it is, speaking favourably about the NHS without requiring reform"],
    321: ["Support for regulation of the drug industry and control of NHS costs to third parties", "Opposition to drug industry regulation"],
    325: ["Calls for more health staff, or support for the work of health staff", "Criticism of the work of health staff"],
    331: ["Promoting danger of communicable diseases and advocating measures to combat them", "Downplaying the effect of communicable diseases and resisting measures to combat them"],
    332: [],
    334: [],
    344: ["Support for drug, alcohol, or substance abuse treatment. Addicts seen as victims", "Focus on law enforcement against drug, alcohol, or substance abusers. Addicts seen as perpetrators"],
    401: ["Support for British agriculture and/or farmers", "Promotion of measures against farming interests"],
    406: ["Support for policies promoting animal welfare", "Downplaying animal welfare concerns"],
    408: ["Support for policies promoting the fishing industry", "Promotion of measures against fishing interests"],
    502: ["Increasing the number of jobs", "Prioritising other concerns over job creation"],
    503: ["Supporting the protection of employee benefits like pensions", "Prioritising other concerns over employee benefits"],
    504: ["Greater negotiation with labour unions", "Opposition to/criticism of labour unions"],
    505: ["Support for higher wages, ‘better’ working conditions", "Opposition to wage increases"],
    506: ["Increasing youth employment rates", "Arguments against youth employment"],
    508: ["In support of greater investment in childcare", "Rejecting need for increased investment in childcare"],
    529: ["More migrant workers", "Fewer migrant workers"],
    601: ["Support for actions improving access to higher education, e.g. lowering tuition fees", "Opposition to higher education changes"],
    602: ["Support for investment in schools, or for the work of schools", "Opposition to increased investment in schools"],
    603: ["More investment in education for underprivileged students", "Opposition to increased investment in underprivileged students"],
    604: ["Support of vocational education programs such as apprenticeships", "Criticism of vocational education"],
    606: ["Support for special needs education (as opposed to integration in mainstream schools)", "Arguments for integration of mainstream integration of children with special needs"],
    701: [],
    703: [],
    705: ["In support of efforts to limit air pollution, noise pollution, or climate change (or global warming)", "Against efforts to limit air pollution or climate change"],
    709: ["Prioritising the protection of species or forests", "Deprioritising protection of species or forests"],
    801: ["Support for nuclear energy", "Against nuclear energy"],
    803: ["Support for investment in oil and gas exploration", "Against oil and gas exploration"],
    805: ["Support for coal energy and/or the coal industry", "Against coal energy"],
    806: ["Support for alternative and renewable energy", "Against renewable energy initiatives"],
    807: ["Support for efforts to conserve energy, e.g. turning off lights", "Criticism of energy conservation"],
    1001: ["Advocacy for public transportation", "Downplaying the value of public transportation"],
    1002: ["Support for road construction/maintenance projects", "Opposition to road construction projects"],
    1003: ["Support for air travel", "Against air travel"],
    1005: ["Support for train travel", "Criticism of train travel"],
    1006: ["Support for car travel/the automobile industry", "Against car travel"],
    1202: ["Support for strong measures targeting white collar crime", "Downplaying importance of tackling white collar crime"],
    1203: ["Support for greater drug law enforcement", "Opposition to drug law enforcement. Promotion of legalisation arguments"],
    1205: ["Support for more imprisonment and/or higher sentences", "Opposition to greater imprisonment"],
    1206: ["Support for juvenile detention", "Opposition to juvenile detention"],
    1207: [],
    1208: [],
    1209: ["Greater investment in the police, or support of the police’s work", "Calls for police budget cuts or criticism of police operations"],
    1211: ["More power to police for crime prevention", "Opposing the expansion of physical police powers such as stop-and-search"],
    1302: ["More assistance for low income families", "Opposition to increasing welfare or subsidies for low income families"],
    1303: ["More investment in the elderly", "Criticism of excessive spending on the elderly"],
    1304: ["Support for providing social welfare to the disabled", "Opposition to expanding social welfare for the disabled"],
    1305: ["Support for the work of charitable organisations", "Criticism of the role or influence of charitable organisations"],
    1401: ["Support for an increase in number of homes being built", "Opposition to new housing developments"],
    1406: ["More housing support for low and middle income families", "Opposition to government-funded housing support"],
    1407: ["More housing assistance for veterans", "Opposition to specific housing for veterans"],
    1409: ["More housing assistance for the homeless", "Opposition to housing programs for the homeless"],
    1410: ["Support for mortgages or home ownership", "Criticism of mortgage support"],
    1501: ["Greater banking regulation", "Support for deregulation or less oversight of the banking sector"],
    1521: ["Prioritising small business concerns", "Deprioritising small business needs"],
    1524: ["Support for tourism", "Opposition to tourism growth"],
    1603: ["Speaking in support of the military intelligence services, e.g. MI5", "Criticism of intelligence services"],
    1608: ["Support for strengthening the military", "Advocacy for reduced defence spending"],
    1609: ["Support for veterans", "Opposition to benefits or special status for veterans"],
    1610: ["Supporting the acquisition and/or maintenance of weapons", "Opposing the purchase or upkeep of military weapons"],
    1627: ["Support for measures taken against terrorism", "Criticism of counter-terrorism measures"],
    1803: ["Support for greater British export", "Against greater export"],
    1806: ["Positive comments about UK business in comparison to non-UK", "Negative comments about UK business"],
    1901: ["Support for offering aid to other countries", "Opposition to foreign aid or calls to reduce international spending"],
    1907: ["In support of cooperation with China", "Against cooperation with China"],
    1909: ["In support of Eastern European countries", "Criticism of Eastern European nations"],
    1910: ["Greater cooperation with European partners", "Opposing cooperation with European partners"],
    1911: ["In support of helping or intervening in African nations", "Against providing support or intervention in African nations"],
    1920: ["In support of intervention in the Middle East", "Opposing intervention or military presence in the Middle East"],
    1926: ["Collaboration with non-finance international organisations like the UN", "Opposition to working with the UN or similar international bodies"],
    1930: ["Speaking favourably about North America, or North American leaders such as the US President", "Speaking unfavourably about North America or the US President"],
    2001: ["Greater devolution powers for regions", "Opposing devolution or supporting more centralised government"],
    2011: ["Keeping parliamentary operations as they are, against reforms such as abolishing the Lords", "Supporting reform of parliamentary operations, e.g. the abolition of the Lords"],
    2012: ["Speaking favourably about political parties or campaigns", "Speaking negatively about political parties or specific campaigns"],
    2032: ["Emphasising the negative effect of ministerial scandals", "Downplaying or dismissing the impact of ministerial scandals"]
}

In [34]:
for i in elaborate:print(i)

101
103
104
105
107
108
201
202
207
208
230
301
321
325
331
332
334
344
401
406
408
502
503
504
505
506
508
529
601
602
603
604
606
701
703
705
709
801
803
805
806
807
1001
1002
1003
1005
1006
1202
1203
1205
1206
1207
1208
1209
1211
1302
1303
1304
1305
1401
1406
1407
1409
1410
1501
1521
1524
1603
1608
1609
1610
1627
1803
1806
1901
1907
1909
1910
1911
1920
1926
1930
2001
2011
2012
2032

In [23]:
codebook_lines = codebook_string.split("\n")
new_codebook_lines = []
for line in codebook_lines:
    new_line = line
    for i in elaborate:
        if str(i) in line and len(elaborate[i])>0:
            support = elaborate[i][0]
            against = elaborate[i][1]
            elaboration = support+" or "+against
            new_line += " ("+elaboration+")"                                                    
    new_codebook_lines.append(new_line)
codebook_string_new = "\n".join(new_codebook_lines)
print(codebook_string_new)

100: Macroeconomics
  - 101: Inflation, prices, and interest rates (Discussion of the importance of lowering inflation/interest rates or Downplaying the importance of inflation/interest rate falls)
  - 103: Unemployment rate
  - 104: Monetary Supply, Central Bank, and the Treasury (Emphasising the importance of the Bank of England and Treasury or Disregard for the Bank of England or Treasury)
  - 105: National Budget, Debt, public spending (Greater public spending or Lower public spending)
  - 107: Taxation, Tax policy, and Tax Reform (Tax increases or Tax reductions)
  - 108: Industrial Policy, Privatisation, Nationalisation (Support for nationalisation, or opposition to privatisation or Opposition to nationalisation)

200: Civil Rights
  - 201: Ethnic Minority and Racial Group Discrimination (Speaking against racial discrimination, recognising discrimination as a problem or Downplaying the importance of racial discrimination)
  - 202: Gender and Sexual Orientation Discrimination (Recognising gender/sexual orientation discrimination as a problem or Downplaying importance of gender/sexual orientation discrimination)
  - 207: Freedom of Speech & Religion (Support for freedom of expression, including protest. Also, freedom of religion or Opposition to freedom-of-speech actions such as protests)
  - 208: Right to Privacy and Access to Government Information (Supporting the need to preserve privacy and rights against government interference or Prioritising security needs over the need for privacy)
  - 230: Immigration (Support for immigrants (that would be blocked by strict border control) or Opposition to immigration)

300: Health
  - 301: Health Care Reform (Support for reforming healthcare or Support for the NHS as it is, speaking favourably about the NHS without requiring reform)
  - 321: Regulation of Drug Industry, Medical Devices, and Clinical Labs (Support for regulation of the drug industry and control of NHS costs to third parties or Opposition to drug industry regulation)
  - 325: Health Manpower and Training (Calls for more health staff, or support for the work of health staff or Criticism of the work of health staff)
  - 331: Prevention, Communicable Diseases and Health Promotion (Promoting danger of communicable diseases and advocating measures to combat them or Downplaying the effect of communicable diseases and resisting measures to combat them)
  - 332: Infants and Children
  - 334: Long-Term Care, Home Health, and Rehabilitation
  - 344: Drug and Alcohol or Substance Abuse Treatment (Support for drug, alcohol, or substance abuse treatment. Addicts seen as victims or Focus on law enforcement against drug, alcohol, or substance abusers. Addicts seen as perpetrators)

400: Agriculture
  - 401: Agricultural Trade (Support for British agriculture and/or farmers or Promotion of measures against farming interests)
  - 406: Animal Welfare (Support for policies promoting animal welfare or Downplaying animal welfare concerns)
  - 408: Fisheries and Fishing (Support for policies promoting the fishing industry or Promotion of measures against fishing interests)

500: Labour and Employment
  - 502: Employment Training and Workforce Development (Increasing the number of jobs or Prioritising other concerns over job creation)
  - 503: Employee Benefits (Supporting the protection of employee benefits like pensions or Prioritising other concerns over employee benefits)
  - 504: Employee Relations and Labour Unions (Greater negotiation with labour unions or Opposition to/criticism of labour unions)
  - 505: Fair Labour Standards (Support for higher wages, ‘better’ working conditions or Opposition to wage increases)
  - 506: Youth Employment and Child Labour (Increasing youth employment rates or Arguments against youth employment)
  - 508: Parental Leave and Child Care (In support of greater investment in childcare or Rejecting need for increased investment in childcare)
  - 529: Migrant and Seasonal Workers (More migrant workers or Fewer migrant workers)

600: Education
  - 601: Higher Education (Support for actions improving access to higher education, e.g. lowering tuition fees or Opposition to higher education changes)
  - 602: Elementary and Secondary Education (Support for investment in schools, or for the work of schools or Opposition to increased investment in schools)
  - 603: Education of Underprivileged Students (More investment in education for underprivileged students or Opposition to increased investment in underprivileged students)
  - 604: Vocational Education (Support of vocational education programs such as apprenticeships or Criticism of vocational education)
  - 606: Special Education (Support for special needs education (as opposed to integration in mainstream schools) or Arguments for integration of mainstream integration of children with special needs)

700: Environment
  - 701: Water Pollution
  - 703: Waste Disposal
  - 705: Air Pollution, Global Warming, and Noise Pollution (In support of efforts to limit air pollution, noise pollution, or climate change (or global warming) or Against efforts to limit air pollution or climate change)
  - 709: Species and Forest Protection (Prioritising the protection of species or forests or Deprioritising protection of species or forests)

800: Energy
  - 801: Nuclear Energy and Nuclear Regulatory Issues (Support for nuclear energy or Against nuclear energy)
  - 803: Natural Gas and Oil (Support for investment in oil and gas exploration or Against oil and gas exploration)
  - 805: Coal (Support for coal energy and/or the coal industry or Against coal energy)
  - 806: Alternative and Renewable Energy (Support for alternative and renewable energy or Against renewable energy initiatives)
  - 807: Energy Conservation (Support for efforts to conserve energy, e.g. turning off lights or Criticism of energy conservation)

1000: Transportation
  - 1001: Mass and Public Transportation and Safety (Advocacy for public transportation or Downplaying the value of public transportation)
  - 1002: Highway (Road) Construction, Maintenance, and Safety (Support for road construction/maintenance projects or Opposition to road construction projects)
  - 1003: Airports, Airlines, Air Traffic Control and Safety (Support for air travel or Against air travel)
  - 1005: Railroad Transportation and Safety (Support for train travel or Criticism of train travel)
  - 1006: Truck and Automobile Transportation and Safety (Support for car travel/the automobile industry or Against car travel)

1200: Law, Crime, and Family Issues
  - 1202: White Collar Crime and Organized Crime (Recognising gender/sexual orientation discrimination as a problem or Downplaying importance of gender/sexual orientation discrimination) (Support for strong measures targeting white collar crime or Downplaying importance of tackling white collar crime)
  - 1203: Illegal Drug Production, Trafficking, and Control (Support for greater drug law enforcement or Opposition to drug law enforcement. Promotion of legalisation arguments)
  - 1205: Prison System (Support for more imprisonment and/or higher sentences or Opposition to greater imprisonment)
  - 1206: Juvenile Crime and the Juvenile Justice System (Support for juvenile detention or Opposition to juvenile detention)
  - 1207: Child Abuse (Support for freedom of expression, including protest. Also, freedom of religion or Opposition to freedom-of-speech actions such as protests)
  - 1208: Family Issues (Supporting the need to preserve privacy and rights against government interference or Prioritising security needs over the need for privacy)
  - 1209: Police, Fire, and Weapons Control (Greater investment in the police, or support of the police’s work or Calls for police budget cuts or criticism of police operations)
  - 1211: Riots and Crime Prevention (More power to police for crime prevention or Opposing the expansion of physical police powers such as stop-and-search)

1300: Social Welfare
  - 1302: Poverty and Assistance for Low-Income Families (More assistance for low income families or Opposition to increasing welfare or subsidies for low income families)
  - 1303: Elderly Issues and Elderly Assistance Programs, State Pensions (More investment in the elderly or Criticism of excessive spending on the elderly)
  - 1304: Assistance to the Disabled and Handicapped (Support for providing social welfare to the disabled or Opposition to expanding social welfare for the disabled)
  - 1305: Social Services and Volunteer Associations (Support for the work of charitable organisations or Criticism of the role or influence of charitable organisations)

1400: Planning and Housing Issues
  - 1401: Housing and Community Development (Support for British agriculture and/or farmers or Promotion of measures against farming interests) (Support for an increase in number of homes being built or Opposition to new housing developments)
  - 1406: Low and Middle Income Housing Programs and Needs (Support for policies promoting animal welfare or Downplaying animal welfare concerns) (More housing support for low and middle income families or Opposition to government-funded housing support)
  - 1407: Veterans Housing Assistance and Military Housing Programs (More housing assistance for veterans or Opposition to specific housing for veterans)
  - 1409: Housing Assistance for Homeless and Homeless Issues (More housing assistance for the homeless or Opposition to housing programs for the homeless)
  - 1410: Mortgages (Support for mortgages or home ownership or Criticism of mortgage support)

1500: Finance and Domestic Commerce
  - 1501: Banking System and Financial Institution Regulation (Greater banking regulation or Support for deregulation or less oversight of the banking sector)
  - 1521: Small Business Issues (Prioritising small business concerns or Deprioritising small business needs)
  - 1524: Tourism (Support for tourism or Opposition to tourism growth)

1600: Defence
  - 1603: Military Intelligence, Intelligence Services, Espionage (More investment in education for underprivileged students or Opposition to increased investment in underprivileged students) (Speaking in support of the military intelligence services, e.g. MI5 or Criticism of intelligence services)
  - 1608: Manpower, Military Personnel and Dependents (Support for strengthening the military or Advocacy for reduced defence spending)
  - 1609: Veterans Issues (Support for veterans or Opposition to benefits or special status for veterans)
  - 1610: Military Procurement and Weapons System Acquisitions and Evaluation (Supporting the acquisition and/or maintenance of weapons or Opposing the purchase or upkeep of military weapons)
  - 1627: Domestic and International Terrorism (Support for measures taken against terrorism or Criticism of counter-terrorism measures)

1800: Foreign Trade
  - 1803: Export Promotion and Regulation, Export Credit Agencies (Support for investment in oil and gas exploration or Against oil and gas exploration) (Support for greater British export or Against greater export)
  - 1806: Productivity and Competitiveness of U.K. Business, U.K. Balance of Payments (Support for alternative and renewable energy or Against renewable energy initiatives) (Positive comments about UK business in comparison to non-UK or Negative comments about UK business)

1900: International Affairs
  - 1901: Foreign Aid (Support for offering aid to other countries or Opposition to foreign aid or calls to reduce international spending)
  - 1907: China (In support of cooperation with China or Against cooperation with China)
  - 1909: Eastern Europe (In support of Eastern European countries or Criticism of Eastern European nations)
  - 1910: Western Europe, Common Market Issues (Greater cooperation with European partners or Opposing cooperation with European partners)
  - 1911: Africa (In support of helping or intervening in African nations or Against providing support or intervention in African nations)
  - 1920: Middle East (In support of intervention in the Middle East or Opposing intervention or military presence in the Middle East)
  - 1926: International Organizations other than Finance (Collaboration with non-finance international organisations like the UN or Opposition to working with the UN or similar international bodies)
  - 1930: North America and North Atlantic Ocean (Speaking favourably about North America, or North American leaders such as the US President or Speaking unfavourably about North America or the US President)

2000: Government Operations
  - 2001: Intergovernmental Relations (Greater devolution powers for regions or Opposing devolution or supporting more centralised government)
  - 2011: Executive-Legislative Relations and Parliamentary Operations (Speaking against racial discrimination, recognising discrimination as a problem or Downplaying the importance of racial discrimination) (Keeping parliamentary operations as they are, against reforms such as abolishing the Lords or Supporting reform of parliamentary operations, e.g. the abolition of the Lords)
  - 2012: Political Parties, Campaigns, and Voter Registration (Speaking against racial discrimination, recognising discrimination as a problem or Downplaying the importance of racial discrimination) (Speaking favourably about political parties or campaigns or Speaking negatively about political parties or specific campaigns)
  - 2032: Prime Ministerial or Ministerial Scandals and Resignations (Emphasising the negative effect of ministerial scandals or Downplaying or dismissing the impact of ministerial scandals)

In [41]:
results = []
with torch.no_grad():
    for index, row in tqdm(df_val.iterrows(), total=len(df_val)):
        prompt = create_labelling_prompt(row['Text'], examples_string, codebook_string_new)
        
        output = llm_model(
            prompt,
            max_new_tokens=100,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        generated_text = output[0]['generated_text'].split("assistant")[-1].strip()
        
        json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
        if json_match:
            codes = json.loads(json_match.group())['codes']
        else:
            codes = []
            
        results.append({
        "id": row['ID'],
        "llm_predicted_codes": codes
        })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_2.csv", index=False)

  0%|          | 0/369 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
  3%|▎         | 10/369 [01:15<48:38,  8.13s/it] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
100%|██████████| 369/369 [44:42<00:00,  7.27s/it]

In [42]:
results_df

       id                                llm_predicted_codes
0       0                                 [1201, 1211, 1209]
1       1                     [600, 603, 500, 508, 101, 105]
2       2                                                 []
3       3                               [150, 107, 105, 101]
4       4                                                 []
..    ...                                                ...
364  1426           [500, 506, 101, 103, 105, 301, 601, 604]
365  1756  [200, 207, 208, 600, 606, 700, 701, 705, 709, ...
366  2601  [400, 406, 407, 500, 529, 200, 230, 1000, 2011...
367  3070                                       [1800, 1803]
368  3356  [200, 201, 202, 207, 208, 1000, 1001, 500, 502...

[369 rows x 2 columns]

new

In [17]:
print(codebook_string)

100: Macroeconomics
  - 101: Inflation, prices, and interest rates
  - 103: Unemployment rate
  - 104: Monetary Supply, Central Bank, and the Treasury
  - 105: National Budget, Debt, public spending
  - 107: Taxation, Tax policy, and Tax Reform
  - 108: Industrial Policy, Privatisation, Nationalisation

200: Civil Rights
  - 201: Ethnic Minority and Racial Group Discrimination
  - 202: Gender and Sexual Orientation Discrimination
  - 207: Freedom of Speech & Religion
  - 208: Right to Privacy and Access to Government Information
  - 230: Immigration

300: Health
  - 301: Health Care Reform
  - 321: Regulation of Drug Industry, Medical Devices, and Clinical Labs
  - 325: Health Manpower and Training
  - 331: Prevention, Communicable Diseases and Health Promotion
  - 332: Infants and Children
  - 334: Long-Term Care, Home Health, and Rehabilitation
  - 344: Drug and Alcohol or Substance Abuse Treatment

400: Agriculture
  - 401: Agricultural Trade
  - 406: Animal Welfare
  - 408: Fisheries and Fishing

500: Labour and Employment
  - 502: Employment Training and Workforce Development
  - 503: Employee Benefits
  - 504: Employee Relations and Labour Unions
  - 505: Fair Labour Standards
  - 506: Youth Employment and Child Labour
  - 508: Parental Leave and Child Care
  - 529: Migrant and Seasonal Workers

600: Education
  - 601: Higher Education
  - 602: Elementary and Secondary Education
  - 603: Education of Underprivileged Students
  - 604: Vocational Education
  - 606: Special Education

700: Environment
  - 701: Water Pollution
  - 703: Waste Disposal
  - 705: Air Pollution, Global Warming, and Noise Pollution
  - 709: Species and Forest Protection

800: Energy
  - 801: Nuclear Energy and Nuclear Regulatory Issues
  - 803: Natural Gas and Oil
  - 805: Coal
  - 806: Alternative and Renewable Energy
  - 807: Energy Conservation

1000: Transportation
  - 1001: Mass and Public Transportation and Safety
  - 1002: Highway (Road) Construction, Maintenance, and Safety
  - 1003: Airports, Airlines, Air Traffic Control and Safety
  - 1005: Railroad Transportation and Safety
  - 1006: Truck and Automobile Transportation and Safety

1200: Law, Crime, and Family Issues
  - 1202: White Collar Crime and Organized Crime
  - 1203: Illegal Drug Production, Trafficking, and Control
  - 1205: Prison System
  - 1206: Juvenile Crime and the Juvenile Justice System
  - 1207: Child Abuse
  - 1208: Family Issues
  - 1209: Police, Fire, and Weapons Control
  - 1211: Riots and Crime Prevention

1300: Social Welfare
  - 1302: Poverty and Assistance for Low-Income Families
  - 1303: Elderly Issues and Elderly Assistance Programs, State Pensions
  - 1304: Assistance to the Disabled and Handicapped
  - 1305: Social Services and Volunteer Associations

1400: Planning and Housing Issues
  - 1401: Housing and Community Development
  - 1406: Low and Middle Income Housing Programs and Needs
  - 1407: Veterans Housing Assistance and Military Housing Programs
  - 1409: Housing Assistance for Homeless and Homeless Issues
  - 1410: Mortgages

1500: Finance and Domestic Commerce
  - 1501: Banking System and Financial Institution Regulation
  - 1521: Small Business Issues
  - 1524: Tourism

1600: Defence
  - 1603: Military Intelligence, Intelligence Services, Espionage
  - 1608: Manpower, Military Personnel and Dependents
  - 1609: Veterans Issues
  - 1610: Military Procurement and Weapons System Acquisitions and Evaluation
  - 1627: Domestic and International Terrorism

1800: Foreign Trade
  - 1803: Export Promotion and Regulation, Export Credit Agencies
  - 1806: Productivity and Competitiveness of U.K. Business, U.K. Balance of Payments

1900: International Affairs
  - 1901: Foreign Aid
  - 1907: China
  - 1909: Eastern Europe
  - 1910: Western Europe, Common Market Issues
  - 1911: Africa
  - 1920: Middle East
  - 1926: International Organizations other than Finance
  - 1930: North America and North Atlantic Ocean

2000: Government Operations
  - 2001: Intergovernmental Relations
  - 2011: Executive-Legislative Relations and Parliamentary Operations
  - 2012: Political Parties, Campaigns, and Voter Registration
  - 2032: Prime Ministerial or Ministerial Scandals and Resignations

In [28]:
elaborate_2 = {
    101: ["Discussion of the importance of lowering inflation/interest rates", "Downplaying the importance of inflation/interest rate falls"],
    103: ["Discussion of the number of people that are not employed"],
    104: ["Emphasising the importance of the Bank of England and Treasury", "Disregard for the Bank of England or Treasury"],
    105: ["Greater public spending", "Lower public spending"],
    107: ["Tax increases", "Tax reductions"],
    108: ["Support for nationalisation/opposition to privatisation", "Support for privatisation/opposition to nationalisation"],
    201: ["Speaking against racial discrimination, recognising discrimination as a problem", "Downplaying the importance of racial discrimination"],
    202: ["Recognising gender/sexual orientation discrimination as a problem", "Downplaying importance of gender/sexual orientation discrimination"],
    207: ["Support for freedom of expression, including protest. Also, freedom of religion", "Opposition to freedom-of-speech actions such as protests"],
    208: ["Supporting the need to preserve privacy and rights against government interference", "Prioritising security needs over the need for privacy"],
    230: ["Support for immigrants and flexible borders", "Opposition to immigration"],
    301: ["Support for reforming healthcare", "Support for the NHS as it is, speaking favourably about the NHS without requiring reform"],
    321: ["Support for regulation of the drug industry and control of NHS costs to third parties", "Opposition to drug industry regulation"],
    325: ["Calls for more health staff, or support for the work of health staff", "Criticism of the work of health staff"],
    331: ["Promoting danger of communicable diseases and advocating measures to combat them", "Downplaying the effect of communicable diseases and resisting measures to combat them"],
    332: ["Discussion of health care or health issues relating to infants and children"],
    334: ["Discussion of long-term care such as treatment in care homes or treatment of long-term illness"],
    344: ["Support for drug, alcohol, or substance abuse treatment. Addicts seen as victims", "Focus on law enforcement against drug, alcohol, or substance abusers. Addicts seen as perpetrators"],
    401: ["Support for British agriculture and/or farmers", "Promotion of measures against farming interests"],
    406: ["Support for policies promoting animal welfare", "Downplaying animal welfare concerns"],
    408: ["Support for policies promoting the fishing industry", "Promotion of measures against fishing interests"],
    502: ["Increasing the number of jobs", "Prioritising other concerns over job creation"],
    503: ["Supporting the protection of employee benefits like pensions", "Prioritising other concerns over employee benefits"],
    504: ["Greater negotiation with labour unions", "Opposition to/criticism of labour unions"],
    505: ["Support for higher wages, ‘better’ working conditions", "Opposition to wage increases"],
    506: ["Increasing youth employment rates", "Arguments against youth employment"],
    508: ["In support of greater investment in childcare", "Rejecting need for increased investment in childcare"],
    529: ["More migrant workers", "Fewer migrant workers"],
    601: ["Support for actions improving access to higher education, e.g. lowering tuition fees", "Opposition to higher education changes"],
    602: ["Support for investment in schools, or for the work of schools", "Opposition to increased investment in schools"],
    603: ["More investment in education for underprivileged students", "Opposition to increased investment in underprivileged students"],
    604: ["Support of vocational education programs such as apprenticeships", "Criticism of vocational education"],
    606: ["Support for special needs education (as opposed to integration in mainstream schools)", "Arguments for the integration of children with special needs into mainstream schools"],
    701: ["Discussion of water pollution"],
    703: ["Discussion of waste disposal by household or company"],
    705: ["In support of efforts to limit air pollution, noise pollution, or climate change (or global warming)", "Against efforts to limit air pollution or climate change"],
    709: ["Prioritising the protection of species or forests", "Deprioritising protection of species or forests"],
    801: ["Support for nuclear energy", "Against nuclear energy"],
    803: ["Support for investment in oil and gas exploration", "Against oil and gas exploration"],
    805: ["Support for coal energy and/or the coal industry", "Against coal energy"],
    806: ["Support for alternative and renewable energy", "Against renewable energy initiatives"],
    807: ["Support for efforts to conserve energy, e.g. turning off lights", "Criticism of energy conservation"],
    1001: ["Advocacy for public transportation", "Downplaying the value of public transportation"],
    1002: ["Support for road construction/maintenance projects", "Opposition to road construction projects"],
    1003: ["Support for air travel", "Against air travel"],
    1005: ["Support for train travel", "Criticism of train travel"],
    1006: ["Support for car travel/the automobile industry", "Against car travel"],
    1202: ["Support for strong measures targeting white collar crime", "Downplaying importance of tackling white collar crime"],
    1203: ["Support for greater drug law enforcement", "Opposition to drug law enforcement. Promotion of legalisation arguments"],
    1205: ["Support for more imprisonment and/or higher sentences", "Opposition to greater imprisonment"],
    1206: ["Support for juvenile detention", "Opposition to juvenile detention"],
    1207: ["Discussion of child abuse"],
    1208: ["Reference made to the speaker's family members"],
    1209: ["Greater investment in the police, or support of the police’s work", "Calls for police budget cuts or criticism of police operations"],
    1211: ["More power to police for crime prevention", "Opposing the expansion of physical police powers such as stop-and-search"],
    1302: ["More assistance for low income families", "Opposition to increasing welfare or subsidies for low income families"],
    1303: ["More investment in the elderly", "Criticism of excessive spending on the elderly"],
    1304: ["Support for providing social welfare to the disabled", "Opposition to expanding social welfare for the disabled"],
    1305: ["Support for the work of charitable organisations", "Criticism of the role or influence of charitable organisations"],
    1401: ["Support for an increase in number of homes being built", "Opposition to new housing developments"],
    1406: ["More housing support for low and middle income families", "Opposition to government-funded housing support"],
    1407: ["More housing assistance for veterans", "Opposition to specific housing for veterans"],
    1409: ["More housing assistance for the homeless", "Opposition to housing programs for the homeless"],
    1410: ["Support for mortgages or home ownership", "Criticism of mortgage support"],
    1501: ["Greater banking regulation", "Support for deregulation or less oversight of the banking sector"],
    1521: ["Prioritising small business concerns", "Deprioritising small business needs"],
    1524: ["Support for tourism", "Opposition to tourism growth"],
    1603: ["Speaking in support of the military intelligence services, e.g. MI5", "Criticism of intelligence services"],
    1608: ["Support for strengthening the military", "Advocacy for reduced defence spending"],
    1609: ["Support for veterans", "Opposition to benefits or special status for veterans"],
    1610: ["Supporting the acquisition and/or maintenance of weapons", "Opposing the purchase or upkeep of military weapons"],
    1627: ["Support for measures taken against terrorism", "Criticism of counter-terrorism measures"],
    1803: ["Support for greater British export", "Against greater export"],
    1806: ["Positive comments about UK business in comparison to non-UK", "Negative comments about UK business"],
    1901: ["Support for offering aid to other countries", "Opposition to foreign aid or calls to reduce international spending"],
    1907: ["In support of cooperation with China", "Against cooperation with China"],
    1909: ["In support of Eastern European countries", "Criticism of Eastern European nations"],
    1910: ["Greater cooperation with European partners", "Opposing cooperation with European partners"],
    1911: ["In support of helping or intervening in African nations", "Against providing support or intervention in African nations"],
    1920: ["In support of intervention in the Middle East", "Opposing intervention or military presence in the Middle East"],
    1926: ["Collaboration with non-finance international organisations like the UN", "Opposition to working with the UN or similar international bodies"],
    1930: ["Speaking favourably about North America, or North American leaders such as the US President", "Speaking unfavourably about North America or the US President"],
    2001: ["Greater devolution powers for regions", "Opposing devolution or supporting more centralised government"],
    2011: ["Keeping parliamentary operations as they are, against reforms such as abolishing the Lords", "Supporting reform of parliamentary operations, e.g. the abolition of the Lords"],
    2012: ["Speaking favourably about political parties or campaigns", "Speaking negatively about political parties or specific campaigns"],
    2032: ["Emphasising the negative effect of ministerial scandals", "Downplaying or dismissing the impact of ministerial scandals"]
}

In [24]:
def update_codebook(text, descriptions):
    lines = text.split('\n')
    updated_lines = []
    
    for line in lines:        
        match = re.search(r'^\s*-\s*(\d+):', line)
        
        if match:
            code_id = int(match.group(1))
            if code_id in descriptions:
                desc_list = descriptions[code_id]
                formatted_desc = f" ({' or '.join(desc_list)})"
                line = line.rstrip() + formatted_desc
        
        updated_lines.append(line)
        
    return '\n'.join(updated_lines)

In [29]:
codebook_string_3 = update_codebook(codebook_string, elaborate_2)

In [30]:
print(codebook_string_3)

100: Macroeconomics
  - 101: Inflation, prices, and interest rates (Discussion of the importance of lowering inflation/interest rates or Downplaying the importance of inflation/interest rate falls)
  - 103: Unemployment rate (Discussion of the number of people that are not employed)
  - 104: Monetary Supply, Central Bank, and the Treasury (Emphasising the importance of the Bank of England and Treasury or Disregard for the Bank of England or Treasury)
  - 105: National Budget, Debt, public spending (Greater public spending or Lower public spending)
  - 107: Taxation, Tax policy, and Tax Reform (Tax increases or Tax reductions)
  - 108: Industrial Policy, Privatisation, Nationalisation (Support for nationalisation/opposition to privatisation or Support for privatisation/opposition to nationalisation)

200: Civil Rights
  - 201: Ethnic Minority and Racial Group Discrimination (Speaking against racial discrimination, recognising discrimination as a problem or Downplaying the importance of racial discrimination)
  - 202: Gender and Sexual Orientation Discrimination (Recognising gender/sexual orientation discrimination as a problem or Downplaying importance of gender/sexual orientation discrimination)
  - 207: Freedom of Speech & Religion (Support for freedom of expression, including protest. Also, freedom of religion or Opposition to freedom-of-speech actions such as protests)
  - 208: Right to Privacy and Access to Government Information (Supporting the need to preserve privacy and rights against government interference or Prioritising security needs over the need for privacy)
  - 230: Immigration (Support for immigrants and flexible borders or Opposition to immigration)

300: Health
  - 301: Health Care Reform (Support for reforming healthcare or Support for the NHS as it is, speaking favourably about the NHS without requiring reform)
  - 321: Regulation of Drug Industry, Medical Devices, and Clinical Labs (Support for regulation of the drug industry and control of NHS costs to third parties or Opposition to drug industry regulation)
  - 325: Health Manpower and Training (Calls for more health staff, or support for the work of health staff or Criticism of the work of health staff)
  - 331: Prevention, Communicable Diseases and Health Promotion (Promoting danger of communicable diseases and advocating measures to combat them or Downplaying the effect of communicable diseases and resisting measures to combat them)
  - 332: Infants and Children (Discussion of health care or health issues relating to infants and children)
  - 334: Long-Term Care, Home Health, and Rehabilitation (Discussion of long-term care such as treatment in care homes or treatment of long-term illness)
  - 344: Drug and Alcohol or Substance Abuse Treatment (Support for drug, alcohol, or substance abuse treatment. Addicts seen as victims or Focus on law enforcement against drug, alcohol, or substance abusers. Addicts seen as perpetrators)

400: Agriculture
  - 401: Agricultural Trade (Support for British agriculture and/or farmers or Promotion of measures against farming interests)
  - 406: Animal Welfare (Support for policies promoting animal welfare or Downplaying animal welfare concerns)
  - 408: Fisheries and Fishing (Support for policies promoting the fishing industry or Promotion of measures against fishing interests)

500: Labour and Employment
  - 502: Employment Training and Workforce Development (Increasing the number of jobs or Prioritising other concerns over job creation)
  - 503: Employee Benefits (Supporting the protection of employee benefits like pensions or Prioritising other concerns over employee benefits)
  - 504: Employee Relations and Labour Unions (Greater negotiation with labour unions or Opposition to/criticism of labour unions)
  - 505: Fair Labour Standards (Support for higher wages, ‘better’ working conditions or Opposition to wage increases)
  - 506: Youth Employment and Child Labour (Increasing youth employment rates or Arguments against youth employment)
  - 508: Parental Leave and Child Care (In support of greater investment in childcare or Rejecting need for increased investment in childcare)
  - 529: Migrant and Seasonal Workers (More migrant workers or Fewer migrant workers)

600: Education
  - 601: Higher Education (Support for actions improving access to higher education, e.g. lowering tuition fees or Opposition to higher education changes)
  - 602: Elementary and Secondary Education (Support for investment in schools, or for the work of schools or Opposition to increased investment in schools)
  - 603: Education of Underprivileged Students (More investment in education for underprivileged students or Opposition to increased investment in underprivileged students)
  - 604: Vocational Education (Support of vocational education programs such as apprenticeships or Criticism of vocational education)
  - 606: Special Education (Support for special needs education (as opposed to integration in mainstream schools) or Arguments for the integration of children with special needs into mainstream schools)

700: Environment
  - 701: Water Pollution (Discussion of water pollution)
  - 703: Waste Disposal (Discussion of waste disposal by household or company)
  - 705: Air Pollution, Global Warming, and Noise Pollution (In support of efforts to limit air pollution, noise pollution, or climate change (or global warming) or Against efforts to limit air pollution or climate change)
  - 709: Species and Forest Protection (Prioritising the protection of species or forests or Deprioritising protection of species or forests)

800: Energy
  - 801: Nuclear Energy and Nuclear Regulatory Issues (Support for nuclear energy or Against nuclear energy)
  - 803: Natural Gas and Oil (Support for investment in oil and gas exploration or Against oil and gas exploration)
  - 805: Coal (Support for coal energy and/or the coal industry or Against coal energy)
  - 806: Alternative and Renewable Energy (Support for alternative and renewable energy or Against renewable energy initiatives)
  - 807: Energy Conservation (Support for efforts to conserve energy, e.g. turning off lights or Criticism of energy conservation)

1000: Transportation
  - 1001: Mass and Public Transportation and Safety (Advocacy for public transportation or Downplaying the value of public transportation)
  - 1002: Highway (Road) Construction, Maintenance, and Safety (Support for road construction/maintenance projects or Opposition to road construction projects)
  - 1003: Airports, Airlines, Air Traffic Control and Safety (Support for air travel or Against air travel)
  - 1005: Railroad Transportation and Safety (Support for train travel or Criticism of train travel)
  - 1006: Truck and Automobile Transportation and Safety (Support for car travel/the automobile industry or Against car travel)

1200: Law, Crime, and Family Issues
  - 1202: White Collar Crime and Organized Crime (Support for strong measures targeting white collar crime or Downplaying importance of tackling white collar crime)
  - 1203: Illegal Drug Production, Trafficking, and Control (Support for greater drug law enforcement or Opposition to drug law enforcement. Promotion of legalisation arguments)
  - 1205: Prison System (Support for more imprisonment and/or higher sentences or Opposition to greater imprisonment)
  - 1206: Juvenile Crime and the Juvenile Justice System (Support for juvenile detention or Opposition to juvenile detention)
  - 1207: Child Abuse (Discussion of child abuse)
  - 1208: Family Issues (Reference made to the speaker's family members)
  - 1209: Police, Fire, and Weapons Control (Greater investment in the police, or support of the police’s work or Calls for police budget cuts or criticism of police operations)
  - 1211: Riots and Crime Prevention (More power to police for crime prevention or Opposing the expansion of physical police powers such as stop-and-search)

1300: Social Welfare
  - 1302: Poverty and Assistance for Low-Income Families (More assistance for low income families or Opposition to increasing welfare or subsidies for low income families)
  - 1303: Elderly Issues and Elderly Assistance Programs, State Pensions (More investment in the elderly or Criticism of excessive spending on the elderly)
  - 1304: Assistance to the Disabled and Handicapped (Support for providing social welfare to the disabled or Opposition to expanding social welfare for the disabled)
  - 1305: Social Services and Volunteer Associations (Support for the work of charitable organisations or Criticism of the role or influence of charitable organisations)

1400: Planning and Housing Issues
  - 1401: Housing and Community Development (Support for an increase in number of homes being built or Opposition to new housing developments)
  - 1406: Low and Middle Income Housing Programs and Needs (More housing support for low and middle income families or Opposition to government-funded housing support)
  - 1407: Veterans Housing Assistance and Military Housing Programs (More housing assistance for veterans or Opposition to specific housing for veterans)
  - 1409: Housing Assistance for Homeless and Homeless Issues (More housing assistance for the homeless or Opposition to housing programs for the homeless)
  - 1410: Mortgages (Support for mortgages or home ownership or Criticism of mortgage support)

1500: Finance and Domestic Commerce
  - 1501: Banking System and Financial Institution Regulation (Greater banking regulation or Support for deregulation or less oversight of the banking sector)
  - 1521: Small Business Issues (Prioritising small business concerns or Deprioritising small business needs)
  - 1524: Tourism (Support for tourism or Opposition to tourism growth)

1600: Defence
  - 1603: Military Intelligence, Intelligence Services, Espionage (Speaking in support of the military intelligence services, e.g. MI5 or Criticism of intelligence services)
  - 1608: Manpower, Military Personnel and Dependents (Support for strengthening the military or Advocacy for reduced defence spending)
  - 1609: Veterans Issues (Support for veterans or Opposition to benefits or special status for veterans)
  - 1610: Military Procurement and Weapons System Acquisitions and Evaluation (Supporting the acquisition and/or maintenance of weapons or Opposing the purchase or upkeep of military weapons)
  - 1627: Domestic and International Terrorism (Support for measures taken against terrorism or Criticism of counter-terrorism measures)

1800: Foreign Trade
  - 1803: Export Promotion and Regulation, Export Credit Agencies (Support for greater British export or Against greater export)
  - 1806: Productivity and Competitiveness of U.K. Business, U.K. Balance of Payments (Positive comments about UK business in comparison to non-UK or Negative comments about UK business)

1900: International Affairs
  - 1901: Foreign Aid (Support for offering aid to other countries or Opposition to foreign aid or calls to reduce international spending)
  - 1907: China (In support of cooperation with China or Against cooperation with China)
  - 1909: Eastern Europe (In support of Eastern European countries or Criticism of Eastern European nations)
  - 1910: Western Europe, Common Market Issues (Greater cooperation with European partners or Opposing cooperation with European partners)
  - 1911: Africa (In support of helping or intervening in African nations or Against providing support or intervention in African nations)
  - 1920: Middle East (In support of intervention in the Middle East or Opposing intervention or military presence in the Middle East)
  - 1926: International Organizations other than Finance (Collaboration with non-finance international organisations like the UN or Opposition to working with the UN or similar international bodies)
  - 1930: North America and North Atlantic Ocean (Speaking favourably about North America, or North American leaders such as the US President or Speaking unfavourably about North America or the US President)

2000: Government Operations
  - 2001: Intergovernmental Relations (Greater devolution powers for regions or Opposing devolution or supporting more centralised government)
  - 2011: Executive-Legislative Relations and Parliamentary Operations (Keeping parliamentary operations as they are, against reforms such as abolishing the Lords or Supporting reform of parliamentary operations, e.g. the abolition of the Lords)
  - 2012: Political Parties, Campaigns, and Voter Registration (Speaking favourably about political parties or campaigns or Speaking negatively about political parties or specific campaigns)
  - 2032: Prime Ministerial or Ministerial Scandals and Resignations (Emphasising the negative effect of ministerial scandals or Downplaying or dismissing the impact of ministerial scandals)

In [20]:
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your task is to annotate debate excerpts using a specific hierarchical coding schema.
RULES:
1. Every subcategory must be preceded by its parent supercategory.
2. If a text discusses multiple topics (e.g., both Tax and Health), provide all relevant codes.
3. Only use codes provided in the codebook below.
4. Return a JSON object with two fields: "reasoning" (a brief explanation) and "codes" (the list of integers).
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}
<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
JSON Response:<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

In [29]:
results = []
with torch.no_grad():
    for index, row in tqdm(df_val.iterrows(), total=len(df_val)):
        prompt = create_labelling_prompt(row['Text'], examples_string, codebook_string_3)
        
        output = llm_model(
            prompt,
            max_new_tokens=100,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        generated_text = output[0]['generated_text'].split("assistant")[-1].strip()
        
        json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
        codes = []
        reasoning = ""
        
        if json_match:
            data = json.loads(json_match.group())                
            codes = data.get('codes', [])
            reasoning = data.get('reasoning', "")
            
        results.append({
        "id": row['ID'],
        "llm_reasoning": reasoning,
        "claim_labels": codes
        })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_3.csv", index=False)

  0%|          | 0/369 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
  3%|▎         | 10/369 [01:20<50:15,  8.40s/it] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
100%|██████████| 369/369 [46:45<00:00,  7.60s/it]

new

In [28]:
def robust_json_parser(text):    
    try:        
        clean_text = re.sub(r'^```json\s*|\s*```$', '', text.strip(), flags=re.MULTILINE)
        return json.loads(clean_text)
    except json.JSONDecodeError:
        pass
    # save the codes if there's an error
    code_match = re.search(r'"codes":\s*(\[[\d,\s]*\])', text)
    if code_match:
        try:            
            codes = ast.literal_eval(code_match.group(1))
            return {"reasoning": "Extracted via Regex (JSON was broken)", "codes": codes}
        except:
            pass
            
    # if all else fails
    return {"reasoning": "CRITICAL ERROR: Could not parse JSON", "codes": []}

In [29]:
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist. Annotate debate excerpts using the provided hierarchical coding schema.

STRICT RULES:
1. IDENTIFICATION PATH: For every label, you must first identify the Supercategory (e.g., 100) and then the specific Subcategory (e.g., 107).
2. PARENT RULE: You MUST always include the parent code. For example, if you choose 107, your list must also contain 100. [100, 107] is correct; [107] is a failure.
3. CODEBOOK ONLY: Use ONLY the integer codes listed in the codebook below. Do not invent new codes.
4. MULTI-LABELLING: Debate text often covers multiple domains. If a speaker mentions "Tax" (107) and "Hospitals" (301), you MUST include both paths: [100, 107, 300, 301].
5. RESPONSE FORMAT: Return a JSON object with "reasoning" and "codes". In the reasoning field, use single quotes (') for any quotes or emphasis. Never use double quotes inside the JSON values.

CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}
<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt: "{excerpt}"
JSON Response:<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

In [30]:
examples_string_2 = """
Excerpt: "We will fund the NHS by closing tax loopholes and ensuring the wealthy pay their fair share while protecting the poorest."
JSON Response: {
  "reasoning": "1. Health (300/301) is mentioned ('fund the NHS'). 2. Macroeconomics (100/107) is mentioned ('tax loopholes'). 3. Social Welfare (1300/1302) is mentioned ('protecting the poorest').",
  "codes": [300, 301, 100, 107, 1300, 1302]
}

Excerpt: "Building new homes on the green belt is the only way to solve the housing crisis and create local jobs."
JSON Response: {
  "reasoning": "1. Planning/Housing (1400/1401) is the focus ('building new homes'). 2. Labour/Employment (500/502) is mentioned as a secondary benefit ('create local jobs').",
  "codes": [1400, 1401, 500, 502]
}
"""

In [31]:
results = []
with torch.no_grad():
    for index, row in tqdm(df_val.iterrows(), total=len(df_val)):
        prompt = create_labelling_prompt(row['Text'], examples_string_2, codebook_string_3)
        
        output = llm_model(
            prompt,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        generated_text = output[0]['generated_text'].split("assistant")[-1].strip()
        
#         json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
#         codes = []
#         reasoning = ""
        
#         if json_match:
#             data = json.loads(json_match.group())                
#             codes = data.get('codes', [])
#             reasoning = data.get('reasoning', "")

        data = robust_json_parser(generated_text)
            
        results.append({
            "id": row['ID'],
            "llm_reasoning": data.get('reasoning', ""),
            "claim_labels": data.get('codes', [])
        })
        
        # save progress every 20 rows
        if index % 20 == 0:
            pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_4.csv", index=False)

100%|██████████| 369/369 [1:01:53<00:00, 10.06s/it]

new

In [32]:

def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your task is to annotate debate excerpts using a specific hierarchical coding schema.
RULES:
1. Every subcategory must be preceded by its parent supercategory.
2. If a text discusses multiple topics (e.g., both Tax and Health), provide all relevant codes.
3. Only use codes provided in the codebook below.
4. Return ONLY a valid JSON object. Do not include introductory text.
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}
<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
JSON Response:<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

In [33]:
results = []
with torch.no_grad():
    for index, row in tqdm(df_val.iterrows(), total=len(df_val)):
        prompt = create_labelling_prompt(row['Text'], examples_string_2, codebook_string_3)
        
        output = llm_model(
            prompt,
            max_new_tokens=100,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        generated_text = output[0]['generated_text'].split("assistant")[-1].strip()
        
        json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
        if json_match:
            codes = json.loads(json_match.group())['codes']
        else:
            codes = []
            
        results.append({
        "id": row['ID'],
        "claim_labels": codes
        })

        # save progress every 20 rows
        if index % 20 == 0:
            pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)        
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_5.csv", index=False)

 43%|████▎     | 160/369 [20:59<27:25,  7.87s/it]

JSONDecodeError: Expecting ',' delimiter: line 3 column 24 (char 230)

In [18]:
results = []
with torch.no_grad():
    for index, row in tqdm(df_val.iterrows(), total=len(df_val)):
        prompt = create_labelling_prompt(row['Text'], examples_string, codebook_string)
        
        output = llm_model(
            prompt,
            max_new_tokens=100,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        generated_text = output[0]['generated_text'].split("assistant")[-1].strip()
        
        json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
        if json_match:
            codes = json.loads(json_match.group())['codes']
        else:
            codes = []
            
        results.append({
        "id": row['ID'],
        "llm_predicted_codes": codes
        })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_6.csv", index=False)

  0%|          | 0/369 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
  3%|▎         | 10/369 [00:57<38:28,  6.43s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
100%|██████████| 369/369 [34:46<00:00,  5.66s/it]

In [33]:
%%notify
results = []
with torch.no_grad():
    for index, row in tqdm(df_val.iterrows(), total=len(df_val)):
        prompt = create_labelling_prompt(row['Text'], examples_string, codebook_string_3)
        
        output = llm_model(
            prompt,
            max_new_tokens=100,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        generated_text = output[0]['generated_text'].split("assistant")[-1].strip()
        
        json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
        if json_match:
            codes = json.loads(json_match.group())['codes']
        else:
            codes = []
            
        results.append({
        "id": row['ID'],
        "claim_labels": codes
        })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_7.csv", index=False)

100%|██████████| 369/369 [44:15<00:00,  7.20s/it]

In [ ]:
# performance dropped so return to 6

In [ ]:
# stick to original codebook string
# what's in use now:
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your task is to annotate debate excerpts using a specific hierarchical coding schema.
RULES:
1. Every subcategory must be preceded by its parent supercategory.
2. If a text discusses multiple topics (e.g., both Tax and Health), provide all relevant codes.
3. Only use codes provided in the codebook below.
4. Return ONLY a valid JSON object. Do not include introductory text.
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}
<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
JSON Response:<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

examples_string = """
Excerpt: "We must cap energy bills immediately to protect families from the soaring cost of gas and electricity this winter."
JSON Response: {"codes": [800, 803, 807]}
# Logic: 800 (Energy) is the super; 803 (Gas/Oil) and 807 (Conservation/Bills) are the subs.

Excerpt: "The crisis in our prisons is a direct result of the failure to tackle illegal drug trafficking on our streets."
JSON Response: {"codes": [1200, 1203, 1205]}
# Logic: 1200 (Law/Crime) is the super; 1203 (Trafficking) and 1205 (Prisons) are the subs.

Excerpt: "Investing in high-speed rail will not only improve our transport infrastructure but also create thousands of high-skilled jobs for young people."
JSON Response: {"codes": [1000, 1005, 500, 506]}
# Logic: Multi-label across Transportation (1000/1005) and Labour (500/506).

Excerpt: "We are committed to protecting the rights of EU citizens living here while ensuring our border points have the resources to manage migration flows."
JSON Response: {"codes": [200, 230, 500, 529]}
# Logic: Distinguishes between the right to be here (200/230) and the administrative/worker aspect (500/529).

Excerpt: "Yes, I will."
JSON Response: {"codes": []}
# Logic: No category is relevant to this excerpt so the list of labels is empty
"""

# model info:

# model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"

# quant_config = BitsAndBytesConfig(
#     load_in_4bit=True,
#     bnb_4bit_compute_dtype=torch.bfloat16,
#     bnb_4bit_quant_type="nf4",
#     bnb_4bit_use_double_quant=True
# )

# llm_model = pipeline(
#     "text-generation",
#     model=model_id,
#     model_kwargs={
#         "quantization_config": quant_config,
#         "low_cpu_mem_usage": True,
#         "torch_dtype": torch.bfloat16
#     },
#     device_map="auto"
# )

# terminators = [
#     llm_model.tokenizer.eos_token_id,
#     llm_model.tokenizer.convert_tokens_to_ids("<|eot_id|>")
# ]

In [49]:
class ListDataset(Dataset):
    def __init__(self, original_list):
        self.original_list = original_list
    def __len__(self):
        return len(self.original_list)
    def __getitem__(self, i):
        return self.original_list[i]

In [50]:
%%notify

# speeding up labelling
prompts = [create_labelling_prompt(text, examples_string, codebook_string) for text in df_val['Text']]
dataset = ListDataset(prompts)

original_ids = df_val['ID'].tolist()
results = []

with torch.no_grad():
    for i, output in enumerate(tqdm(llm_model(dataset,
                                           max_new_tokens=100,
                                           eos_token_id=terminators,
                                           do_sample=False),
                                 total=len(prompts))):
        
        generated_text = output[0]['generated_text'].split("assistant")[-1].strip()
        
        json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
        if json_match:
            codes = json.loads(json_match.group())['codes']
        else:
            codes = []
            
        results.append({
        "id": original_ids[i],
        "claim_labels": codes
        })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_6_faster.csv", index=False)

  0%|          | 0/369 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  0%|          | 1/369 [00:32<3:20:22, 32.67s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  1%|▏         | 5/369 [01:04<1:10:31, 11.62s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  2%|▏         | 9/369 [01:36<58:11,  9.70s/it]  Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  4%|▎         | 13/369 [02:08<53:03,  8.94s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  5%|▍         | 17/369 [02:41<50:32,  8.62s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  6%|▌         | 21/369 [03:12<48:28,  8.36s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  7%|▋         | 25/369 [03:44<47:00,  8.20s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  8%|▊         | 29/369 [04:17<46:50,  8.27s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
  9%|▉         | 33/369 [04:50<46:00,  8.21s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 10%|█         | 37/369 [05:22<45:02,  8.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 11%|█         | 41/369 [05:55<44:51,  8.21s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 12%|█▏        | 45/369 [06:27<43:49,  8.12s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 13%|█▎        | 49/369 [06:58<42:54,  8.05s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 14%|█▍        | 53/369 [07:30<42:19,  8.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 15%|█▌        | 57/369 [08:02<41:23,  7.96s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 17%|█▋        | 61/369 [08:34<40:54,  7.97s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 18%|█▊        | 65/369 [09:06<40:41,  8.03s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 19%|█▊        | 69/369 [09:40<40:37,  8.13s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 20%|█▉        | 73/369 [10:12<40:06,  8.13s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 21%|██        | 77/369 [10:45<39:41,  8.15s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 22%|██▏       | 81/369 [11:18<39:11,  8.16s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 23%|██▎       | 85/369 [11:50<38:25,  8.12s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 24%|██▍       | 89/369 [12:22<37:42,  8.08s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 25%|██▌       | 93/369 [12:54<37:09,  8.08s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 26%|██▋       | 97/369 [13:27<36:44,  8.10s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 27%|██▋       | 101/369 [13:58<35:52,  8.03s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 28%|██▊       | 105/369 [14:30<35:23,  8.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 30%|██▉       | 109/369 [15:02<34:47,  8.03s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 31%|███       | 113/369 [15:24<30:50,  7.23s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 32%|███▏      | 117/369 [15:56<31:18,  7.45s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 33%|███▎      | 121/369 [16:29<31:58,  7.74s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 34%|███▍      | 125/369 [17:01<31:35,  7.77s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 35%|███▍      | 129/369 [17:32<31:16,  7.82s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 36%|███▌      | 133/369 [18:04<30:55,  7.86s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 37%|███▋      | 137/369 [18:37<30:39,  7.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 38%|███▊      | 141/369 [19:08<30:03,  7.91s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 39%|███▉      | 145/369 [19:42<30:04,  8.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 40%|████      | 149/369 [20:14<29:34,  8.07s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 41%|████▏     | 153/369 [20:47<29:17,  8.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 43%|████▎     | 157/369 [21:20<28:42,  8.13s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 44%|████▎     | 161/369 [21:52<28:13,  8.14s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 45%|████▍     | 165/369 [22:01<21:31,  6.33s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 46%|████▌     | 169/369 [22:33<22:50,  6.85s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 47%|████▋     | 173/369 [23:05<23:29,  7.19s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 48%|████▊     | 177/369 [23:37<23:53,  7.47s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 49%|████▉     | 181/369 [24:10<23:58,  7.65s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 50%|█████     | 185/369 [24:44<24:19,  7.93s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 51%|█████     | 189/369 [25:16<23:50,  7.95s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 52%|█████▏    | 193/369 [25:48<23:26,  7.99s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 53%|█████▎    | 197/369 [26:21<23:04,  8.05s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 54%|█████▍    | 201/369 [26:55<22:49,  8.15s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 56%|█████▌    | 205/369 [27:26<22:01,  8.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 57%|█████▋    | 209/369 [27:58<21:23,  8.02s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 58%|█████▊    | 213/369 [28:30<20:56,  8.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 59%|█████▉    | 217/369 [29:03<20:25,  8.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 60%|█████▉    | 221/369 [29:36<20:00,  8.11s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 61%|██████    | 225/369 [30:08<19:23,  8.08s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 62%|██████▏   | 229/369 [30:39<18:45,  8.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 63%|██████▎   | 233/369 [31:12<18:20,  8.09s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 64%|██████▍   | 237/369 [31:44<17:43,  8.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 65%|██████▌   | 241/369 [32:16<17:12,  8.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 66%|██████▋   | 245/369 [32:48<16:30,  7.99s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 67%|██████▋   | 249/369 [33:19<15:54,  7.95s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 69%|██████▊   | 253/369 [33:52<15:31,  8.03s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 70%|██████▉   | 257/369 [34:25<15:03,  8.07s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 71%|███████   | 261/369 [34:58<14:42,  8.17s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 72%|███████▏  | 265/369 [35:30<14:04,  8.12s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

 73%|███████▎  | 269/369 [36:03<13:32,  8.13s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 74%|███████▍  | 273/369 [36:35<12:58,  8.11s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 75%|███████▌  | 277/369 [37:08<12:25,  8.11s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 76%|███████▌  | 281/369 [37:39<11:47,  8.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 77%|███████▋  | 285/369 [38:12<11:17,  8.06s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 78%|███████▊  | 289/369 [38:43<10:41,  8.02s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 79%|███████▉  | 293/369 [39:16<10:11,  8.05s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 80%|████████  | 297/369 [39:43<09:11,  7.66s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 82%|████████▏ | 301/369 [40:14<08:44,  7.71s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 83%|████████▎ | 305/369 [40:46<08:17,  7.78s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 84%|████████▎ | 309/369 [41:18<07:51,  7.87s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 85%|████████▍ | 313/369 [41:51<07:26,  7.97s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 86%|████████▌ | 317/369 [42:23<06:56,  8.02s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 87%|████████▋ | 321/369 [42:56<06:26,  8.05s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 88%|████████▊ | 325/369 [43:28<05:53,  8.03s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 89%|████████▉ | 329/369 [43:57<05:13,  7.83s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 90%|█████████ | 333/369 [44:29<04:43,  7.88s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 91%|█████████▏| 337/369 [45:02<04:14,  7.96s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 92%|█████████▏| 341/369 [45:34<03:43,  7.97s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 93%|█████████▎| 345/369 [46:06<03:12,  8.00s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 95%|█████████▍| 349/369 [46:38<02:39,  7.98s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 96%|█████████▌| 353/369 [47:11<02:08,  8.04s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 97%|█████████▋| 357/369 [47:43<01:37,  8.09s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 98%|█████████▊| 361/369 [48:16<01:04,  8.08s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
 99%|█████████▉| 365/369 [48:48<00:32,  8.11s/it]Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
100%|██████████| 369/369 [48:56<00:00,  7.96s/it]

In [17]:
%%notify
# speed-up attempt 2
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = [
            create_labelling_prompt(row['Text'], examples_string, codebook_string)
            for _, row in batch.iterrows()
        ]
                
        outputs = llm_model(
            prompts,
            max_new_tokens=100,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        for output, (_, row) in zip(outputs, batch.iterrows()):            
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
            if json_match:
                codes = json.loads(json_match.group())['codes']
            else:
                codes = []

            results.append({
            "id": row['ID'],
            "claim_labels": codes
            })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_6_faster.csv", index=False)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [36]:
# ensuring logical consistency. subcategory must have supercategory
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your task is to annotate debate excerpts using a specific hierarchical coding schema.
RULES:
1. Provide all relevant subcategories. Then, include the parent '00' code for each subcategory used.
2. Subcategories (e.g., 107, 105) MUST be accompanied by their Supercategory (e.g., 100) 
3. If a text discusses multiple topics (e.g., both Tax and Health), provide all relevant codes.
4. Only use codes provided in the codebook below.
5. If no topics in the codebook apply, the lists must be empty []. Do not guess.
6. Ignore general rhetorical statements about 'fairness' or 'growth' unless a specific policy proposal is mentioned.

OUTPUT FORMAT:
Return ONLY a JSON object with this structure:
{{
  "reasoning": "A brief explanation of why these topics apply.",
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}
<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
JSON Response:<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

In [22]:
%%notify
# logical consistency and chain of thought
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = [
            create_labelling_prompt(row['Text'], examples_string, codebook_string)
            for _, row in batch.iterrows()
        ]
                
        outputs = llm_model(
            prompts,
            max_new_tokens=100,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        for output, (_, row) in zip(outputs, batch.iterrows()):            
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
            if json_match:
                supercats = json.loads(json_match.group())['identified_supercategories'] 
                codes = json.loads(json_match.group())['final_codes']
            else:
                supercats = []
                codes = []

            results.append({
            "id": row['ID'],
            "supercategories": supercats,
            "claim_labels": codes
            })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_8.csv", index=False)

In [24]:
df_llm_8 = pd.read_csv('llm_labels_8.csv')
df_llm_8['claim_labels'] = df_llm_8['claim_labels'].apply(ast.literal_eval)

In [10]:
# fix logical errors programmatically
def fix_hierarchy(codes):
    final_codes = set(codes)
    for code in codes:
        if code % 100 != 0:
            supercategory = (code // 100) * 100
            final_codes.add(supercategory)
    return sorted(list(final_codes))

def check_inconsistency(codes):
    for code in codes:
        if code % 100 != 0:
            if (code // 100) * 100 not in codes:
                return True
    return False

In [26]:
df_llm_8['claim_labels'] = df_llm_8['claim_labels'].apply(fix_hierarchy)
inconsistent_count = df_llm_8['claim_labels'].apply(check_inconsistency).sum()
print(f"Remaining inconsistent rows: {inconsistent_count}")

Remaining inconsistent rows: 0

In [27]:
df_llm_8.to_csv("llm_labels_8.csv", index=False)

In [31]:
%%notify
# increasing tokens, moving final_codes to the top, explicitly allowing empty lists
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = [
            create_labelling_prompt(row['Text'], examples_string, codebook_string)
            for _, row in batch.iterrows()
        ]
                
        outputs = llm_model(
            prompts,
            max_new_tokens=500,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        for output, (_, row) in zip(outputs, batch.iterrows()):            
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
            if json_match:
                supercats = json.loads(json_match.group())['identified_supercategories'] 
                codes = json.loads(json_match.group())['final_codes']
            else:
                supercats = []
                codes = []

            results.append({
            "id": row['ID'],
            "supercategories": supercats,
            "claim_labels": codes
            })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_9.csv", index=False)

In [33]:
df_llm_9 = pd.read_csv('llm_labels_9.csv')
df_llm_9['claim_labels'] = df_llm_9['claim_labels'].apply(ast.literal_eval)
df_llm_9['claim_labels'] = df_llm_9['claim_labels'].apply(fix_hierarchy)
inconsistent_count = df_llm_9['claim_labels'].apply(check_inconsistency).sum()
print(f"Remaining inconsistent rows: {inconsistent_count}")

Remaining inconsistent rows: 0

In [34]:
df_llm_9.to_csv("llm_labels_9.csv", index=False)

In [37]:
%%notify
# fixing over-constraint and re-establishing reasoning
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = [
            create_labelling_prompt(row['Text'], examples_string, codebook_string)
            for _, row in batch.iterrows()
        ]
                
        outputs = llm_model(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        for output, (_, row) in zip(outputs, batch.iterrows()):            
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*\}', generated_text, re.DOTALL)
            if json_match:
                supercats = json.loads(json_match.group())['identified_supercategories'] 
                codes = json.loads(json_match.group())['final_codes']
            else:
                supercats = []
                codes = []

            results.append({
            "id": row['ID'],
            "supercategories": supercats,
            "claim_labels": codes
            })
        
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_10.csv", index=False)

In [38]:
df_llm_10 = pd.read_csv('llm_labels_10.csv')
df_llm_10['claim_labels'] = df_llm_10['claim_labels'].apply(ast.literal_eval)
df_llm_10['claim_labels'] = df_llm_10['claim_labels'].apply(fix_hierarchy)
inconsistent_count = df_llm_10['claim_labels'].apply(check_inconsistency).sum()
print(f"Remaining inconsistent rows: {inconsistent_count}")
df_llm_10

Remaining inconsistent rows: 0

       id       supercategories                                   claim_labels
0       0                [1200]                                   [1200, 1207]
1       1            [100, 600]                      [100, 105, 600, 601, 604]
2       2                    []                                             []
3       3            [100, 500]                           [100, 107, 500, 502]
4       4                [2000]                                         [2000]
..    ...                   ...                                            ...
364  1426            [500, 600]                           [500, 506, 600, 604]
365  1756            [200, 600]                      [200, 201, 207, 600, 603]
366  2601  [100, 400, 500, 200]  [100, 105, 200, 201, 230, 400, 408, 500, 507]
367  3070           [1500, 400]                         [400, 401, 1500, 1501]
368  3356           [200, 1000]                         [200, 201, 1000, 1001]

[369 rows x 3 columns]

In [39]:
df_llm_10.to_csv("llm_labels_10.csv", index=False)

In [49]:
# adding clarifications for problematic codes
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your task is to annotate debate excerpts using a specific hierarchical coding schema.
RULES:
1. Provide all relevant subcategories. Then, include the parent '00' code for each subcategory used.
2. Subcategories (e.g., 107, 105) MUST be accompanied by their Supercategory (e.g., 100) 
3. If a text discusses multiple topics (e.g., both Tax and Health), provide all relevant codes.
4. Only use codes provided in the codebook below.
5. If no topics in the codebook apply, the lists must be empty []. Do not guess.
6. Ignore general rhetorical statements about 'fairness' or 'growth' unless a specific policy proposal is mentioned.
7. Use ONLY single quotes inside the reasoning string. NEVER use double quotes ("") inside the reasoning string. 

OUTPUT FORMAT:
Return ONLY a JSON object with this structure:
{{
  "reasoning": "A brief explanation of why these topics apply.",
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}
        
CODEBOOK:
{codebook_string}

CODING CLARIFICATIONS (CRITICAL):
- 105: Use 105 ONLY if the text explicitly refers to public spending or economic growth
- 201: Use 201 ONLY if the text explicitly refers to racial discrimination
- 200: Do NOT use 200 codes except if the text explicitly refers to civil rights
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation

EXAMPLES:
{examples_string}
<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
JSON Response:<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

In [2]:
embedder = SentenceTransformer('all-MiniLM-L6-v2')

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 748951fd-c490-4cf6-97a0-dbd6345fd6db)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./config_sentence_transformers.json
Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: d4d3f4d6-e7f8-4746-b33a-9b848ec05391)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./README.md
Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: fea14a19-289b-4297-8a82-35bb88e78f3e)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./modules.json
Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 68a11d6f-9f33-4f7b-b548-e972f70171db)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./modules.json
Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: b7cd1c52-477b-4e2f-af0f-6a3a13e53ca5)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./modules.json
Retrying in 4s [Retry 3/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 69a8cc51-83de-4f33-8cc3-0117b6a0ad5c)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./modules.json
Retrying in 8s [Retry 4/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: dce4f8cc-3290-4dff-bc8b-f24c79202ec2)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./modules.json
Retrying in 8s [Retry 5/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: d96d85da-c41c-4de1-b388-d873a43b4830)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./sentence_bert_config.json
Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: a4793691-ba90-453b-915f-f8453dfdb373)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: ee8112e2-cc58-49a0-8764-2d0dc3b48698)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 7fb7423c-bd1e-4fa4-a81e-9281b3908431)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 4s [Retry 3/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 252c8cad-2334-48e7-a93e-5c157d7e6bff)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 8s [Retry 4/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 8fbe3eba-0a8c-44ce-a466-fc956243b0d3)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 8s [Retry 5/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 88c571a4-bbe3-4cd6-8566-cc8145d457c5)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 785ecabd-0a60-4a17-8340-fa1248a6e4fd)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json
Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 3bcd3279-f954-4fa7-ad87-5765c8addd10)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json
Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: e38be2f6-ae1f-4a7a-8e69-4a2f8ff08a5d)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json
Retrying in 4s [Retry 3/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 9e37c9fc-f6eb-4fad-849c-03f1a2275f2d)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json
Retrying in 8s [Retry 4/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 63d28dd2-3dbe-4f55-a7a3-e0729eb59a7f)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json
Retrying in 8s [Retry 5/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 65222d6e-057f-4b93-9c7b-ab55d5d11d4a)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f9b73a9b-140a-4c58-8b76-69ae85bd6157)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 89473cdb-85e1-4886-bec3-1b539cae1961)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 314c092f-7808-4401-a431-b12c818a59c4)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
Retrying in 4s [Retry 3/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: b3ee09fe-b397-4e05-a829-b40274478636)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
Retrying in 8s [Retry 4/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 287a243c-3ec1-42e6-bfe4-ffecf00190f9)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
Retrying in 8s [Retry 5/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: cc9a1304-ca1d-4a8d-b583-d6ad7d9b609e)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 7de4e2e9-1bc2-4664-b0e9-fd7dbb1470be)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/1_Pooling/config.json

Retrying in 1s [Retry 1/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 5dd169c6-14b6-4617-b07b-22622718c433)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/1_Pooling/config.json
Retrying in 2s [Retry 2/5].
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 6e0f84a6-b600-4ea0-853b-e69ff17eb935)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/1_Pooling/config.json
Retrying in 4s [Retry 3/5].

In [12]:
df_val=pd.read_csv('labelling_validation.csv', index_col=0)
df_val['Claim_Labels'] = df_val['Claim_Labels'].fillna('')
df_val.rename(columns={'Claim_Labels': 'claim_labels'}, inplace=True)

df_val_temp = df_val.copy()
def clean_labels(x):
    if pd.isna(x) or x == "":
        return []
    if isinstance(x, str):
        try:
            splits = x.split(',')
            if 'None' in x:
                return []
            elif '' in splits:                
                splits.remove('')
            elif ' ' in splits:                
                splits.remove(' ')
#             elif x[-1]
            return [int(i.strip()) for i in splits]
        except:
            print(x)
            print(splits)
    return x

df_val_temp['claim_labels'] = df_val_temp['claim_labels'].apply(clean_labels)

df_val_temp.rename(columns={'ID': 'id'}, inplace=True)
df_human = df_val_temp.copy()
df_human

,id,Text,claim_labels
0,0,"So knife crime's going to go up, because the e...","[1200, 1211]"
1,1,Of course Gordon Brown's right to say there's ...,"[100, 107, 1300, 1302, 600, 602, 603, 1200, 1208]"
2,2,"You won't admit the truth, will you? The truth...",[]
3,3,"I tell you how we pay for it. We would, for in...","[100, 107]"
4,4,"You just, look, there's no point in speculatin...",[]
...,...,...,...
364,1426,I think the lady makes a very important point....,"[100, 103, 1200, 1207, 1900, 1910, 500, 506]"
365,1756,I've met some of the people who have rightly c...,"[1200, 1207]"
366,2601,"Well, I share the frustration of both our ques...","[1900, 1910, 400, 406, 200, 202, 230]"
367,3070,You're saying people voted for 10% tariffs on ...,"[1000, 1006]"
368,3356,I think this question of enthusiasm is really ...,"[2000, 2032, 1200, 1208]"

In [13]:
human_texts = df_human['Text'].tolist()
human_labels = df_human['claim_labels'].tolist()
library_embeddings = embedder.encode(human_texts, convert_to_tensor=True)

In [14]:
def get_dynamic_examples(target_text, k=5):
  query_embedding = embedder.encode([target_text], convert_to_tensor=True)
  similarities = cosine_similarity(query_embedding.cpu(), library_embeddings.cpu())[0]
  top_k_idx = np.argsort(similarities)[-k:][::-1]
  
  dynamic_examples = ""
  for idx in top_k_idx:
    if human_texts[idx] != target_text:
      dynamic_examples += f"\nExcerpt: \"{human_texts[idx]}\"\n"
      dynamic_examples += f"JSON Response: {{\"final codes\": {human_labels[idx]}}}\n"

  return dynamic_examples

In [19]:
print(get_dynamic_examples("Which it has for millions of years."))

Excerpt: "But that's why I said it, because I think it was overloaded, it wasn't fully funded, and I think that, particularly now, in 2024, the base camp, the foundation, is economic stability."
JSON Response: {"final codes": [100, 101]}

Excerpt: "Because of the record of this Prime Minister. So we've had..."
JSON Response: {"final codes": []}

Excerpt: "The figure that you're left with at the moment is £23,000, so we're actually quadrupling that."
JSON Response: {"final codes": []}

Excerpt: "I, no point in speculating on that. What I do know is that"
JSON Response: {"final codes": []}

In [50]:
# for the JSONDecodeError :
# 1. Instruct model only to use single quotes
# 2. Use ? in json decode to stop at the first '}'
# 3. use try-except to get as many codes as can be scraped
# 4. added intermittent saving

In [53]:
%%notify
# implementing better examples and clarification for problematic codes
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
          current_examples = get_dynamic_examples(row['Text'], k=6)
          p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
          prompts.append(p)        
                
        outputs = llm_model(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            
            reasoning, supercats, codes = "", [], []
            
            if json_match:
                json_str = json_match.group()
                try:
                    reasoning = json.loads(json_match.group())['reasoning'] 
                    supercats = json.loads(json_match.group())['identified_supercategories'] 
                    codes = json.loads(json_match.group())['final_codes']
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })
        
            # save progress every 20 rows
            if index % 20 == 0:
                pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_12.csv", index=False)

In [54]:
df_llm_12 = pd.read_csv('llm_labels_12.csv')
df_llm_12['claim_labels'] = df_llm_12['claim_labels'].apply(ast.literal_eval)
df_llm_12['claim_labels'] = df_llm_12['claim_labels'].apply(fix_hierarchy)
inconsistent_count = df_llm_12['claim_labels'].apply(check_inconsistency).sum()
print(f"Remaining inconsistent rows: {inconsistent_count}")
df_llm_12

Remaining inconsistent rows: 0

,id,reasoning,supercategories,claim_labels
0,0,The speaker is discussing the relationship bet...,[1200],"[1200, 1206, 1211]"
1,1,The excerpt discusses the link between poverty...,"[100, 200]","[100, 105, 200, 201]"
2,2,The excerpt does not explicitly mention any sp...,[],[]
3,3,"The excerpt discusses tax policy, specifically...","[100, 200]","[100, 105, 200, 201]"
4,4,The excerpt does not mention any specific poli...,[],[]
...,...,...,...,...
364,1426,The excerpt discusses the importance of provid...,"[500, 600]","[500, 506, 600, 601]"
365,1756,The excerpt discusses the Catholic Church's ha...,"[200, 600]","[200, 600, 607, 1200, 1207]"
366,2601,"The excerpt discusses Brexit, animal welfare, ...","[1900, 400, 500, 700]","[400, 401, 500, 508, 700, 701, 1900]"
367,3070,"The text mentions tariffs, which is related to...","[100, 1800]","[100, 107, 1800, 1803]"
368,3356,The excerpt discusses the importance of restor...,"[100, 200]","[100, 105, 200, 201]"

In [55]:
df_llm_12.to_csv("llm_labels_12.csv", index=False)

In [12]:
# adding stingy rule, further clarifying problematic codes, moving reasoning outside JSON
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts.
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. MULTI-TOPIC: If the text discusses multiple distinct policies (e.g., Health and Tax), provide all relevant codes.
3. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
4. VALIDITY: Only use codes from the provided codebook.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general talk about the economy. Use 105 ONLY if explicit talk on reducing or increasing public spending
- 201: Do NOT use 201 for general talk about fairness. Use 201 ONLY for explicit reference to racism
- 200: Do NOT use 200 codes except if the text explicitly refers to civil rights
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation
- 1300: Ensure you use 1300 codes whenever there is a reference to social welfare
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation.
Then, provide a JSON object with this structure:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

FINAL REMINDER:
You must conclude your response with a JSON block containing the keys: "identified_supercategories", "identified_subcategories", and "final_codes".

<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
<|eot_id|><|start_header_id|>assistant<|end_header_id|>
Reasoning: """

In [64]:
%%notify
# fixing the over-tagging problem, reducing examples to 4 (k=5)
# for the KeyError, I tidied the tags in the prompt and fixed the intructions
# I also set the code to work even if the keys are not available
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
          current_examples = get_dynamic_examples(row['Text'], k=5)
          p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
          prompts.append(p)        
                
        outputs = llm_model(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            
            reasoning, supercats, codes = "", [], []
            
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            if json_match:
                json_str = json_match.group()
                data = json.loads(json_str)
                try:                     
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })
        
            # save progress every 20 rows
            if index % 20 == 0:
                pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_13.csv", index=False)

In [65]:
df_llm_13 = pd.read_csv('llm_labels_13.csv')
df_llm_13['claim_labels'] = df_llm_13['claim_labels'].apply(ast.literal_eval)
df_llm_13['claim_labels'] = df_llm_13['claim_labels'].apply(fix_hierarchy)
inconsistent_count = df_llm_13['claim_labels'].apply(check_inconsistency).sum()
print(f"Remaining inconsistent rows: {inconsistent_count}")
df_llm_13

Remaining inconsistent rows: 0

,id,reasoning,supercategories,claim_labels
0,0,<|end_header_id|>\n The excerpt discusses the...,[1200],"[1200, 1206, 1211]"
1,1,<|end_header_id|>\n The excerpt discusses the...,"[100, 200]","[100, 107, 200, 201]"
2,2,<|end_header_id|>\n The excerpt appears to be...,[],[]
3,3,<|end_header_id|>\n The excerpt discusses tax...,[100],"[100, 105, 107]"
4,4,<|end_header_id|>\n The excerpt does not cont...,[],[]
...,...,...,...,...
364,1426,<|end_header_id|>\n The excerpt discusses the...,"[100, 1300]","[100, 103, 1300, 1302]"
365,1756,<|end_header_id|>\n The excerpt discusses the...,[200],"[200, 201]"
366,2601,<|end_header_id|>\n The excerpt discusses the...,"[100, 400, 500, 1900]","[100, 107, 400, 406, 500, 508, 1900, 1901]"
367,3070,<|end_header_id|>\n The excerpt mentions tari...,[],[]
368,3356,<|end_header_id|>\n The excerpt discusses the...,[200],"[200, 201]"

In [66]:
df_llm_13.to_csv("llm_labels_13.csv", index=False)

In [18]:
# changes to clarifications, removal of Final Reminder, streamlining rules 
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts using the provided codebook
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
3. If specific policies are named (e.g. 'NHS', 'pensions'), you MUST code them, even if phrased as a question.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general 'unfunded' rhetoric. Use 105 ONLY when the actual national budget size, debt levels, or a fiscal rule is the primary topic.
- 200/201: Do NOT use 200/201 for general talk about fairness. Use ONLY for explicit civil rights/racism.
- 2000: Government Operations (2000) subcodes for mentions of political integrity, 'Partygate', trust in government, or 'returning politics to service', NOT 200 
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation
- 1910: MUST be used for any mention of Brexit, 'leaving the EU', or 'negotiating with Brussels'.
- 1300: MUST be used for social welfare/pensions.
- 300: When a policy involves health services provided in another setting (e.g., mental health in schools), prioritize the Health codes (300/301) as the primary topic.
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation.
Then, provide a JSON object:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
<|eot_id|><|start_header_id|>assistant<|end_header_id|>
Reasoning: """

In [19]:
%%notify
# fixing the over-tagging problem, reducing examples to 4 (k=5)
# for the KeyError, I tidied the tags in the prompt and fixed the intructions
# I also set the code to work even if the keys are not available
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
          current_examples = get_dynamic_examples(row['Text'], k=5)
          p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
          prompts.append(p)        
                
        outputs = llm_model(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            
            reasoning, supercats, codes = "", [], []
            
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            if json_match:
                json_str = json_match.group()
                data = json.loads(json_str)
                try:                     
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })
        
            # save progress every 20 rows
            if index % 20 == 0:
                pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_14.csv", index=False)

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [22]:
df_llm_14 = pd.read_csv('llm_labels_14.csv')
df_llm_14['claim_labels'] = df_llm_14['claim_labels'].apply(ast.literal_eval)
df_llm_14['claim_labels'] = df_llm_14['claim_labels'].apply(fix_hierarchy)
inconsistent_count = df_llm_14['claim_labels'].apply(check_inconsistency).sum()
print(f"Remaining inconsistent rows: {inconsistent_count}")
df_llm_14

Remaining inconsistent rows: 0

,id,reasoning,supercategories,claim_labels
0,0,<|end_header_id|>\n The excerpt discusses the...,[1200],"[1200, 1206, 1211]"
1,1,<|end_header_id|>\n The excerpt discusses the...,"[100, 1300]","[100, 107, 1300, 1302]"
2,2,<|end_header_id|>\n The excerpt appears to be...,[],[]
3,3,<|end_header_id|>\n The excerpt discusses tax...,[100],"[100, 107]"
4,4,<|end_header_id|>\n The excerpt is a rhetoric...,[],[]
...,...,...,...,...
364,1426,<|end_header_id|>\n The excerpt discusses the...,"[100, 1300]","[100, 103, 1300, 1302]"
365,1756,<|end_header_id|>\n The excerpt discusses the...,"[100, 200]","[100, 105, 200]"
366,2601,<|end_header_id|>\n The excerpt discusses the...,"[100, 1900]","[100, 108, 1900, 1910]"
367,3070,<|end_header_id|>\n The excerpt mentions a sp...,[100],"[100, 107]"
368,3356,<|end_header_id|>\n The excerpt discusses the...,"[100, 2000]","[100, 105, 2000]"

In [23]:
df_llm_14.to_csv("llm_labels_14.csv", index=False)

In [25]:
# fixing overtagging of 2000
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts using the provided codebook
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
3. If specific policies are named (e.g. 'NHS', 'pensions'), you MUST code them, even if phrased as a question.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general 'unfunded' rhetoric. Use 105 ONLY when the actual national budget size, debt levels, or a fiscal rule is the primary topic.
- 200/201: Do NOT use 200/201 for general talk about fairness, integrity or trust. Use ONLY for explicit civil rights/racism.
- 2000: Do NOT use 2000 for general accusations of lying or 'untrustworthiness'. Use Government Operations (2000) subcodes ONLY if the text discusses institutional reform, election rules, or formal ministerial resignations. 
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation
- 1910: MUST be used for any mention of Brexit, 'leaving the EU', or 'negotiating with Brussels'.
- 1300: MUST be used for social welfare/pensions.
- 300: When a policy involves health services provided in another setting (e.g., mental health in schools), prioritize the Health codes (300/301) as the primary topic.
- If the text mentions 'taxes', 'VAT', or 'income tax', you MUST prioritize 107. If the text mentions 'the deficit', 'national debt', or 'the budget', you MUST prioritize 105.

CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation.
Then, provide a JSON object:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
<|eot_id|><|start_header_id|>assistant<|end_header_id|>
Reasoning: """

In [26]:
%%notify
# fixing the over-tagging problem, reducing examples to 4 (k=5)
# for the KeyError, I tidied the tags in the prompt and fixed the intructions
# I also set the code to work even if the keys are not available
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
          current_examples = get_dynamic_examples(row['Text'], k=5)
          p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
          prompts.append(p)        
                
        outputs = llm_model(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            
            reasoning, supercats, codes = "", [], []
            
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            if json_match:
                json_str = json_match.group()
                data = json.loads(json_str)
                try:                     
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })
        
            # save progress every 20 rows
            if index % 20 == 0:
                pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_15.csv", index=False)

In [15]:
def post_inference(i):
    global df
    df = pd.read_csv(f'llm_labels_{i}.csv')
    df['claim_labels'] = df['claim_labels'].apply(ast.literal_eval)
    df['claim_labels'] = df['claim_labels'].apply(fix_hierarchy)
    inconsistent_count = df['claim_labels'].apply(check_inconsistency).sum()
    print(f"Remaining inconsistent rows: {inconsistent_count}")
    return df
def send_df(i):
    df.to_csv(f"llm_labels_{i}.csv", index=False)

In [30]:
post_inference(15)

Remaining inconsistent rows: 0

,id,reasoning,supercategories,claim_labels
0,0,<|end_header_id|>\n The excerpt discusses the...,[1200],"[1200, 1206, 1211]"
1,1,<|end_header_id|>\n The excerpt discusses the...,"[100, 1300]","[100, 107, 1300, 1302]"
2,2,<|end_header_id|>\n The excerpt appears to be...,[],[]
3,3,<|end_header_id|>\n The excerpt discusses tax...,[100],"[100, 107]"
4,4,<|end_header_id|>\n The excerpt is a rhetoric...,[],[]
...,...,...,...,...
364,1426,<|end_header_id|>\n The excerpt discusses the...,"[100, 1300]","[100, 103, 1300, 1302]"
365,1756,<|end_header_id|>\n The excerpt discusses the...,"[100, 200]","[100, 105, 200, 201]"
366,2601,<|end_header_id|>\n The excerpt discusses the...,"[100, 1900]","[100, 108, 1900, 1901]"
367,3070,<|end_header_id|>\n The excerpt mentions a sp...,[100],"[100, 107]"
368,3356,<|end_header_id|>\n The excerpt discusses the...,"[100, 200]","[100, 105, 200, 2000]"

In [31]:
send_df(15)

In [49]:
# beating run 13
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts.
RULES:
1. HIERARCHY: If you identify a specific subcategory (e.g., 107), you MUST also include its parent supercategory (e.g., 100). If only a general topic is identifiable, provide the parent code and leave the subcategory list empty for that specific topic.
2. MULTI-TOPIC: If the text discusses multiple distinct policies (e.g., Health and Tax), provide all relevant codes.
3. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
4. KEYWORD MANDATE: If specific policy subjects are named (e.g., 'NHS', 'VAT', 'pensions', 'Brexit'), you MUST code them, even if the sentence is an attack or a question. These are NOT rhetorical filler.
5. VALIDITY: Only use codes from the provided codebook.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general talk about the economy. Use 105 ONLY if explicit talk on reducing or increasing public spending
- 107: Use 107 ONLY for specific taxes like VAT, Income Tax, or National Insurance.
- 201: Do NOT use 201 for general talk about fairness. Use 201 ONLY for explicit reference to racism
- 1910: MUST be used for any mention of Brexit or EU negotiations.
- 1300: Ensure you use 1300 codes whenever there is a reference to social welfare
- 300: Prioritize Health codes (300/301) for health services even if they occur in other settings (e.g., mental health in schools).
- 2000: Use subcodes of 2000 ONLY for formal institutional matters (e.g., Partygate, ministerial codes, election rules). Do NOT use 2000 for general "trust" or "lying" rhetoric.
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation.
Then, provide a JSON object with this structure:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

FINAL REMINDER:
You must conclude with the JSON block. If no policy is present, final_codes MUST be [].

<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
<|eot_id|><|start_header_id|>assistant<|end_header_id|>
Reasoning: """

In [50]:
%%notify
# beating 13
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):        
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
          current_examples = get_dynamic_examples(row['Text'], k=5)
          p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
          prompts.append(p)        
                
        outputs = llm_model(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            
            reasoning, supercats, codes = "", [], []
            
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            if json_match:
                json_str = json_match.group() 
                json_str = json_str.replace("None", "null").replace("'", '"')
                try:     
                    data = json.loads(json_str)
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    codes = list(set(codes))
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })
        
            # save progress every 20 rows
            if index % 20 == 0:
                pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_16.csv", index=False)

In [40]:
json_strjson_str = json_str.replace("None", "null").replace("'", '"')
json.loads(json_strjson_str)

{'identified_supercategories': [100, 1900],
 'identified_subcategories': [None, 1910],
 'final_codes': [100, 1910]}

In [45]:
codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
cx= list(set(codes))
cx

[1900, 100, 1910]

In [48]:
cz = json.loads(json_strjson_str).get('final_codes', [])
cz

[100, 1910]

In [51]:
post_inference(16)

Remaining inconsistent rows: 0

,id,reasoning,supercategories,claim_labels
0,0,<|end_header_id|>\n The excerpt discusses the...,[1200],"[1200, 1206, 1211]"
1,1,<|end_header_id|>\n The excerpt discusses the...,"[100, 1300]","[100, 105, 1300, 1302]"
2,2,<|end_header_id|>\n The excerpt appears to be...,[],[]
3,3,<|end_header_id|>\n The excerpt discusses tax...,[100],"[100, 105, 107]"
4,4,<|end_header_id|>\n The excerpt is a statemen...,[],[]
...,...,...,...,...
364,1426,<|end_header_id|>\n The excerpt discusses the...,"[100, 1300, 500]","[100, 103, 500, 506, 1300, 1302]"
365,1756,<|end_header_id|>\n The excerpt discusses the...,"[100, 200, 1300]","[100, 105, 200, 201, 1300, 1303]"
366,2601,<|end_header_id|>\n The excerpt discusses the...,"[100, 400, 1300, 1900]","[100, 105, 400, 401, 1300, 1303, 1900, 1910]"
367,3070,<|end_header_id|>\n The excerpt mentions a sp...,[100],"[100, 107]"
368,3356,<|end_header_id|>\n The excerpt discusses the...,"[100, 200, 2000]","[100, 107, 200, 201, 2000, 2012]"

In [52]:
send_df(16)

In [20]:
def get_dynamic_examples_2(target_text, k=5, max_labels=4, include_empty_prob=0.3):
    query_embedding = embedder.encode([target_text], convert_to_tensor=True)
    similarities = cosine_similarity(query_embedding.cpu(), library_embeddings.cpu())[0]
    top_k_idx = np.argsort(similarities)[-k:][::-1]

    dynamic_examples = ""
    for idx in top_k_idx:
        if human_texts[idx] == target_text:
            continue
        
        labels = human_labels[idx]
        if len(labels) > max_labels:
            continue
        subcats = [c for c in labels if str(c)[-2:]!='00']
        
        if len(subcats) == 0:
            if np.random.rand() > include_empty_prob:
                continue
            supercats = []
            final_codes = []
        else:
            supercats = sorted([c for c in labels if str(c)[-2:]=='00'])
            final_codes = sorted(supercats+subcats)

        dynamic_examples += f"\nExcerpt: \"{human_texts[idx]}\"\n"
        dynamic_examples += (
            "JSON Response:\n"
            "{\n"
            f'  "identified_supercategories": {supercats},\n'
            f'  "identified_subcategories": {subcats},\n'
            f'  "final_codes": {final_codes}\n'
            "}\n"
        )
#         dynamic_examples += f"JSON Response: {{\"sub codes\": {subcats}}}\n"
    
    dynamic_examples += """\nExcerpt: "This government has failed the people time and again."
JSON Response:
{
  "identified_supercategories": [],
  "identified_subcategories": [],
  "final_codes": []
}\n"""
    
    return dynamic_examples

In [21]:
print(get_dynamic_examples_2("I think the lady makes a very important point. Anyone who clearly can't stay at home, who has to live independently because of abuse or what have you, we have to make special provision for them and we would. But the situation today, where you can, age 18, leave school, sign on, get a flat, rather than work, or earn and learn at the same time. I don't think that's right. Look, other countries in Europe have almost abolished youth unemployment because they've taken this approach in, say, Germany or in Holland. And I think we should do the same thing. Look, we have created two million jobs in the last five years. Youth unemployment has come plummeting down. If we stick to the economic plan that's working, we can continue to get unemployment down and give young people what I want, which is the opportunity of an apprenticeship or a university place and the chance of a great career. Starting a life on benefits, frankly, is no life at all."))

Excerpt: "Well he's absolutely right, that pensions should be linked to earnings and we'll do that in 2012 when we've got the resources to do so. We've also introduced the winter allowance for all pensioner households where someone is over sixty, and that's two hundred and four hundred pounds for people over 80. We're trying to do our best to create a new regime for pensioners where women particularly have a full state pension, which they haven't had in the past. To come to benefits, we're making it a condition for young people, they've got to take a job,we're making it a condition now for people who've been long term unemployed, that they've got to take a job. Yes we've got 2 and a half million more people now in work than there was in 1997, and yes single parents are working now when they used not to work, and yes we've got more young people in training and in education than we've had before. But yes also, we've got to go further, these are the measures of compulsion, a requirement to work and a responsibility to work."
JSON Response:
{
  "identified_supercategories": [500, 1300],
  "identified_subcategories": [1303, 506],
  "final_codes": [500, 506, 1300, 1303]
}

Excerpt: "Let me perhaps draw out one of them. David Cameron keeps repeating we've got nothing to say. We're the only party, actually, in this general election campaign who've got a plan fully costed to get people off benefits and into work. That's been independently recognised. I think it's a general... It's almost a philosophical issue here. Do you think the best way to help people who are vulnerable or poor is to constantly giving them more benefits through greater dependency on the state? Or do you provide incentives to let them help themselves where they can? That is what our very, very radical tax switch, so you keep more money when you start working, would precisely do - it would get people off that benefits dependency into work. I think that's what most people agree is the absolute priority these days."
JSON Response:
{
  "identified_supercategories": [100, 1300],
  "identified_subcategories": [1302, 107],
  "final_codes": [100, 107, 1300, 1302]
}

Excerpt: "Why university fees? I think we should invest in education for the future and I do think that abolishing university tuition fees means that any young person has then got the chance to go to university if they can get in. If you look at the process of applications at the moment, the number of working class students is dropping, the number coming from poorer communities is dropping. I want to see real access for everybody. I think that's the right thing to do. It would not be unusual in many other parts of the world to do this. Listen, as a young person, basically, I had the offer of free education. I didn't take it up. That was my choice, and I'm not complaining about it. I don't think it's up to me and my generation to pull up the ladder on the generations that are coming behind. I want to see an education system that really does work for all, so that every child can develop to their full potential, irrespective of their background and the life chances they were given at birth."
JSON Response:
{
  "identified_supercategories": [600],
  "identified_subcategories": [601, 603],
  "final_codes": [600, 601, 603]
}

Excerpt: "This government has failed the people time and again."
JSON Response:
{
  "identified_supercategories": [],
  "identified_subcategories": [],
  "final_codes": []
}

In [76]:
# better examples
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts.
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
3. VALIDITY: Only use codes from the provided codebook.
4. You must only assign a code if there is explicit, unambiguous evidence in the text. If a label requires inference, DO NOT include it.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general talk about the economy. Use 105 ONLY if explicit talk on reducing or increasing public spending
- 201: Do NOT use 201 for general talk about fairness. Use 201 ONLY for explicit reference to racism
- 200: Do NOT use 200 codes except if the text explicitly refers to civil rights
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation
- 1300: Ensure you use 1300 codes whenever there is a reference to social welfare
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation.
Then, provide a JSON object with this structure:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

FINAL REMINDER:
You must conclude your response with a JSON block containing the keys: "identified_supercategories", "identified_subcategories", and "final_codes".

<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
<|eot_id|><|start_header_id|>assistant<|end_header_id|>
Reasoning: """

In [77]:
%%notify
# fixing the over-tagging problem, reducing examples to 4 (k=5)
# for the KeyError, I tidied the tags in the prompt and fixed the intructions
# I also set the code to work even if the keys are not available
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
          current_examples = get_dynamic_examples_2(row['Text'], k=5)
          p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
          prompts.append(p)        
                
        outputs = llm_model(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            
            reasoning, supercats, codes = "", [], []
            
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            if json_match:
                json_str = json_match.group()
                data = json.loads(json_str)
                try:                     
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })
        
            # save progress every 20 rows
            if index % 20 == 0:
                pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_18.csv", index=False)

In [78]:
post_inference(18)

Remaining inconsistent rows: 0

,id,reasoning,supercategories,claim_labels
0,0,<|end_header_id|>\n The excerpt discusses the...,[1200],"[1200, 1206, 1211]"
1,1,<|end_header_id|>\n The excerpt discusses the...,"[100, 200]","[100, 107, 200, 201]"
2,2,<|end_header_id|>\n The excerpt appears to be...,[],[]
3,3,<|end_header_id|>\n The excerpt discusses tax...,[100],"[100, 105, 107]"
4,4,<|end_header_id|>\n The excerpt does not cont...,[],[]
...,...,...,...,...
364,1426,<|end_header_id|>\n The excerpt discusses the...,"[500, 1300]","[500, 506, 1300, 1302]"
365,1756,<|end_header_id|>\n The excerpt discusses the...,[200],"[200, 201]"
366,2601,<|end_header_id|>\n The excerpt discusses the...,"[1900, 400]","[400, 408, 1900, 1910]"
367,3070,<|end_header_id|>\n The excerpt mentions tari...,[100],[100]
368,3356,<|end_header_id|>\n The excerpt discusses the...,"[100, 200]","[100, 105, 200, 201]"

In [79]:
send_df(18)

In [ ]:
# better examples
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts.
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. Do NOT independently infer supercategories. First identify subcategories. Then automatically include their parent supercategories.
2. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
3. VALIDITY: Only use codes from the provided codebook.
4. You must only assign a code if there is explicit, unambiguous evidence in the text. If a label requires inference, DO NOT include it.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general talk about the economy. Use 105 ONLY if explicit talk on reducing or increasing public spending
- 107: Use ONLY if a specific taxation mechanism (tex, levy, duty) is explicitly mentioned
- If both 105 and 107 are implied, choose ONLY the primary mechanism discussed
- 201: Do NOT use 201 if the text contains no reference to racism. Use 201 ONLY for explicit reference to racism
- 200: Do NOT use 200 codes except if the text explicitly refers to civil rights
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation
- 1300: Ensure you use 1300 codes whenever there is a reference to social welfare
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
Do NOT include reasoning. Output ONLY the JSON.
Provide a JSON object with this structure:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

FINAL REMINDER:
You must conclude your response with a JSON block containing the keys: "identified_supercategories", "identified_subcategories", and "final_codes".

<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
<|eot_id|><|start_header_id|>assistant<|end_header_id|>
Reasoning: """

In [81]:
%%notify
# fixing the over-tagging problem, reducing examples to 4 (k=5)
# for the KeyError, I tidied the tags in the prompt and fixed the intructions
# I also set the code to work even if the keys are not available
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
            current_examples = get_dynamic_examples_2(row['Text'], k=5)
            p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
            prompts.append(p)        

        outputs = llm_model(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            
            supercats, codes = [], []
                       
            if json_match:
                json_str = json_match.group()
                data = json.loads(json_str)
                try:                     
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "supercategories": supercats,
            "claim_labels": codes
            })
        
            # save progress every 20 rows
            if index % 20 == 0:
                pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_19.csv", index=False)

In [82]:
post_inference(19)

Remaining inconsistent rows: 0

       id supercategories            claim_labels
0       0          [1200]      [1200, 1206, 1211]
1       1      [100, 200]    [100, 107, 200, 201]
2       2              []                      []
3       3           [100]         [100, 105, 107]
4       4              []                      []
..    ...             ...                     ...
364  1426     [500, 1300]  [500, 506, 1300, 1302]
365  1756           [200]              [200, 201]
366  2601     [1900, 400]  [400, 408, 1900, 1910]
367  3070              []                      []
368  3356      [100, 200]    [100, 105, 200, 201]

[369 rows x 3 columns]

In [83]:
send_df(19)

In [84]:
# better examples
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts.
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. Do NOT independently infer supercategories. First identify subcategories. Then automatically include their parent supercategories.
2. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
3. VALIDITY: Only use codes from the provided codebook.
4. You must only assign a code if there is explicit, unambiguous evidence in the text. If a label requires inference, DO NOT include it.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general talk about the economy. Use 105 ONLY if explicit talk on reducing or increasing public spending
- 107: Use ONLY if a specific taxation mechanism (tex, levy, duty) is explicitly mentioned
- If both 105 and 107 are implied, choose ONLY the primary mechanism discussed
- 201: Do NOT use 201 if the text contains no reference to racism. Use 201 ONLY for explicit reference to racism
- 200: Do NOT use 200 codes except if the text explicitly refers to civil rights
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation
- 1300: Ensure you use 1300 codes whenever there is a reference to social welfare
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation.
Provide a JSON object with this structure:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

FINAL REMINDER:
You must conclude your response with a JSON block containing the keys: "identified_supercategories", "identified_subcategories", and "final_codes".

<|eot_id|><|start_header_id|>user<|end_header_id|>
Annotate the following excerpt:"{excerpt}"
<|eot_id|><|start_header_id|>assistant<|end_header_id|>
Reasoning: """

In [85]:
%%notify
# fixing the over-tagging problem, reducing examples to 4 (k=5)
# for the KeyError, I tidied the tags in the prompt and fixed the intructions
# I also set the code to work even if the keys are not available
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
            current_examples = get_dynamic_examples_2(row['Text'], k=5)
            p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
            prompts.append(p)        
                
        outputs = llm_model(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model.tokenizer.eos_token_id
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].split("assistant")[-1].strip()

            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            
            reasoning, supercats, codes = "", [], []
            
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            if json_match:
                json_str = json_match.group()
                data = json.loads(json_str)
                try:                     
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })
        
            # save progress every 20 rows
            if index % 20 == 0:
                pd.DataFrame(results).to_csv("llm_labels_checkpoint.csv", index=False)
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_20.csv", index=False)

In [86]:
post_inference(20)

Remaining inconsistent rows: 0

,id,reasoning,supercategories,claim_labels
0,0,<|end_header_id|>\n The excerpt discusses the...,[1200],"[1200, 1206, 1211]"
1,1,<|end_header_id|>\n The excerpt discusses the...,"[100, 600]","[100, 107, 600, 602]"
2,2,<|end_header_id|>\n The excerpt appears to be...,[],[]
3,3,<|end_header_id|>\n The excerpt discusses tax...,[100],"[100, 105, 107]"
4,4,<|end_header_id|>\n The excerpt does not cont...,[],[]
...,...,...,...,...
364,1426,<|end_header_id|>\n The excerpt discusses the...,"[500, 1300]","[500, 506, 1300, 1303]"
365,1756,<|end_header_id|>\n The excerpt discusses the...,[200],"[200, 201]"
366,2601,<|end_header_id|>\n The excerpt discusses the...,"[1900, 400]","[400, 406, 1900, 1910]"
367,3070,<|end_header_id|>\n The excerpt mentions tari...,[100],"[100, 107]"
368,3356,<|end_header_id|>\n The excerpt discusses the...,"[100, 200]","[100, 103, 200, 201]"

In [87]:
send_df(20)

In [22]:
# better examples
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<start_of_turn>user
You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts.
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. Do NOT independently infer supercategories. First identify subcategories. Then automatically include their parent supercategories.
2. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
3. VALIDITY: Only use codes from the provided codebook.
4. You must only assign a code if there is explicit, unambiguous evidence in the text. If a label requires inference, DO NOT include it.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general talk about the economy. Use 105 ONLY if explicit talk on reducing or increasing public spending
- 107: Use ONLY if a specific taxation mechanism (tex, levy, duty) is explicitly mentioned
- If both 105 and 107 are implied, choose ONLY the primary mechanism discussed
- 201: Do NOT use 201 if the text contains no reference to racism. Use 201 ONLY for explicit reference to racism
- 200: Do NOT use 200 codes except if the text explicitly refers to civil rights
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation
- 1300: Ensure you use 1300 codes whenever there is a reference to social welfare
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation.
Provide a JSON object with this structure:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

FINAL REMINDER:
You must conclude your response with a JSON block containing the keys: "identified_supercategories", "identified_subcategories", and "final_codes".

Annotate the following excerpt:"{excerpt}"<end_of_turn>
<start_of_turn>model
Reasoning: """

In [26]:
%%notify
# gemma model
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
            current_examples = get_dynamic_examples_2(row['Text'], k=5)
            p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
            prompts.append(p)        
                
        outputs = llm_model_gemma(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model_gemma.tokenizer.eos_token_id,
            return_full_text=False
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].strip()
            
            reasoning = ""
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            supercats, codes = [], []
            
            if json_match:
                json_str = json_match.group()                
                try:     
                    data = json.loads(json_str)
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            
            else:
                print(f"ID {row['ID']}: No JSON found in output.")
                
            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })        
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_21.csv", index=False)

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [27]:
post_inference(21)

Remaining inconsistent rows: 0

,id,reasoning,supercategories,claim_labels
0,0,The excerpt discusses the relationship between...,[1200],"[1200, 1211]"
1,1,The text discusses the link between poverty an...,"[100, 1300]","[100, 105, 1300, 1302]"
2,2,The excerpt contains no explicit mention of po...,[],[]
3,3,The text discusses closing tax loopholes that ...,[100],"[100, 107]"
4,4,The text does not contain any explicit mention...,[],[]
...,...,...,...,...
364,1426,The text discusses the issue of youth unemploy...,"[100, 1300]","[100, 103, 1300, 1302]"
365,1756,The text discusses the Catholic Church's handl...,"[200, 1900]","[200, 201, 1900, 1926]"
366,2601,"The excerpt discusses Brexit, its potential be...","[1900, 100]","[100, 107, 1400, 1401, 1900, 1910]"
367,3070,"The excerpt discusses tariffs on cars, which i...",[100],"[100, 107]"
368,3356,The excerpt discusses a lack of hope in the co...,[2000],"[2000, 2012]"

In [28]:
send_df(21)

In [19]:
# better examples
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<s>[INST] You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts.
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. Do NOT independently infer supercategories. First identify subcategories. Then automatically include their parent supercategories.
2. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
3. VALIDITY: Only use codes from the provided codebook.
4. You must only assign a code if there is explicit, unambiguous evidence in the text. If a label requires inference, DO NOT include it.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general talk about the economy. Use 105 ONLY if explicit talk on reducing or increasing public spending
- 107: Use ONLY if a specific taxation mechanism (tex, levy, duty) is explicitly mentioned
- If both 105 and 107 are implied, choose ONLY the primary mechanism discussed
- 201: Do NOT use 201 if the text contains no reference to racism. Use 201 ONLY for explicit reference to racism
- 200: Do NOT use 200 codes except if the text explicitly refers to civil rights
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation
- 1300: Ensure you use 1300 codes whenever there is a reference to social welfare
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation. Keep reasoning under 50 words.
Provide a JSON object with this structure:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

FINAL REMINDER:
You must conclude your response with a JSON block containing the keys: "identified_supercategories", "identified_subcategories", and "final_codes".

Annotate the following excerpt:"{excerpt}" [/INST]
Reasoning: """

In [21]:
%%notify
# fixing the over-tagging problem, reducing examples to 4 (k=5)
# for the KeyError, I tidied the tags in the prompt and fixed the intructions
# I also set the code to work even if the keys are not available
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
            current_examples = get_dynamic_examples_2(row['Text'], k=5)
            p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
            prompts.append(p)        
                
        outputs = llm_model_nemo(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model_nemo.tokenizer.eos_token_id,
            return_full_text=False
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].strip()
            
            reasoning = ""
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            supercats, codes = [], []
            
            if json_match:
                json_str = json_match.group()                
                try:      
                    data = json.loads(json_str)
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_22.csv", index=False)

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [22]:
post_inference(22)

Remaining inconsistent rows: 0

,id,reasoning,supercategories,claim_labels
0,0,100 (Macroeconomics) is implied as the discuss...,"[100, 200]","[100, 107, 200, 201]"
1,1,The excerpt discusses the link between poverty...,"[100, 1300, 600]","[100, 107, 600, 602, 1300, 1302]"
2,2,100 (Macroeconomics) is inferred from the ment...,"[100, 200]","[100, 107, 200, 201]"
3,3,100 is chosen because the text discusses taxat...,"[100, 200]","[100, 107, 200, 201]"
4,4,100 (Macroeconomics) is inferred as the superc...,[100],"[100, 107]"
...,...,...,...,...
364,1426,"The excerpt discusses youth unemployment, bene...","[500, 1300, 1900]","[500, 506, 1300, 1302, 1900]"
365,1756,100 (Macroeconomics) is implied as the speaker...,"[100, 200]","[100, 107, 200, 201]"
366,2601,100 (Macroeconomics) is implied by the mention...,"[100, 1300, 1900]","[100, 1300, 1900]"
367,3070,100 (Macroeconomics) is used because the text ...,[100],"[100, 107]"
368,3356,The excerpt discusses the lack of integrity in...,[2000],"[2000, 2012]"

In [23]:
send_df(22)

In [16]:
# better examples
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<s>[INST] You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts.
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. Do NOT independently infer supercategories. First identify subcategories. Then automatically include their parent supercategories.
3. VALIDITY: Only use codes from the provided codebook.
4. You must only assign a code if there is explicit, unambiguous evidence in the text. If a label requires inference, DO NOT include it.
5. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation. Keep reasoning under 50 words.
Provide a JSON object with this structure:
{{
  "identified_supercategories": [LIST_OF_SUPER_CODES],
  "identified_subcategories": [LIST_OF_SUB_CODES],
  "final_codes": [ALL_IDENTIFIED_CODES]  
}}

FINAL REMINDER:
You must conclude your response with a JSON block containing the keys: "identified_supercategories", "identified_subcategories", and "final_codes".

Annotate the following excerpt:"{excerpt}" [/INST]
Reasoning: """

In [22]:
%%notify
# fixing the over-tagging problem, reducing examples to 4 (k=5)
# for the KeyError, I tidied the tags in the prompt and fixed the intructions
# I also set the code to work even if the keys are not available
batch_size = 8
results = []
with torch.no_grad():
    for i in range(0, len(df_val), batch_size):
        print(f"Progress: {i+1}/{len(df_val)}", end='\r')
        batch = df_val.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
            current_examples = get_dynamic_examples_2(row['Text'], k=5)
            p = create_labelling_prompt(row['Text'], current_examples, codebook_string)
            prompts.append(p)        
                
        outputs = llm_model_nemo(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model_nemo.tokenizer.eos_token_id,
            return_full_text=False
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].strip()
            
            reasoning = ""
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            supercats, codes = [], []
            
            if json_match:
                json_str = json_match.group()                
                try:      
                    data = json.loads(json_str)
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            

            results.append({
            "id": row['ID'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })
                
results_df = pd.DataFrame(results)
results_df.to_csv("llm_labels_23.csv", index=False)

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

OSError: [Errno 122] Disk quota exceeded: 'llm_labels_23.csv'

In [32]:
results_df.to_csv("llm_labels_23.csv", index=False)

Performance (Comparison with human)

In [36]:
# llm_labels_21 is the best performing
df_llm = pd.read_csv('llm_labels_21.csv')
df_human = pd.read_csv('labelling_validation.csv')
def parse_llm_list(val):
    if pd.isna(val) or val == "[]" or val == "": return []
    try:
        res = ast.literal_eval(val)
        return [int(x) for x in res] if isinstance(res, list) else []
    except:
        import re
        return [int(x) for x in re.findall(r'\d+', str(val))]

def parse_human_list(val):
    if pd.isna(val) or str(val).strip() == "": return []
    parts = str(val).replace('[', '').replace(']', '').split(',')
    return [int(x.strip()) for x in parts if x.strip().isdigit()]

df_llm['llm_parsed'] = df_llm['claim_labels'].apply(parse_llm_list)
df_human['human_parsed'] = df_human['Claim_Labels'].apply(parse_human_list)

In [39]:
merged = pd.merge(df_llm[['id', 'llm_parsed']], df_human[['ID', 'human_parsed']], left_on='id', right_on='ID')
merged

,id,llm_parsed,ID,human_parsed
0,0,"[1200, 1211]",0,"[1200, 1211]"
1,1,"[100, 105, 1300, 1302]",1,"[100, 107, 1300, 1302, 600, 602, 603, 1200, 1208]"
2,2,[],2,[]
3,3,"[100, 107]",3,"[100, 107]"
4,4,[],4,[]
...,...,...,...,...
364,1426,"[100, 103, 1300, 1302]",1426,"[100, 103, 1200, 1207, 1900, 1910, 500, 506]"
365,1756,"[200, 201, 1900, 1926]",1756,"[1200, 1207]"
366,2601,"[100, 107, 1400, 1401, 1900, 1910]",2601,"[1900, 1910, 400, 406, 200, 202, 230]"
367,3070,"[100, 107]",3070,"[1000, 1006]"
368,3356,"[2000, 2012]",3356,"[2000, 2032, 1200, 1208]"

In [40]:
mlb = MultiLabelBinarizer()
y_true = mlb.fit_transform(merged['human_parsed'])
y_pred = mlb.transform(merged['llm_parsed'])

/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) [1216, 1306, 1309, 1906, 203, 608] will be ignored
  warnings.warn(

In [44]:
report = classification_report(
    y_true, 
    y_pred, 
    target_names=[str(c) for c in mlb.classes_], 
    output_dict=True, 
    zero_division=0
)
report_df = pd.DataFrame(report).transpose().sort_values(by='support', ascending=False)

In [46]:
print(report_df.head(20))

              precision    recall  f1-score  support
samples avg    0.472116  0.508562  0.470239   1019.0
weighted avg   0.589953  0.559372  0.533915   1019.0
macro avg      0.362536  0.322909  0.302198   1019.0
micro avg      0.521978  0.559372  0.540028   1019.0
100            0.568345  0.877778  0.689956     90.0
1900           0.803030  0.791045  0.796992     67.0
107            0.619048  0.847826  0.715596     46.0
1910           0.870968  0.627907  0.729730     43.0
105            0.410959  0.731707  0.526316     41.0
200            0.492308  0.780488  0.603774     41.0
300            0.800000  0.500000  0.615385     40.0
500            0.615385  0.210526  0.313725     38.0
1200           0.807692  0.636364  0.711864     33.0
230            0.777778  0.677419  0.724138     31.0
2000           0.541667  0.433333  0.481481     30.0
1300           0.324675  0.925926  0.480769     27.0
1600           0.888889  0.615385  0.727273     26.0
1400           0.736842  0.636364  0.682927     22.0
301            0.450000  0.473684  0.461538     19.0
700            0.722222  0.722222  0.722222     18.0

In [47]:
report_df.to_csv('llm_per_label_performance.csv')

Decisions for labelling:  
* F1>0.70: Use labels directly when they appear
* f1:0.4-0.7: use embedding filtering
* f1<0.4:human adjudication

---

Presentation of results and explanation
* F1 score of the top 10 supercategories in horizontal bar
* Precision v Recall scatter with size indicating frequency (for maybe top x)
* Analysis of the precision and recall of select labels
* Comparing supercategory and subcategory performance  
* Explain the difficulty of the task

---