In [1]:
%load_ext jupyternotify

/home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages/jupyternotify/jupyternotify.py:11: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename

In [17]:
!pip install python-certifi-win32

Collecting python-certifi-win32
  Downloading python_certifi_win32-1.6.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: wrapt>=1.10.4 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from python-certifi-win32) (2.1.0)
Requirement already satisfied: certifi in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from python-certifi-win32) (2026.1.4)
Collecting setuptools-scm (from python-certifi-win32)
  Downloading setuptools_scm-9.2.2-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: packaging>=20 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from setuptools-scm->python-certifi-win32) (25.0)
Requirement already satisfied: setuptools in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from setuptools-scm->python-certifi-win32) (80.10.2)
Requirement already satisfied: tomli>=1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from setuptools-scm->python-certifi-win32) (2.4.0)
Requirement already satisfied: typing-extensions in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from setuptools-scm->python-certifi-win32) (4.15.0)
Downloading python_certifi_win32-1.6.1-py2.py3-none-any.whl (7.3 kB)
Downloading setuptools_scm-9.2.2-py3-none-any.whl (62 kB)
Installing collected packages: setuptools-scm, python-certifi-win32
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [python-certifi-win32]
Successfully installed python-certifi-win32-1.6.1 setuptools-scm-9.2.2

[notice] A new release of pip is available: 20.0.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [19]:
!pip install transformers --use-feature=truststore

WARNING: The following features are always enabled: truststore.
Requirement already satisfied: transformers in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (4.57.3)
Requirement already satisfied: filelock in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (2026.1.15)
Requirement already satisfied: requests in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->transformers) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home2/pwfb75/joel_jupyterenv-3.9/lib/python3.9/site-packages (from requests->transformers) (2026.1.4)

[notice] A new release of pip is available: 20.0.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [1]:
import os
from transformers import pipeline, BitsAndBytesConfig, AutoTokenizer, AutoModelForCausalLM
import torch
from huggingface_hub import login
import pandas as pd
import json
from tqdm import tqdm
import re
import ast
import gc
from torch.utils.data import Dataset
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import classification_report

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [80]:
def create_debate_dataframe(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
        
    pattern = r'^(\d+)\n(.*?)(?=\n\d+\n|\Z)'

    matches = re.findall(pattern, content, re.DOTALL | re.MULTILINE)

    df = pd.DataFrame(matches, columns=['id', 'text'])
    
    df['text'] = df['text'].str.strip()
    
    df['id'] = df['id'].astype(int)
    
    return df

In [81]:
df_turns = create_debate_dataframe('all_turns_shuffled.txt')
df_turns

        id                                               text
0        0  So knife crime's going to go up, because the e...
1        1  Of course Gordon Brown's right to say there's ...
2        2  You won't admit the truth, will you? The truth...
3        3  I tell you how we pay for it. We would, for in...
4        4  You just, look, there's no point in speculatin...
...    ...                                                ...
3683  3683  Nigel Farage. Well, I mean, the fact that ther...
3684  3684  Yeah, I was incredibly sad to have caused peop...
3685  3685  ...that he wasn't originally in favour, er, he...
3686  3686  There are lots of people who go for private he...
3687  3687  And it wasn't tripled, and we didn't triple tu...

[3688 rows x 2 columns]

In [2]:
# remove the IDs in the validation set
df_val=pd.read_csv('labelling_validation.csv', index_col=0)
df_val['Claim_Labels'] = df_val['Claim_Labels'].fillna('')
df_val.rename(columns={'Claim_Labels': 'claim_labels'}, inplace=True)

df_val_temp = df_val.copy()
def clean_labels(x):
    if pd.isna(x) or x == "":
        return []
    if isinstance(x, str):
        try:
            splits = x.split(',')
            if 'None' in x:
                return []
            elif '' in splits:                
                splits.remove('')
            elif ' ' in splits:                
                splits.remove(' ')
#             elif x[-1]
            return [int(i.strip()) for i in splits]
        except:
            print(x)
            print(splits)
    return x

df_val_temp['claim_labels'] = df_val_temp['claim_labels'].apply(clean_labels)

df_val_temp.rename(columns={'ID': 'id'}, inplace=True)
df_human = df_val_temp.copy()
df_human

,id,Text,claim_labels
0,0,"So knife crime's going to go up, because the e...","[1200, 1211]"
1,1,Of course Gordon Brown's right to say there's ...,"[100, 107, 1300, 1302, 600, 602, 603, 1200, 1208]"
2,2,"You won't admit the truth, will you? The truth...",[]
3,3,"I tell you how we pay for it. We would, for in...","[100, 107]"
4,4,"You just, look, there's no point in speculatin...",[]
...,...,...,...
364,1426,I think the lady makes a very important point....,"[100, 103, 1200, 1207, 1900, 1910, 500, 506]"
365,1756,I've met some of the people who have rightly c...,"[1200, 1207]"
366,2601,"Well, I share the frustration of both our ques...","[1900, 1910, 400, 406, 200, 202, 230]"
367,3070,You're saying people voted for 10% tariffs on ...,"[1000, 1006]"
368,3356,I think this question of enthusiasm is really ...,"[2000, 2032, 1200, 1208]"

In [83]:
val_list = df_val['ID'].tolist()
print(val_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 351, 361, 388, 394, 404, 416, 429, 432, 447, 455, 484, 624, 628, 671, 737, 748, 998, 1222, 1361, 1420, 1426, 1756, 2601, 3070, 3356]

In [84]:
df_turns = df_turns[~df_turns['id'].isin(val_list)]
df_turns

        id                                               text
344    344  Ed Miliband. You've heard tonight from five di...
345    345  Of course, we have to improve the system, but ...
346    346  I've never been called timid in my life, but c...
347    347  Well, Darren, in answer to your question, obvi...
348    348  It isn't a question of what it's worth paying ...
...    ...                                                ...
3683  3683  Nigel Farage. Well, I mean, the fact that ther...
3684  3684  Yeah, I was incredibly sad to have caused peop...
3685  3685  ...that he wasn't originally in favour, er, he...
3686  3686  There are lots of people who go for private he...
3687  3687  And it wasn't tripled, and we didn't triple tu...

[3319 rows x 2 columns]

LLM

In [15]:
login("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")

In [16]:
model_id_gemma = "unsloth/gemma-2-9b-it-bnb-4bit" 

quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)


llm_model_gemma = pipeline(
    "text-generation",
    model=model_id_gemma,
    model_kwargs={
        "low_cpu_mem_usage": True,
        "dtype": torch.bfloat16 
    },
    device_map="auto"
)
terminators = [
    llm_model_gemma.tokenizer.eos_token_id,
    llm_model_gemma.tokenizer.convert_tokens_to_ids("<end_of_turn>")
]

Device set to use cuda:0

In [8]:
!huggingface-cli scan-cache

⚠️  Warning: 'huggingface-cli scan-cache' is deprecated. Use 'hf cache scan' instead.
REPO ID                                     REPO TYPE SIZE ON DISK NB FILES LAST_ACCESSED LAST_MODIFIED REFS             LOCAL PATH
------------------------------------------- --------- ------------ -------- ------------- ------------- ---------------- -----------------------------------------------------------------------------------------
GateNLP/stance-bertweet-target-aware        model           541.6M        7 3 months ago  3 months ago  main             /home2/pwfb75/.cache/huggingface/hub/models--GateNLP--stance-bertweet-target-aware
bert-base-german-cased                      model           439.6M        5 2 months ago  2 months ago  main             /home2/pwfb75/.cache/huggingface/hub/models--bert-base-german-cased
google/gemma-2-9b-it                        model            39.9K        2 1 day ago     1 day ago     main             /home2/pwfb75/.cache/huggingface/hub/models--google--gemma-2-9b-it
openai/clip-vit-base-patch32                model             1.2G        9 3 weeks ago   3 weeks ago   main, refs/pr/66 /home2/pwfb75/.cache/huggingface/hub/models--openai--clip-vit-base-patch32
sentence-transformers/all-MiniLM-L6-v2      model            91.6M       11 3 days ago    3 days ago    main             /home2/pwfb75/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2
unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit model             8.3G        8 1 day ago     1 day ago     main             /home2/pwfb75/.cache/huggingface/hub/models--unsloth--Mistral-Nemo-Instruct-2407-bnb-4bit
unsloth/gemma-2-9b-it-bnb-4bit              model             6.2G        7 1 day ago     1 day ago     main             /home2/pwfb75/.cache/huggingface/hub/models--unsloth--gemma-2-9b-it-bnb-4bit
vinai/bertweet-base                         model             1.1G        6 3 months ago  3 months ago  main, refs/pr/6  /home2/pwfb75/.cache/huggingface/hub/models--vinai--bertweet-base

Done in 0.0s. Scanned 8 repo(s) for a total of 17.9G.
Got 1 warning(s) while scanning. Use -vvv to print details.

In [9]:
embedder = SentenceTransformer(
    'sentence-transformers/all-MiniLM-L6-v2', 
    local_files_only=True
)

In [12]:
human_texts = df_human['Text'].tolist()
human_labels = df_human['claim_labels'].tolist()
library_embeddings = embedder.encode(human_texts, convert_to_tensor=True)

In [13]:
def get_dynamic_examples_2(target_text, k=5, max_labels=4, include_empty_prob=0.3):
    query_embedding = embedder.encode([target_text], convert_to_tensor=True)
    similarities = cosine_similarity(query_embedding.cpu(), library_embeddings.cpu())[0]
    top_k_idx = np.argsort(similarities)[-k:][::-1]

    dynamic_examples = ""
    for idx in top_k_idx:
        if human_texts[idx] == target_text:
            continue
        
        labels = human_labels[idx]
        if len(labels) > max_labels:
            continue
        subcats = [c for c in labels if str(c)[-2:]!='00']
        
        if len(subcats) == 0:
            if np.random.rand() > include_empty_prob:
                continue
            supercats = []
            final_codes = []
        else:
            supercats = sorted([c for c in labels if str(c)[-2:]=='00'])
            final_codes = sorted(supercats+subcats)

        dynamic_examples += f"\nExcerpt: \"{human_texts[idx]}\"\n"
        dynamic_examples += (
            "JSON Response:\n"
            "{\n"
            f'  "identified_supercategories": {supercats},\n'
            f'  "identified_subcategories": {subcats},\n'
            f'  "final_codes": {final_codes}\n'
            "}\n"
        )
#         dynamic_examples += f"JSON Response: {{\"sub codes\": {subcats}}}\n"
    
    dynamic_examples += """\nExcerpt: "This government has failed the people time and again."
JSON Response:
{
  "identified_supercategories": [],
  "identified_subcategories": [],
  "final_codes": []
}\n"""
    
    return dynamic_examples

In [14]:
print(get_dynamic_examples_2("I think the lady makes a very important point. Anyone who clearly can't stay at home, who has to live independently because of abuse or what have you, we have to make special provision for them and we would. But the situation today, where you can, age 18, leave school, sign on, get a flat, rather than work, or earn and learn at the same time. I don't think that's right. Look, other countries in Europe have almost abolished youth unemployment because they've taken this approach in, say, Germany or in Holland. And I think we should do the same thing. Look, we have created two million jobs in the last five years. Youth unemployment has come plummeting down. If we stick to the economic plan that's working, we can continue to get unemployment down and give young people what I want, which is the opportunity of an apprenticeship or a university place and the chance of a great career. Starting a life on benefits, frankly, is no life at all."))

Excerpt: "Well he's absolutely right, that pensions should be linked to earnings and we'll do that in 2012 when we've got the resources to do so. We've also introduced the winter allowance for all pensioner households where someone is over sixty, and that's two hundred and four hundred pounds for people over 80. We're trying to do our best to create a new regime for pensioners where women particularly have a full state pension, which they haven't had in the past. To come to benefits, we're making it a condition for young people, they've got to take a job,we're making it a condition now for people who've been long term unemployed, that they've got to take a job. Yes we've got 2 and a half million more people now in work than there was in 1997, and yes single parents are working now when they used not to work, and yes we've got more young people in training and in education than we've had before. But yes also, we've got to go further, these are the measures of compulsion, a requirement to work and a responsibility to work."
JSON Response:
{
  "identified_supercategories": [500, 1300],
  "identified_subcategories": [1303, 506],
  "final_codes": [500, 506, 1300, 1303]
}

Excerpt: "Let me perhaps draw out one of them. David Cameron keeps repeating we've got nothing to say. We're the only party, actually, in this general election campaign who've got a plan fully costed to get people off benefits and into work. That's been independently recognised. I think it's a general... It's almost a philosophical issue here. Do you think the best way to help people who are vulnerable or poor is to constantly giving them more benefits through greater dependency on the state? Or do you provide incentives to let them help themselves where they can? That is what our very, very radical tax switch, so you keep more money when you start working, would precisely do - it would get people off that benefits dependency into work. I think that's what most people agree is the absolute priority these days."
JSON Response:
{
  "identified_supercategories": [100, 1300],
  "identified_subcategories": [1302, 107],
  "final_codes": [100, 107, 1300, 1302]
}

Excerpt: "Why university fees? I think we should invest in education for the future and I do think that abolishing university tuition fees means that any young person has then got the chance to go to university if they can get in. If you look at the process of applications at the moment, the number of working class students is dropping, the number coming from poorer communities is dropping. I want to see real access for everybody. I think that's the right thing to do. It would not be unusual in many other parts of the world to do this. Listen, as a young person, basically, I had the offer of free education. I didn't take it up. That was my choice, and I'm not complaining about it. I don't think it's up to me and my generation to pull up the ladder on the generations that are coming behind. I want to see an education system that really does work for all, so that every child can develop to their full potential, irrespective of their background and the life chances they were given at birth."
JSON Response:
{
  "identified_supercategories": [600],
  "identified_subcategories": [601, 603],
  "final_codes": [600, 601, 603]
}

Excerpt: "This government has failed the people time and again."
JSON Response:
{
  "identified_supercategories": [],
  "identified_subcategories": [],
  "final_codes": []
}

Prompt

In [17]:
codebook_string = '100: Macroeconomics\n  - 101: Inflation, prices, and interest rates\n  - 103: Unemployment rate\n  - 104: Monetary Supply, Central Bank, and the Treasury\n  - 105: National Budget, Debt, public spending\n  - 107: Taxation, Tax policy, and Tax Reform\n  - 108: Industrial Policy, Privatisation, Nationalisation\n\n200: Civil Rights\n  - 201: Ethnic Minority and Racial Group Discrimination\n  - 202: Gender and Sexual Orientation Discrimination\n  - 207: Freedom of Speech & Religion\n  - 208: Right to Privacy and Access to Government Information\n  - 230: Immigration\n\n300: Health\n  - 301: Health Care Reform\n  - 321: Regulation of Drug Industry, Medical Devices, and Clinical Labs\n  - 325: Health Manpower and Training\n  - 331: Prevention, Communicable Diseases and Health Promotion\n  - 332: Infants and Children\n  - 334: Long-Term Care, Home Health, and Rehabilitation\n  - 344: Drug and Alcohol or Substance Abuse Treatment\n\n400: Agriculture\n  - 401: Agricultural Trade\n  - 406: Animal Welfare\n  - 408: Fisheries and Fishing\n\n500: Labour and Employment\n  - 502: Employment Training and Workforce Development\n  - 503: Employee Benefits\n  - 504: Employee Relations and Labour Unions\n  - 505: Fair Labour Standards\n  - 506: Youth Employment and Child Labour\n  - 508: Parental Leave and Child Care\n  - 529: Migrant and Seasonal Workers\n\n600: Education\n  - 601: Higher Education\n  - 602: Elementary and Secondary Education\n  - 603: Education of Underprivileged Students\n  - 604: Vocational Education\n  - 606: Special Education\n\n700: Environment\n  - 701: Water Pollution\n  - 703: Waste Disposal\n  - 705: Air Pollution, Global Warming, and Noise Pollution\n  - 709: Species and Forest Protection\n\n800: Energy\n  - 801: Nuclear Energy and Nuclear Regulatory Issues\n  - 803: Natural Gas and Oil\n  - 805: Coal\n  - 806: Alternative and Renewable Energy\n  - 807: Energy Conservation\n\n1000: Transportation\n  - 1001: Mass and Public Transportation and Safety\n  - 1002: Highway (Road) Construction, Maintenance, and Safety\n  - 1003: Airports, Airlines, Air Traffic Control and Safety\n  - 1005: Railroad Transportation and Safety\n  - 1006: Truck and Automobile Transportation and Safety\n\n1200: Law, Crime, and Family Issues\n  - 1202: White Collar Crime and Organized Crime\n  - 1203: Illegal Drug Production, Trafficking, and Control\n  - 1205: Prison System\n  - 1206: Juvenile Crime and the Juvenile Justice System\n  - 1207: Child Abuse\n  - 1208: Family Issues\n  - 1209: Police, Fire, and Weapons Control\n  - 1211: Riots and Crime Prevention\n\n1300: Social Welfare\n  - 1302: Poverty and Assistance for Low-Income Families\n  - 1303: Elderly Issues and Elderly Assistance Programs, State Pensions\n  - 1304: Assistance to the Disabled and Handicapped\n  - 1305: Social Services and Volunteer Associations\n\n1400: Planning and Housing Issues\n  - 1401: Housing and Community Development\n  - 1406: Low and Middle Income Housing Programs and Needs\n  - 1407: Veterans Housing Assistance and Military Housing Programs\n  - 1409: Housing Assistance for Homeless and Homeless Issues\n  - 1410: Mortgages\n\n1500: Finance and Domestic Commerce\n  - 1501: Banking System and Financial Institution Regulation\n  - 1521: Small Business Issues\n  - 1524: Tourism\n\n1600: Defence\n  - 1603: Military Intelligence, Intelligence Services, Espionage\n  - 1608: Manpower, Military Personnel and Dependents\n  - 1609: Veterans Issues\n  - 1610: Military Procurement and Weapons System Acquisitions and Evaluation\n  - 1627: Domestic and International Terrorism\n\n1800: Foreign Trade\n  - 1803: Export Promotion and Regulation, Export Credit Agencies\n  - 1806: Productivity and Competitiveness of U.K. Business, U.K. Balance of Payments\n\n1900: International Affairs\n  - 1901: Foreign Aid\n  - 1907: China\n  - 1909: Eastern Europe\n  - 1910: Western Europe, Common Market Issues\n  - 1911: Africa\n  - 1920: Middle East\n  - 1926: International Organizations other than Finance\n  - 1930: North America and North Atlantic Ocean\n\n2000: Government Operations\n  - 2001: Intergovernmental Relations\n  - 2011: Executive-Legislative Relations and Parliamentary Operations\n  - 2012: Political Parties, Campaigns, and Voter Registration\n  - 2032: Prime Ministerial or Ministerial Scandals and Resignations\n'

In [18]:
print(codebook_string)

100: Macroeconomics
  - 101: Inflation, prices, and interest rates
  - 103: Unemployment rate
  - 104: Monetary Supply, Central Bank, and the Treasury
  - 105: National Budget, Debt, public spending
  - 107: Taxation, Tax policy, and Tax Reform
  - 108: Industrial Policy, Privatisation, Nationalisation

200: Civil Rights
  - 201: Ethnic Minority and Racial Group Discrimination
  - 202: Gender and Sexual Orientation Discrimination
  - 207: Freedom of Speech & Religion
  - 208: Right to Privacy and Access to Government Information
  - 230: Immigration

300: Health
  - 301: Health Care Reform
  - 321: Regulation of Drug Industry, Medical Devices, and Clinical Labs
  - 325: Health Manpower and Training
  - 331: Prevention, Communicable Diseases and Health Promotion
  - 332: Infants and Children
  - 334: Long-Term Care, Home Health, and Rehabilitation
  - 344: Drug and Alcohol or Substance Abuse Treatment

400: Agriculture
  - 401: Agricultural Trade
  - 406: Animal Welfare
  - 408: Fisheries and Fishing

500: Labour and Employment
  - 502: Employment Training and Workforce Development
  - 503: Employee Benefits
  - 504: Employee Relations and Labour Unions
  - 505: Fair Labour Standards
  - 506: Youth Employment and Child Labour
  - 508: Parental Leave and Child Care
  - 529: Migrant and Seasonal Workers

600: Education
  - 601: Higher Education
  - 602: Elementary and Secondary Education
  - 603: Education of Underprivileged Students
  - 604: Vocational Education
  - 606: Special Education

700: Environment
  - 701: Water Pollution
  - 703: Waste Disposal
  - 705: Air Pollution, Global Warming, and Noise Pollution
  - 709: Species and Forest Protection

800: Energy
  - 801: Nuclear Energy and Nuclear Regulatory Issues
  - 803: Natural Gas and Oil
  - 805: Coal
  - 806: Alternative and Renewable Energy
  - 807: Energy Conservation

1000: Transportation
  - 1001: Mass and Public Transportation and Safety
  - 1002: Highway (Road) Construction, Maintenance, and Safety
  - 1003: Airports, Airlines, Air Traffic Control and Safety
  - 1005: Railroad Transportation and Safety
  - 1006: Truck and Automobile Transportation and Safety

1200: Law, Crime, and Family Issues
  - 1202: White Collar Crime and Organized Crime
  - 1203: Illegal Drug Production, Trafficking, and Control
  - 1205: Prison System
  - 1206: Juvenile Crime and the Juvenile Justice System
  - 1207: Child Abuse
  - 1208: Family Issues
  - 1209: Police, Fire, and Weapons Control
  - 1211: Riots and Crime Prevention

1300: Social Welfare
  - 1302: Poverty and Assistance for Low-Income Families
  - 1303: Elderly Issues and Elderly Assistance Programs, State Pensions
  - 1304: Assistance to the Disabled and Handicapped
  - 1305: Social Services and Volunteer Associations

1400: Planning and Housing Issues
  - 1401: Housing and Community Development
  - 1406: Low and Middle Income Housing Programs and Needs
  - 1407: Veterans Housing Assistance and Military Housing Programs
  - 1409: Housing Assistance for Homeless and Homeless Issues
  - 1410: Mortgages

1500: Finance and Domestic Commerce
  - 1501: Banking System and Financial Institution Regulation
  - 1521: Small Business Issues
  - 1524: Tourism

1600: Defence
  - 1603: Military Intelligence, Intelligence Services, Espionage
  - 1608: Manpower, Military Personnel and Dependents
  - 1609: Veterans Issues
  - 1610: Military Procurement and Weapons System Acquisitions and Evaluation
  - 1627: Domestic and International Terrorism

1800: Foreign Trade
  - 1803: Export Promotion and Regulation, Export Credit Agencies
  - 1806: Productivity and Competitiveness of U.K. Business, U.K. Balance of Payments

1900: International Affairs
  - 1901: Foreign Aid
  - 1907: China
  - 1909: Eastern Europe
  - 1910: Western Europe, Common Market Issues
  - 1911: Africa
  - 1920: Middle East
  - 1926: International Organizations other than Finance
  - 1930: North America and North Atlantic Ocean

2000: Government Operations
  - 2001: Intergovernmental Relations
  - 2011: Executive-Legislative Relations and Parliamentary Operations
  - 2012: Political Parties, Campaigns, and Voter Registration
  - 2032: Prime Ministerial or Ministerial Scandals and Resignations

In [27]:
# better examples
def create_labelling_prompt(excerpt, examples_string, codebook_string):
    return f"""<start_of_turn>user
You are an expert Political Scientist specialising in content analysis. Your goal is to identify ONLY the primary policy topics in debate excerpts.
RULES:
1. HIERARCHY: You must provide the specific subcategory (e.g., 107) AND its parent supercategory (e.g., 100).
2. Do NOT independently infer supercategories. First identify subcategories. Then automatically include their parent supercategories.
2. THE STINGY RULE: If no codes apply, or if the text is purely rhetorical/filler, return empty lists []. Do not guess.
3. VALIDITY: Only use codes from the provided codebook.
4. You must only assign a code if there is explicit, unambiguous evidence in the text. If a label requires inference, DO NOT include it.

CODING CLARIFICATIONS:
- 105: Do NOT use 105 for general talk about the economy. Use 105 ONLY if explicit talk on reducing or increasing public spending
- 107: Use ONLY if a specific taxation mechanism (tex, levy, duty) is explicitly mentioned
- If both 105 and 107 are implied, choose ONLY the primary mechanism discussed
- 201: Do NOT use 201 if the text contains no reference to racism. Use 201 ONLY for explicit reference to racism
- 200: Do NOT use 200 codes except if the text explicitly refers to civil rights
- 1900: Ensure you use 1900 codes whenever the text refers to international cooperation
- 1300: Ensure you use 1300 codes whenever there is a reference to social welfare
        
CODEBOOK:
{codebook_string}

EXAMPLES:
{examples_string}

OUTPUT FORMAT:
First provide a section "Reasoning: " with a brief explanation.
Provide a JSON object with this structure:
{{
  "identified_supercategories": [100, 200],
  "identified_subcategories": [107, 201],
  "final_codes": [100, 107, 200, 201]  
}}

FINAL REMINDER:
You must conclude your response with a JSON block containing the keys: "identified_supercategories", "identified_subcategories", and "final_codes".

Annotate the following excerpt:"{excerpt}"<end_of_turn>
<start_of_turn>model
Reasoning: """

In [37]:
%%notify
# gemma model
batch_size = 8
results = []
with torch.no_grad():
    
    for i in range(0, 1112, batch_size):
        print(f"Progress: {i+1}/{1112}", end='\r')
        batch = df_turns.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
            current_examples = get_dynamic_examples_2(row['text'], k=5)
            p = create_labelling_prompt(row['text'], current_examples, codebook_string)
            prompts.append(p)        
                
        outputs = llm_model_gemma(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model_gemma.tokenizer.eos_token_id,
            return_full_text=False
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].strip()
            
            reasoning = ""
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            supercats, codes = [], []
            
            if json_match:
                json_str = json_match.group()                
                try:     
                    data = json.loads(json_str)
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            
            else:
                print(f"ID {row['ID']}: No JSON found in output.")
                
            results.append({
            "id": row['id'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })        
                                
results_df = pd.DataFrame(results)
results_df.to_csv("final_labels_0_1112.csv", index=False)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [38]:
%%notify
# gemma model
batch_size = 8
results = []
with torch.no_grad():
    
    for i in range(1111, len(df_turns), batch_size):
        print(f"Progress: {i+1}/{len(df_turns)}", end='\r')
        batch = df_turns.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
            current_examples = get_dynamic_examples_2(row['text'], k=5)
            p = create_labelling_prompt(row['text'], current_examples, codebook_string)
            prompts.append(p)        
                
        outputs = llm_model_gemma(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model_gemma.tokenizer.eos_token_id,
            return_full_text=False
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].strip()
            
            reasoning = ""
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            supercats, codes = [], []
            
            if json_match:
                json_str = json_match.group()                
                try:     
                    data = json.loads(json_str)
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            
            else:
                print(f"ID {row['ID']}: No JSON found in output.")
                
            results.append({
            "id": row['id'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })        
                                
results_df = pd.DataFrame(results)
results_df.to_csv("final_labels_1112_3319.csv", index=False)

KeyboardInterrupt:

In [39]:
results_df = pd.DataFrame(results)
results_df.to_csv("final_labels_1112_3319.csv", index=False)

In [ ]:
%%notify
# gemma model
batch_size = 8
results = []
with torch.no_grad():
    
    for i in range(1278, len(df_turns), batch_size):
        print(f"Progress: {i+1}/{len(df_turns)}", end='\r')
        batch = df_turns.iloc[i:i+batch_size]
        
        prompts = []
        for _, row in batch.iterrows():
            current_examples = get_dynamic_examples_2(row['text'], k=5)
            p = create_labelling_prompt(row['text'], current_examples, codebook_string)
            prompts.append(p)        
                
        outputs = llm_model_gemma(
            prompts,
            max_new_tokens=400,
            eos_token_id=terminators,
            do_sample=False,
            pad_token_id=llm_model_gemma.tokenizer.eos_token_id,
            return_full_text=False
        )
        
        index=0
        for output, (_, row) in zip(outputs, batch.iterrows()):  
            index+=1
            generated_text = output[0]['generated_text'].strip()
            
            reasoning = ""
            try:
                reasoning = generated_text.split('{')[0].replace("Reasoning:", "").strip()
            except:
                reasoning = ""
            
            json_match = re.search(r'\{.*?\}', generated_text, re.DOTALL)
            supercats, codes = [], []
            
            if json_match:
                json_str = json_match.group()                
                try:     
                    data = json.loads(json_str)
                    supercats = data.get('identified_supercategories', [])
                    codes = data.get('final_codes', [])
                    if not codes:
                        codes = data.get('identified_subcategories', [])
                except json.JSONDecodeError:
                    codes = [int(c) for c in re.findall(r'\b\d{3,4}\b', json_str)]
                    print(f"ID {row['ID']}: JSON broken, rescued codes via regex. Output: {generated_text[:50]}")            
            else:
                print(f"ID {row['ID']}: No JSON found in output.")
                
            results.append({
            "id": row['id'],
            "reasoning": reasoning,
            "supercategories": supercats,
            "claim_labels": codes
            })        
        if i in [1566,1710,1854,1998,2142,2286,2286,2430,2574,2718,2862,3006,3150,3294]:
            temp_df = pd.DataFrame(results)
            temp_df.to_csv("final_labels_1112_temp.csv", index=False)
            
results_df = pd.DataFrame(results)
results_df.to_csv("final_labels_1112_end.csv", index=False)

In [4]:
df_labels = pd.read_csv("final_labels_stage_1.csv")

In [99]:
# fix logical errors programmatically
def fix_hierarchy(codes):
    final_codes = set(codes)
    for code in codes:
        if code % 100 != 0:
            supercategory = (code // 100) * 100
            final_codes.add(supercategory)
    return sorted(list(final_codes))

def check_inconsistency(codes):
    for code in codes:
        if code % 100 != 0:
            if (code // 100) * 100 not in codes:
                return True
    return False

In [6]:
df_labels['claim_labels'] = df_labels['claim_labels'].apply(ast.literal_eval)
df_labels['claim_labels'] = df_labels['claim_labels'].apply(fix_hierarchy)
inconsistent_count = df_labels['claim_labels'].apply(check_inconsistency).sum()
print(f"Remaining inconsistent rows: {inconsistent_count}")

Remaining inconsistent rows: 0

In [7]:
df_labels

,id,reasoning,supercategories,claim_labels
0,344,The excerpt discusses economic policy choices ...,"[100, 300]","[100, 105, 300, 301]"
1,345,"The excerpt discusses immigration policy, incl...",[200],"[200, 230]"
2,346,The excerpt discusses the need for increased f...,"[100, 1300]","[100, 105, 107, 1300, 1302]"
3,347,The excerpt discusses the release of a terrori...,"[1200, 1600]","[1200, 1205, 1600, 1627]"
4,348,The text discusses the financial implications ...,"[1900, 100]","[100, 105, 1900, 1910]"
...,...,...,...,...
3314,3683,The excerpt discusses the National Health Serv...,"[300, 100]","[100, 105, 300, 301]"
3315,3684,The excerpt expresses regret for causing harm ...,[1600],"[1600, 1609]"
3316,3685,The excerpt discusses a change in someone's op...,[],[]
3317,3686,The text discusses the issue of people using p...,"[100, 1300]","[100, 108, 1300, 1302]"
3318,3687,The text discusses tuition fees and implies a ...,[600],"[600, 601]"

In [32]:
def no_childless_supercats(codes):
    no_childless = 0
    final_codes = set(codes)
    needed_supercats = []
    for code in codes:        
        supercat = code - code%100
        needed_supercats.append(supercat)
    needed_supercats=set(needed_supercats)
    for s in needed_supercats:
        childless=True
        # if there is no code that gives the same supercat but isn't the
        # supercat, increase no of childless supercats        
        for code in codes:
            if code!=s and (code-code%100)==s:
                childless=False
                break
        if childless==True:
            no_childless+=1
        
    return no_childless

In [36]:
childless_ids = []
for _, row in df_labels.iterrows():
    if no_childless_supercats(row['claim_labels']) > 0:
        childless_ids.append(row['id'])
print(childless_ids)
df_labels.loc[df_labels['id'].isin(childless_ids)]

[352, 371, 373, 383, 422, 445, 468, 475, 476, 487, 507, 542, 559, 568, 569, 594, 596, 646, 648, 693, 702, 704, 706, 744, 785, 790, 805, 834, 839, 841, 855, 858, 896, 980, 986, 1022, 1025, 1029, 1032, 1043, 1047, 1065, 1077, 1086, 1090, 1093, 1106, 1109, 1119, 1122, 1123, 1144, 1148, 1160, 1175, 1184, 1191, 1198, 1215, 1267, 1276, 1278, 1283, 1300, 1305, 1306, 1311, 1316, 1360, 1375, 1378, 1392, 1408, 1415, 1417, 1436, 1447, 1461, 1463, 1470, 1478, 1506, 1526, 1528, 1535, 1547, 1552, 1558, 1577, 1598, 1606, 1622, 1627, 1632, 1638, 1643, 1657, 1665, 1673, 1675, 1683, 1701, 1730, 1737, 1746, 1747, 1781, 1784, 1807, 1819, 1833, 1834, 1839, 1842, 1849, 1901, 1903, 1910, 1912, 1957, 1963, 1978, 1983, 2043, 2047, 2048, 2053, 2069, 2083, 2101, 2104, 2107, 2109, 2131, 2133, 2148, 2174, 2180, 2228, 2231, 2235, 2257, 2264, 2265, 2271, 2294, 2309, 2337, 2361, 2365, 2366, 2367, 2384, 2385, 2388, 2389, 2390, 2393, 2406, 2417, 2429, 2434, 2440, 2442, 2452, 2456, 2472, 2504, 2525, 2528, 2554, 2556, 2565, 2580, 2584, 2600, 2632, 2685, 2703, 2709, 2714, 2725, 2733, 2736, 2745, 2749, 2755, 2761, 2762, 2797, 2818, 2841, 2844, 2850, 2858, 2867, 2877, 2884, 2888, 2894, 2900, 2927, 2947, 2950, 2951, 2954, 2967, 2978, 2987, 3021, 3022, 3029, 3044, 3052, 3061, 3063, 3071, 3072, 3088, 3103, 3104, 3122, 3126, 3140, 3147, 3157, 3162, 3195, 3198, 3228, 3242, 3246, 3255, 3282, 3300, 3313, 3322, 3340, 3348, 3363, 3386, 3390, 3430, 3449, 3454, 3458, 3466, 3501, 3518, 3520, 3522, 3531, 3542, 3554, 3569, 3575, 3576, 3587, 3589, 3591, 3598, 3618, 3636, 3643, 3644, 3662]

,id,reasoning,supercategories,claim_labels
7,352,"The excerpt discusses the current tax burden, ...","[100, 1300]","[100, 105, 1300]"
25,371,The excerpt discusses the European Exchange Ra...,[1900],[1900]
27,373,The text explicitly discusses the cost of Trid...,"[100, 600, 200]","[100, 105, 200, 600, 602]"
37,383,The excerpt discusses the limitations of contr...,[1900],"[200, 230, 1900]"
72,422,"The text discusses immigration, public service...","[100, 200]","[100, 200, 201, 500]"
...,...,...,...,...
3249,3618,The excerpt discusses climate change denial an...,"[700, 1900]","[700, 705, 1900]"
3267,3636,"The excerpt mentions ""problems facing the coun...","[100, 2000]","[100, 2000]"
3274,3643,The excerpt discusses redirecting funds from t...,"[1900, 100]","[100, 1900, 1901]"
3275,3644,The excerpt expresses a callous disregard for ...,[1300],[1300]
3293,3662,The text discusses government spending and deb...,"[100, 200]","[100, 105, 200]"

Separate rows according to tiers of quality:
* Tier 1: with labels for which LLM labelling had F1 >= 0.7 (compared to human)
* Tier 2: 0.4 <= F1 < 0.7
* Tier 3: support <= 10 or F1 < 0.4

In [45]:
df_quality = pd.read_csv('llm_per_label_performance.csv')
df_quality

             code  precision    recall  f1-score  support
0     samples avg   0.472116  0.508562  0.470239   1019.0
1    weighted avg   0.589953  0.559372  0.533915   1019.0
2       macro avg   0.362536  0.322909  0.302198   1019.0
3       micro avg   0.521978  0.559372  0.540028   1019.0
4             100   0.568345  0.877778  0.689956     90.0
..            ...        ...       ...       ...      ...
103           801   0.000000  0.000000  0.000000      1.0
104          1501   0.000000  0.000000  0.000000      1.0
105          1524   0.000000  0.000000  0.000000      1.0
106          1907   0.000000  0.000000  0.000000      1.0
107          1911   0.000000  0.000000  0.000000      1.0

[108 rows x 5 columns]

In [47]:
df_quality = df_quality.loc[~df_quality['code'].isin(['samples avg', 'weighted avg', 'macro avg', 'micro avg'])]
df_quality

     code  precision    recall  f1-score  support
4     100   0.568345  0.877778  0.689956     90.0
5    1900   0.803030  0.791045  0.796992     67.0
6     107   0.619048  0.847826  0.715596     46.0
7    1910   0.870968  0.627907  0.729730     43.0
8     105   0.410959  0.731707  0.526316     41.0
..    ...        ...       ...       ...      ...
103   801   0.000000  0.000000  0.000000      1.0
104  1501   0.000000  0.000000  0.000000      1.0
105  1524   0.000000  0.000000  0.000000      1.0
106  1907   0.000000  0.000000  0.000000      1.0
107  1911   0.000000  0.000000  0.000000      1.0

[104 rows x 5 columns]

In [48]:
df_quality['code'] = df_quality['code'].apply(ast.literal_eval)
df_quality

/tmp/ipykernel_2828996/752108434.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_quality['code'] = df_quality['code'].apply(ast.literal_eval)

     code  precision    recall  f1-score  support
4     100   0.568345  0.877778  0.689956     90.0
5    1900   0.803030  0.791045  0.796992     67.0
6     107   0.619048  0.847826  0.715596     46.0
7    1910   0.870968  0.627907  0.729730     43.0
8     105   0.410959  0.731707  0.526316     41.0
..    ...        ...       ...       ...      ...
103   801   0.000000  0.000000  0.000000      1.0
104  1501   0.000000  0.000000  0.000000      1.0
105  1524   0.000000  0.000000  0.000000      1.0
106  1907   0.000000  0.000000  0.000000      1.0
107  1911   0.000000  0.000000  0.000000      1.0

[104 rows x 5 columns]

In [71]:
tier_1, tier_2, tier_3 = [], [], []
for _, row in df_quality.iterrows(): 
    if row['support'] <= 5 or row['f1-score']<0.4:
        tier_3.append(int(row['code']))
    elif 0.4<=row['f1-score'] and row['f1-score']<0.7:
        tier_2.append(int(row['code']))
    elif row['f1-score'] >= 0.7:
        tier_1.append(int(row['code']))
        
print(f"Tier 3 length: {len(tier_3)}")
print(tier_3)
print("")
print(f"Tier 2 length: {len(tier_2)}")
print(tier_2)
print("")
print(f"Tier 1 length: {len(tier_1)}")
print(tier_1)
print("")

Tier 3 length: 71
[500, 325, 529, 1302, 1211, 1930, 2001, 1401, 108, 1406, 101, 1500, 201, 1208, 503, 505, 1205, 1207, 1909, 103, 508, 400, 1006, 502, 603, 506, 504, 806, 2011, 1609, 1521, 803, 1202, 401, 344, 334, 207, 331, 604, 1901, 2032, 1806, 1001, 1206, 807, 1005, 1305, 1603, 208, 104, 321, 332, 399, 408, 406, 703, 701, 606, 1409, 805, 1002, 1003, 1203, 709, 1407, 1304, 801, 1501, 1524, 1907, 1911]

Tier 2 length: 23
[100, 105, 200, 300, 2000, 1300, 1400, 301, 2012, 705, 1303, 1209, 1610, 602, 1800, 1926, 1627, 800, 1410, 1608, 202, 1000, 1803]

Tier 1 length: 10
[1900, 107, 1910, 1200, 230, 1600, 700, 600, 1920, 601]

In [63]:
# restrict tier codes to subcategories to avoid overlap
def tier_edit(t_list):
    new_list = []
    for c in t_list:
        if c%100 != 0:
            new_list.append(c)
    return new_list

In [72]:
tier_1_sub = tier_edit(tier_1)
tier_2_sub = tier_edit(tier_2)
tier_3_sub = tier_edit(tier_3)

print(f"Tier 3 length: {len(tier_3_sub)}")
print(tier_3_sub)
print("")
print(f"Tier 2 length: {len(tier_2_sub)}")
print(tier_2_sub)
print("")
print(f"Tier 1 length: {len(tier_1_sub)}")
print(tier_1_sub)
print("")

Tier 3 length: 68
[325, 529, 1302, 1211, 1930, 2001, 1401, 108, 1406, 101, 201, 1208, 503, 505, 1205, 1207, 1909, 103, 508, 1006, 502, 603, 506, 504, 806, 2011, 1609, 1521, 803, 1202, 401, 344, 334, 207, 331, 604, 1901, 2032, 1806, 1001, 1206, 807, 1005, 1305, 1603, 208, 104, 321, 332, 399, 408, 406, 703, 701, 606, 1409, 805, 1002, 1003, 1203, 709, 1407, 1304, 801, 1501, 1524, 1907, 1911]

Tier 2 length: 14
[105, 301, 2012, 705, 1303, 1209, 1610, 602, 1926, 1627, 1410, 1608, 202, 1803]

Tier 1 length: 5
[107, 1910, 230, 1920, 601]

In [76]:
df_tiered = df_labels.copy()
df_tiered['watch_labels']=None
tier_id_1, tier_id_2, tier_id_3 = [],[],[]
for index, row in df_tiered.iterrows():
    # if there is a tier x code in the label, add the id to tier_x_id list
    tier_3_check=list(set(tier_3_sub)&set(row['claim_labels']))    
    tier_2_check=list(set(tier_2_sub)&set(row['claim_labels']))
    tier_1_check=list(set(tier_1_sub)&set(row['claim_labels']))
    if len(tier_3_check)>0:
        tier_id_3.append(row['id'])
        df_tiered.at[index, 'watch_labels'] = tier_3_check
    elif len(tier_2_check)>0:
        tier_id_2.append(row['id'])
        df_tiered.at[index, 'watch_labels'] = tier_2_check
    elif len(tier_1_check)>0 or row['claim_labels']==[]:
        tier_id_1.append(row['id'])
        df_tiered.at[index, 'watch_labels'] = tier_1_check
    else:
        # repeat for childless supercats
        tier_3_check=list(set(tier_3)&set(row['claim_labels']))    
        tier_2_check=list(set(tier_2)&set(row['claim_labels']))
        tier_1_check=list(set(tier_1)&set(row['claim_labels']))
        if len(tier_3_check)>0:
            tier_id_3.append(row['id'])
            df_tiered.at[index, 'watch_labels'] = tier_3_check
        elif len(tier_2_check)>0:
            tier_id_2.append(row['id'])
            df_tiered.at[index, 'watch_labels'] = tier_2_check
        elif len(tier_1_check)>0 or row['claim_labels']==[]:
            tier_id_1.append(row['id'])
            df_tiered.at[index, 'watch_labels'] = tier_1_check
        else:
            print(row['claim_labels'])
            print("")

len(tier_id_1)+len(tier_id_2)+len(tier_id_3)

3319

In [85]:
df_tier_1 = df_tiered.loc[df_tiered['id'].isin(tier_id_1)].copy()
df_tier_1 = df_tier_1.merge(df_turns[['id', 'text']], on='id', how='left')
df_tier_1

,id,reasoning,supercategories,claim_labels,watch_labels,text
0,345,"The excerpt discusses immigration policy, incl...",[200],"[200, 230]",[230],"Of course, we have to improve the system, but ..."
1,349,The excerpt discusses the need for a fair and ...,[200],"[200, 230]",[230],I think this is partly what's been going wrong...
2,354,The excerpt discusses the speaker's personal r...,[],[],[],Or you could actually take the view that I'm n...
3,356,The excerpt is purely rhetorical and does not ...,[],[],[],But then you'll ignore the result. No.
4,358,The speaker explicitly states their desire to ...,[1900],"[1900, 1910]",[1910],No. I want to be a member of the European Unio...
...,...,...,...,...,...,...
980,3670,The excerpt expresses a hope and intention but...,[],[],[],"Oh, I very much hope so yes, that's my intention."
981,3673,The excerpt is purely rhetorical and does not ...,[],[],[],But we would put it in to practise.
982,3679,The excerpt is purely rhetorical and does not ...,[],[],[],"Are you disagreeing with the IFS, Angela?"
983,3685,The excerpt discusses a change in someone's op...,[],[],[],"...that he wasn't originally in favour, er, he..."
984,3687,The text discusses tuition fees and implies a ...,[600],"[600, 601]",[601],"And it wasn't tripled, and we didn't triple tu..."

In [86]:
df_tier_2 = df_tiered.loc[df_tiered['id'].isin(tier_id_2)].copy()
df_tier_2 = df_tier_2.merge(df_turns[['id', 'text']], on='id', how='left')
df_tier_2

,id,reasoning,supercategories,claim_labels,watch_labels,text
0,344,The excerpt discusses economic policy choices ...,"[100, 300]","[100, 105, 300, 301]","[105, 301]",Ed Miliband. You've heard tonight from five di...
1,348,The text discusses the financial implications ...,"[1900, 100]","[100, 105, 1900, 1910]",[105],It isn't a question of what it's worth paying ...
2,352,"The excerpt discusses the current tax burden, ...","[100, 1300]","[100, 105, 1300]",[105],"Well, the first thing I'd say is the Tories ar..."
3,362,"The excerpt discusses taxation, public spendin...","[100, 300]","[100, 105, 300, 301]","[105, 301]","Well, in relation to taxation, I do need to be..."
4,366,The excerpt discusses the economic policies of...,[100],"[100, 105]",[105],I don't say there is no difference between Ed ...
...,...,...,...,...,...,...
888,3674,The text expresses frustration with the politi...,[2000],"[2000, 2012]",[2012],"Well, listening to Richard and Rishi, frankly,..."
889,3677,"The text discusses the need for more teachers,...",[600],"[100, 107, 600, 602]",[602],Because I believe every child should have the ...
890,3678,The text discusses the voting systems in Scotl...,[2000],"[2000, 2012]",[2012],"if you're in a hung Parliament? Well, I'll try..."
891,3680,The excerpt discusses the NHS budget and its r...,"[100, 300]","[100, 105, 300, 301]","[105, 301]","The point is, we have made a special exception..."
892,3683,The excerpt discusses the National Health Serv...,"[300, 100]","[100, 105, 300, 301]","[105, 301]","Nigel Farage. Well, I mean, the fact that ther..."

In [87]:
df_tier_3 = df_tiered.loc[df_tiered['id'].isin(tier_id_3)].copy()
df_tier_3 = df_tier_3.merge(df_turns[['id', 'text']], on='id', how='left')
df_tier_3

,id,reasoning,supercategories,claim_labels,watch_labels,text
0,346,The excerpt discusses the need for increased f...,"[100, 1300]","[100, 105, 107, 1300, 1302]",[1302],"I've never been called timid in my life, but c..."
1,347,The excerpt discusses the release of a terrori...,"[1200, 1600]","[1200, 1205, 1600, 1627]",[1205],"Well, Darren, in answer to your question, obvi..."
2,350,The text discusses the future of the oil and g...,"[800, 100]","[100, 101, 800, 803]","[803, 101]","And I was actually just going to come to that,..."
3,353,The text explicitly discusses the beliefs of a...,"[200, 1900]","[200, 201, 1900, 1907]","[201, 1907]","I know many Muslims, but the reality is the He..."
4,355,The text discusses reducing the cost of living...,"[100, 1300]","[100, 107, 1300, 1302]",[1302],Well there is the question of wages and benefi...
...,...,...,...,...,...,...
1436,3676,"The text discusses crime rates, police officer...",[1200],"[1200, 1202, 1209]",[1202],"Well, of course, as I've already outlined, as ..."
1437,3681,The excerpt mentions government spending ineff...,"[100, 200]","[100, 105, 200, 201]",[201],"What I would say is, for example, the Dome was..."
1438,3682,The excerpt discusses the state of the NHS and...,"[100, 300]","[100, 107, 300, 325]",[325],"Terry, like so many people around the country,..."
1439,3684,The excerpt expresses regret for causing harm ...,[1600],"[1600, 1609]",[1609],"Yeah, I was incredibly sad to have caused peop..."
1440,3686,The text discusses the issue of people using p...,"[100, 1300]","[100, 108, 1300, 1302]","[108, 1302]",There are lots of people who go for private he...

if the row has tier_3 codes, leave as is  
elif the row has tier_2, apply embedding  
elif the row has tier_1, adjudicate

In [90]:
df_tier_1.to_csv("tier_1_labels.csv")
df_tier_2.to_csv("tier_2_labels.csv")
df_tier_3.to_csv("tier_3_labels.csv")

In [16]:
# embedding filtering for tier 2 labels
df_tier_2 = pd.read_csv("tier_2_labels.csv", index_col=0)
df_gold = pd.read_csv("labelling_validation.csv")

In [46]:
df_tier_3 = pd.read_csv("tier_3_labels.csv", index_col=0)

In [47]:
df_tier_3

,id,reasoning,supercategories,claim_labels,watch_labels,text
0,346,The excerpt discusses the need for increased f...,"[100, 1300]","[100, 105, 107, 1300, 1302]",[1302],"I've never been called timid in my life, but c..."
1,347,The excerpt discusses the release of a terrori...,"[1200, 1600]","[1200, 1205, 1600, 1627]",[1205],"Well, Darren, in answer to your question, obvi..."
2,350,The text discusses the future of the oil and g...,"[800, 100]","[100, 101, 800, 803]","[803, 101]","And I was actually just going to come to that,..."
3,353,The text explicitly discusses the beliefs of a...,"[200, 1900]","[200, 201, 1900, 1907]","[201, 1907]","I know many Muslims, but the reality is the He..."
4,355,The text discusses reducing the cost of living...,"[100, 1300]","[100, 107, 1300, 1302]",[1302],Well there is the question of wages and benefi...
...,...,...,...,...,...,...
1436,3676,"The text discusses crime rates, police officer...",[1200],"[1200, 1202, 1209]",[1202],"Well, of course, as I've already outlined, as ..."
1437,3681,The excerpt mentions government spending ineff...,"[100, 200]","[100, 105, 200, 201]",[201],"What I would say is, for example, the Dome was..."
1438,3682,The excerpt discusses the state of the NHS and...,"[100, 300]","[100, 107, 300, 325]",[325],"Terry, like so many people around the country,..."
1439,3684,The excerpt expresses regret for causing harm ...,[1600],"[1600, 1609]",[1609],"Yeah, I was incredibly sad to have caused peop..."
1440,3686,The text discusses the issue of people using p...,"[100, 1300]","[100, 108, 1300, 1302]","[108, 1302]",There are lots of people who go for private he...

In [6]:
def parse_list(val):
    if pd.isna(val) or val == "" or str(val).strip() == "[]": return []
    try:
        res = ast.literal_eval(str(val))
        return [str(x) for x in res] if isinstance(res, list) else [str(res)]
    except:
        return [x.strip() for x in str(val).replace('[', '').replace(']', '').split(',') if x.strip()]

In [29]:
def parse_list_robust(val):
    if pd.isna(val) or val == "" or str(val).strip() == "[]": 
        return []
    try:
        res = ast.literal_eval(str(val))        
        if isinstance(res, (list, tuple)):
            return [str(x).strip() for x in res]
        return [str(res).strip()]
    except:
        return [x.strip() for x in str(val).replace('[', '').replace(']', '').replace('(', '').replace(')', '').split(',') if x.strip()]

In [30]:
df_tier_2['parsed_watch'] = df_tier_2['watch_labels'].apply(parse_list_robust)
df_gold['parsed_gold'] = df_gold['Claim_Labels'].apply(parse_list_robust)

In [48]:
df_tier_3['parsed_watch'] = df_tier_3['watch_labels'].apply(parse_list_robust)

In [32]:
# creating the semantic feature space
all_texts = df_gold['Text'].fillna("").tolist() + df_tier_2['text'].fillna("").tolist()
vectorizer = TfidfVectorizer(stop_words='english', max_features=1000)
vectorizer.fit(all_texts)

gold_vecs = vectorizer.transform(df_gold['Text'].fillna(""))
tier_2_vecs = vectorizer.transform(df_tier_2['text'].fillna(""))

In [52]:
# repeat for tier3
all_texts = df_gold['Text'].fillna("").tolist() + df_tier_3['text'].fillna("").tolist()
vectorizer = TfidfVectorizer(stop_words='english', max_features=1000)
vectorizer.fit(all_texts)

gold_vecs = vectorizer.transform(df_gold['Text'].fillna(""))
tier_3_vecs = vectorizer.transform(df_tier_3['text'].fillna(""))

In [33]:
gold_centroids = {}
unique_labels_to_check = set([lbl for sublist in df_tier_2['parsed_watch'] for lbl in sublist])
for label in unique_labels_to_check:
    mask = df_gold['parsed_gold'].apply(lambda x: label in x)
    if mask.any():
        gold_centroids[label] = np.asarray(gold_vecs[mask].mean(axis=0))
    else:
        # if no examples are found of the label in the human set
        gold_centroids[label] = None

In [53]:
# repaet for tier3
gold_centroids_3 = {}
unique_labels_to_check = set([lbl for sublist in df_tier_3['parsed_watch'] for lbl in sublist])
for label in unique_labels_to_check:
    mask = df_gold['parsed_gold'].apply(lambda x: label in x)
    if mask.any():
        gold_centroids_3[label] = np.asarray(gold_vecs[mask].mean(axis=0))
    else:
        # if no examples are found of the label in the human set
        gold_centroids_3[label] = None

In [35]:
results = []
for idx, row in df_tier_2.iterrows():
    text_vec = tier_2_vecs[idx]
    for label in row['parsed_watch']:
        similarity = 0.0
        if label in gold_centroids and gold_centroids[label] is not None:
            similarity = cosine_similarity(text_vec, gold_centroids[label])[0][0]
        results.append({'id': row['id'], 'label': label, 'gold_similarity': similarity})

filtering_df = pd.DataFrame(results)
filtering_df.to_csv('tier2_embedding_filtering.csv')

In [54]:
# repeat for tier3
results = []
for idx, row in df_tier_3.iterrows():
    text_vec = tier_3_vecs[idx]
    for label in row['parsed_watch']:
        similarity = 0.0
        if label in gold_centroids_3 and gold_centroids_3[label] is not None:
            similarity = cosine_similarity(text_vec, gold_centroids_3[label])[0][0]
        results.append({'id': row['id'], 'label': label, 'gold_similarity': similarity})

filtering_df_3 = pd.DataFrame(results)
filtering_df_3.to_csv('tier3_embedding_filtering.csv')

In [39]:
valid_pairs = set(
    filtering_df[filtering_df['gold_similarity'] >= 0.2]
    .apply(lambda x: (x['id'], str(x['label'])), axis=1)
)

In [56]:
# repeat for tier 3
valid_pairs_3 = set(
    filtering_df_3[filtering_df_3['gold_similarity'] >= 0.2]
    .apply(lambda x: (x['id'], str(x['label'])), axis=1)
)

In [41]:
def filter_label_list(row):
    try:
        original_labels = ast.literal_eval(str(row['claim_labels']))
        cleaned_labels = [
            lbl for lbl in original_labels 
            if (row['id'], str(lbl)) in valid_pairs
        ]        
        return cleaned_labels
    except:
        return []

In [42]:
df_tier_2['claim_labels_cleaned'] = df_tier_2.apply(filter_label_list, axis=1)
df_tier_2_cleaned = df_tier_2[df_tier_2['claim_labels_cleaned'].map(len) > 0].copy()
df_tier_2_cleaned['claim_labels'] = df_tier_2_cleaned['claim_labels_cleaned']
df_tier_2_cleaned = df_tier_2_cleaned.drop(columns=['claim_labels_cleaned'])
print(f"Original rows: {len(df_tier_2)}")
print(f"Rows remaining after similarity filtering: {len(df_tier_2_cleaned)}")

Original rows: 893
Rows remaining after similarity filtering: 443

In [57]:
df_tier_3['claim_labels_cleaned'] = df_tier_3.apply(filter_label_list, axis=1)
df_tier_3_cleaned = df_tier_3[df_tier_3['claim_labels_cleaned'].map(len) > 0].copy()
df_tier_3_cleaned['claim_labels'] = df_tier_3_cleaned['claim_labels_cleaned']
df_tier_3_cleaned = df_tier_3_cleaned.drop(columns=['claim_labels_cleaned'])
print(f"Original rows: {len(df_tier_3)}")
print(f"Rows remaining after similarity filtering: {len(df_tier_3_cleaned)}")

Original rows: 1441
Rows remaining after similarity filtering: 0

In [58]:
df_tier_2_cleaned.to_csv('tier_2_cleaned.csv')

In [37]:
df_tier_2

,id,reasoning,supercategories,claim_labels,watch_labels,text,parsed_watch
0,344,The excerpt discusses economic policy choices ...,"[100, 300]","[100, 105, 300, 301]","[105, 301]",Ed Miliband. You've heard tonight from five di...,"[105, 301]"
1,348,The text discusses the financial implications ...,"[1900, 100]","[100, 105, 1900, 1910]",[105],It isn't a question of what it's worth paying ...,[105]
2,352,"The excerpt discusses the current tax burden, ...","[100, 1300]","[100, 105, 1300]",[105],"Well, the first thing I'd say is the Tories ar...",[105]
3,362,"The excerpt discusses taxation, public spendin...","[100, 300]","[100, 105, 300, 301]","[105, 301]","Well, in relation to taxation, I do need to be...","[105, 301]"
4,366,The excerpt discusses the economic policies of...,[100],"[100, 105]",[105],I don't say there is no difference between Ed ...,[105]
...,...,...,...,...,...,...,...
888,3674,The text expresses frustration with the politi...,[2000],"[2000, 2012]",[2012],"Well, listening to Richard and Rishi, frankly,...",[2012]
889,3677,"The text discusses the need for more teachers,...",[600],"[100, 107, 600, 602]",[602],Because I believe every child should have the ...,[602]
890,3678,The text discusses the voting systems in Scotl...,[2000],"[2000, 2012]",[2012],"if you're in a hung Parliament? Well, I'll try...",[2012]
891,3680,The excerpt discusses the NHS budget and its r...,"[100, 300]","[100, 105, 300, 301]","[105, 301]","The point is, we have made a special exception...","[105, 301]"
892,3683,The excerpt discusses the National Health Serv...,"[300, 100]","[100, 105, 300, 301]","[105, 301]","Nigel Farage. Well, I mean, the fact that ther...","[105, 301]"

In [55]:
filtering_df_3

        id label  gold_similarity
0      346  1302         0.169905
1      347  1205         0.106466
2      350   803         0.213280
3      350   101         0.101854
4      353   201         0.157453
...    ...   ...              ...
1906  3681   201         0.104533
1907  3682   325         0.355582
1908  3684  1609         0.226532
1909  3686   108         0.117576
1910  3686  1302         0.076346

[1911 rows x 3 columns]

The final labels will use:
* tier_1_labels.csv
* tier_2_cleaned.csv
* tier_3_labels.csv  

for train, and labelling_validation.csv for test

---

Get the examples from Dayanik et al. and get labels that suit them for train and test csv

In [59]:
df_tier_2_cleaned

,id,reasoning,supercategories,claim_labels,watch_labels,text,parsed_watch
0,344,The excerpt discusses economic policy choices ...,"[100, 300]",[105],"[105, 301]",Ed Miliband. You've heard tonight from five di...,"[105, 301]"
2,352,"The excerpt discusses the current tax burden, ...","[100, 1300]",[105],[105],"Well, the first thing I'd say is the Tories ar...",[105]
3,362,"The excerpt discusses taxation, public spendin...","[100, 300]","[105, 301]","[105, 301]","Well, in relation to taxation, I do need to be...","[105, 301]"
4,366,The excerpt discusses the economic policies of...,[100],[105],[105],I don't say there is no difference between Ed ...,[105]
6,370,"The excerpt discusses Brexit, a people's vote,...","[1900, 2000]",[2012],[2012],Thank you. Sian Berry. I understand completely...,[2012]
...,...,...,...,...,...,...,...
886,3667,The excerpt discusses government spending cuts...,[100],[105],[105],"Well, Geoffrey, first of all, austerity Tory a...",[105]
887,3668,The excerpt discusses a proposed local tax sys...,[100],[105],[105],"Well, if you have a household income in the re...",[105]
888,3674,The text expresses frustration with the politi...,[2000],[2012],[2012],"Well, listening to Richard and Rishi, frankly,...",[2012]
891,3680,The excerpt discusses the NHS budget and its r...,"[100, 300]",[301],"[105, 301]","The point is, we have made a special exception...","[105, 301]"
892,3683,The excerpt discusses the National Health Serv...,"[300, 100]","[105, 301]","[105, 301]","Nigel Farage. Well, I mean, the fact that ther...","[105, 301]"

In [60]:
df_tier_1 = pd.read_csv("tier_1_labels.csv", index_col=0)
df_tier_1

,id,reasoning,supercategories,claim_labels,watch_labels,text
0,345,"The excerpt discusses immigration policy, incl...",[200],"[200, 230]",[230],"Of course, we have to improve the system, but ..."
1,349,The excerpt discusses the need for a fair and ...,[200],"[200, 230]",[230],I think this is partly what's been going wrong...
2,354,The excerpt discusses the speaker's personal r...,[],[],[],Or you could actually take the view that I'm n...
3,356,The excerpt is purely rhetorical and does not ...,[],[],[],But then you'll ignore the result. No.
4,358,The speaker explicitly states their desire to ...,[1900],"[1900, 1910]",[1910],No. I want to be a member of the European Unio...
...,...,...,...,...,...,...
980,3670,The excerpt expresses a hope and intention but...,[],[],[],"Oh, I very much hope so yes, that's my intention."
981,3673,The excerpt is purely rhetorical and does not ...,[],[],[],But we would put it in to practise.
982,3679,The excerpt is purely rhetorical and does not ...,[],[],[],"Are you disagreeing with the IFS, Angela?"
983,3685,The excerpt discusses a change in someone's op...,[],[],[],"...that he wasn't originally in favour, er, he..."
984,3687,The text discusses tuition fees and implies a ...,[600],"[600, 601]",[601],"And it wasn't tripled, and we didn't triple tu..."

In [61]:
df_tier_3

,id,reasoning,supercategories,claim_labels,watch_labels,text,parsed_watch,claim_labels_cleaned
0,346,The excerpt discusses the need for increased f...,"[100, 1300]","[100, 105, 107, 1300, 1302]",[1302],"I've never been called timid in my life, but c...",[1302],[]
1,347,The excerpt discusses the release of a terrori...,"[1200, 1600]","[1200, 1205, 1600, 1627]",[1205],"Well, Darren, in answer to your question, obvi...",[1205],[]
2,350,The text discusses the future of the oil and g...,"[800, 100]","[100, 101, 800, 803]","[803, 101]","And I was actually just going to come to that,...","[803, 101]",[]
3,353,The text explicitly discusses the beliefs of a...,"[200, 1900]","[200, 201, 1900, 1907]","[201, 1907]","I know many Muslims, but the reality is the He...","[201, 1907]",[]
4,355,The text discusses reducing the cost of living...,"[100, 1300]","[100, 107, 1300, 1302]",[1302],Well there is the question of wages and benefi...,[1302],[]
...,...,...,...,...,...,...,...,...
1436,3676,"The text discusses crime rates, police officer...",[1200],"[1200, 1202, 1209]",[1202],"Well, of course, as I've already outlined, as ...",[1202],[]
1437,3681,The excerpt mentions government spending ineff...,"[100, 200]","[100, 105, 200, 201]",[201],"What I would say is, for example, the Dome was...",[201],[]
1438,3682,The excerpt discusses the state of the NHS and...,"[100, 300]","[100, 107, 300, 325]",[325],"Terry, like so many people around the country,...",[325],[]
1439,3684,The excerpt expresses regret for causing harm ...,[1600],"[1600, 1609]",[1609],"Yeah, I was incredibly sad to have caused peop...",[1609],[]
1440,3686,The text discusses the issue of people using p...,"[100, 1300]","[100, 108, 1300, 1302]","[108, 1302]",There are lots of people who go for private he...,"[108, 1302]",[]

In [101]:
df_tier_2_cleaned['claim_labels'] = df_tier_2_cleaned['claim_labels'].apply(fix_hierarchy)
inconsistent_count = df_tier_2_cleaned['claim_labels'].apply(check_inconsistency).sum()
print(f"Remaining inconsistent rows: {inconsistent_count}")

Remaining inconsistent rows: 0

In [102]:
df_tier_2_cleaned

,id,reasoning,supercategories,claim_labels,watch_labels,text,parsed_watch
0,344,The excerpt discusses economic policy choices ...,"[100, 300]","[100, 105]","[105, 301]",Ed Miliband. You've heard tonight from five di...,"[105, 301]"
2,352,"The excerpt discusses the current tax burden, ...","[100, 1300]","[100, 105]",[105],"Well, the first thing I'd say is the Tories ar...",[105]
3,362,"The excerpt discusses taxation, public spendin...","[100, 300]","[100, 105, 300, 301]","[105, 301]","Well, in relation to taxation, I do need to be...","[105, 301]"
4,366,The excerpt discusses the economic policies of...,[100],"[100, 105]",[105],I don't say there is no difference between Ed ...,[105]
6,370,"The excerpt discusses Brexit, a people's vote,...","[1900, 2000]","[2000, 2012]",[2012],Thank you. Sian Berry. I understand completely...,[2012]
...,...,...,...,...,...,...,...
886,3667,The excerpt discusses government spending cuts...,[100],"[100, 105]",[105],"Well, Geoffrey, first of all, austerity Tory a...",[105]
887,3668,The excerpt discusses a proposed local tax sys...,[100],"[100, 105]",[105],"Well, if you have a household income in the re...",[105]
888,3674,The text expresses frustration with the politi...,[2000],"[2000, 2012]",[2012],"Well, listening to Richard and Rishi, frankly,...",[2012]
891,3680,The excerpt discusses the NHS budget and its r...,"[100, 300]","[300, 301]","[105, 301]","The point is, we have made a special exception...","[105, 301]"
892,3683,The excerpt discusses the National Health Serv...,"[300, 100]","[100, 105, 300, 301]","[105, 301]","Nigel Farage. Well, I mean, the fact that ther...","[105, 301]"

In [103]:
combined_df = pd.concat([
    df_tier_1[['text', 'claim_labels']],
    df_tier_2_cleaned[['text', 'claim_labels']],
    df_tier_3[['text', 'claim_labels']]
], ignore_index=True)
combined_df.to_csv('final_labels_stage_2.csv', index=False)

print(f"Dataset compiled: {len(combined_df)} rows.")

Dataset compiled: 2869 rows.

In [104]:
train_df = combined_df.copy()
train_df

,text,claim_labels
0,"Of course, we have to improve the system, but ...","[200, 230]"
1,I think this is partly what's been going wrong...,"[200, 230]"
2,Or you could actually take the view that I'm n...,[]
3,But then you'll ignore the result. No.,[]
4,No. I want to be a member of the European Unio...,"[1900, 1910]"
...,...,...
2864,"Well, of course, as I've already outlined, as ...","[1200, 1202, 1209]"
2865,"What I would say is, for example, the Dome was...","[100, 105, 200, 201]"
2866,"Terry, like so many people around the country,...","[100, 107, 300, 325]"
2867,"Yeah, I was incredibly sad to have caused peop...","[1600, 1609]"
2868,There are lots of people who go for private he...,"[100, 108, 1300, 1302]"

In [3]:
test_df = df_human.drop(columns=['id'])
test_df

,Text,claim_labels
0,"So knife crime's going to go up, because the e...","[1200, 1211]"
1,Of course Gordon Brown's right to say there's ...,"[100, 107, 1300, 1302, 600, 602, 603, 1200, 1208]"
2,"You won't admit the truth, will you? The truth...",[]
3,"I tell you how we pay for it. We would, for in...","[100, 107]"
4,"You just, look, there's no point in speculatin...",[]
...,...,...
364,I think the lady makes a very important point....,"[100, 103, 1200, 1207, 1900, 1910, 500, 506]"
365,I've met some of the people who have rightly c...,"[1200, 1207]"
366,"Well, I share the frustration of both our ques...","[1900, 1910, 400, 406, 200, 202, 230]"
367,You're saying people voted for 10% tariffs on ...,"[1000, 1006]"
368,I think this question of enthusiasm is really ...,"[2000, 2032, 1200, 1208]"

In [4]:
test_df.rename(columns={'Text': 'text'}, inplace=True)
test_df

,text,claim_labels
0,"So knife crime's going to go up, because the e...","[1200, 1211]"
1,Of course Gordon Brown's right to say there's ...,"[100, 107, 1300, 1302, 600, 602, 603, 1200, 1208]"
2,"You won't admit the truth, will you? The truth...",[]
3,"I tell you how we pay for it. We would, for in...","[100, 107]"
4,"You just, look, there's no point in speculatin...",[]
...,...,...
364,I think the lady makes a very important point....,"[100, 103, 1200, 1207, 1900, 1910, 500, 506]"
365,I've met some of the people who have rightly c...,"[1200, 1207]"
366,"Well, I share the frustration of both our ques...","[1900, 1910, 400, 406, 200, 202, 230]"
367,You're saying people voted for 10% tariffs on ...,"[1000, 1006]"
368,I think this question of enthusiasm is really ...,"[2000, 2032, 1200, 1208]"

In [5]:
test_df.to_csv('test_df.csv')

In [107]:
train_df.to_csv('train_df.csv')

In [114]:
train_df = pd.read_csv('train_df.csv', index_col=0)

In [115]:
def safe_parse_to_int(val):
    if pd.isna(val): return []
    if isinstance(val, (list, tuple, np.ndarray)):
        return [int(x) for x in val]
    
    s = str(val).strip()
    if s == "" or s == "[]": return []
    
    try:
        res = ast.literal_eval(s)
        if isinstance(res, (list, tuple)):
            return [int(x) for x in res]
        return [int(res)]
    except:
        return [int(x.strip()) for x in s.replace('[', '').replace(']', '').split(',') if x.strip().isdigit()]

In [116]:
train_df['claim_labels'] = train_df['claim_labels'].apply(safe_parse_to_int)

In [117]:
print(type(train_df['claim_labels'].iloc[0]))

<class 'list'>

In [125]:
all_codes = set()
for labels in train_df['claim_labels']:
    all_codes.update(labels)
for labels in test_df['claim_labels']:
    all_codes.update(labels)
sorted_codes = sorted(list(all_codes))

In [126]:
mlb = MultiLabelBinarizer(classes=sorted_codes)
binary_data = mlb.fit_transform(train_df['claim_labels'])
train_csv = pd.DataFrame(binary_data, columns=sorted_codes)
train_csv.insert(0, 'input', train_df['text'])
train_csv.to_csv('train.csv', index=False)

In [127]:
mlb = MultiLabelBinarizer(classes=sorted_codes)
binary_data = mlb.fit_transform(test_df['claim_labels'])
test_csv = pd.DataFrame(binary_data, columns=sorted_codes)
test_csv.insert(0, 'input', test_df['text'])
test_csv.to_csv('test.csv', index=False)

In [129]:
train_df

,text,claim_labels
0,"Of course, we have to improve the system, but ...","[200, 230]"
1,I think this is partly what's been going wrong...,"[200, 230]"
2,Or you could actually take the view that I'm n...,[]
3,But then you'll ignore the result. No.,[]
4,No. I want to be a member of the European Unio...,"[1900, 1910]"
...,...,...
2864,"Well, of course, as I've already outlined, as ...","[1200, 1202, 1209]"
2865,"What I would say is, for example, the Dome was...","[100, 105, 200, 201]"
2866,"Terry, like so many people around the country,...","[100, 107, 300, 325]"
2867,"Yeah, I was incredibly sad to have caused peop...","[1600, 1609]"
2868,There are lots of people who go for private he...,"[100, 108, 1300, 1302]"

In [130]:
test_df

,text,claim_labels
0,"So knife crime's going to go up, because the e...","[1200, 1211]"
1,Of course Gordon Brown's right to say there's ...,"[100, 107, 1300, 1302, 600, 602, 603, 1200, 1208]"
2,"You won't admit the truth, will you? The truth...",[]
3,"I tell you how we pay for it. We would, for in...","[100, 107]"
4,"You just, look, there's no point in speculatin...",[]
...,...,...
364,I think the lady makes a very important point....,"[100, 103, 1200, 1207, 1900, 1910, 500, 506]"
365,I've met some of the people who have rightly c...,"[1200, 1207]"
366,"Well, I share the frustration of both our ques...","[1900, 1910, 400, 406, 200, 202, 230]"
367,You're saying people voted for 10% tariffs on ...,"[1000, 1006]"
368,I think this question of enthusiasm is really ...,"[2000, 2032, 1200, 1208]"

TypeError: can only concatenate str (not "list") to str