In [2]:
import pandas as pd
import re
import ast
import numpy as np
from itertools import groupby

---

I need, for every debate, the list of turns for each candidate

In [169]:
# import the json files for turns, and copy the find_debates method

with open('../../exploratory_analysis/grouped_sep_raw.json', 'r') as f:
    grouped_sep_raw_data = f.read()
grouped_sep_raw = json.loads(grouped_sep_raw_data)
with open('../../exploratory_analysis/raw_debates.json', 'r') as f:
    raw_debates_data = f.read()
raw_debates=json.loads(raw_debates_data)    
with open('../../exploratory_analysis/sep_raw_debates.json', 'r') as f:
    sep_raw_debates_data = f.read()
sep_raw_debates=json.loads(sep_raw_debates_data)
with open('../../exploratory_analysis/sep_proc_debates.json', 'r') as f:
    sep_proc_debates_data = f.read()
sep_proc_debates = json.loads(sep_proc_debates_data)    
with open('../../exploratory_analysis/grouped_sep_proc.json', 'r') as f:
    grouped_sep_proc_data = f.read()
grouped_sep_proc = json.loads(grouped_sep_proc_data)
with open('../../exploratory_analysis/comb_raw_debates.json', 'r') as f:
    comb_raw_debates_data = f.read()
comb_raw_debates = json.loads(comb_raw_debates_data)
with open('../../exploratory_analysis/comb_proc_debates.json', 'r') as f:
    comb_proc_debates_data = f.read()    
comb_proc_debates = json.loads(grouped_sep_raw_data)

In [5]:
def find_debate(deb, structure, processing, grouping, person=None):  
    '''
    Easily find pre-processed debate transcript text in desired format
    deb - name of debate from options
    structure - 'separate'(each speaker) / 'combined'(all speakers)
    processing - 'proc'(pre-processing applied) / 'raw'(raw content)
    grouping - 'grouped'(all speaker turns combined) / 'turns'(separated into speaker turns)
    person - name of speaker in debate
    '''
    if structure == 'separate':
        #use sep and grouped dicts
        if grouping == 'turns':
            #use sep dicts
            if processing == 'proc':
                if person != None:                    
                    if person in participants[deb]:
                        return sep_proc_debates[deb][person]
                    else:                        
                        print("Invalid 'person' param. Non-participant in debate")
                        return
                else:                    
                    return sep_proc_debates[deb]
            elif processing == 'raw':
                if person != None:
                    if person in participants[deb]:
                        return sep_raw_debates[deb][person]
                    else:
                        print("Invalid 'person' param. Non-participant in debate")
                        return
                else:                    
                    return sep_raw_debates[deb]
            else:
                print("Invalid 'processing' param. Use options given in docstring")
                return
        elif grouping == 'grouped':
            #use grouped dicts
            if processing == 'proc':
                if person != None:
                    if person in participants[deb]:
                        return grouped_sep_proc[deb][person]
                    else:
                        print("Invalid 'person' param. Non-participant in debate")
                        return
                else:                    
                    return grouped_sep_proc[deb]
            elif processing == 'raw':
                if person != None:
                    if person in participants[deb]:
                        return grouped_sep_raw[deb][person]
                    else:
                        print("Invalid 'person' param. Non-participant in debate")
                        return
                else:                    
                    return grouped_sep_raw[deb]
            else:
                print("Invalid 'processing' param. Use options given in docstring")
                return
        else:
            print("Invalid 'grouping' param. Use options given in docstring")
            return
    elif structure == 'combined':
        #use comb dicts
        if processing == 'proc':
            return comb_proc_debates[deb]
        elif processing == 'raw':
            return comb_raw_debates[deb]
        else:
            print("Invalid 'processing' param. Use options given in docstring")
            return
    else:
        print("Invalid 'structure' param. Use options given in docstring")
        return

In [6]:
deb_options = ['deb_2005_04_18',
 'deb_2005_04_20',
 'deb_2005_04_22',
 'deb_2005_04_28',
 'deb_2010_04_15',
 'deb_2010_04_22',
 'deb_2010_04_29',
 'deb_2015_03_26',
 'deb_2015_04_02',
 'deb_2015_04_16',
 'deb_2015_04_30',
 'deb_2017_05_18',
 'deb_2017_05_29',
 'deb_2017_05_31',
 'deb_2017_06_02',
 'deb_2017_06_05',
 'deb_2017_06_06',
 'deb_2019_11_19',
 'deb_2019_11_22',
 'deb_2019_11_28',
 'deb_2019_11_29',
 'deb_2019_12_01',
 'deb_2019_12_06',
 'deb_2019_12_09',
 'deb_2024_06_04',
 'deb_2024_06_04_01',
 'deb_2024_06_07',
 'deb_2024_06_12',
 'deb_2024_06_13',
 'deb_2024_06_18',
 'deb_2024_06_20',
 'deb_2024_06_24',
 'deb_2024_06_26']

In [11]:
with open('../../transcription/data/debate_participants.json', 'r') as f:
    participants_data = f.read()
participants = json.loads(participants_data)
participants

{'deb_2005_04_18': ['KENNEDY'],
 'deb_2005_04_20': ['BLAIR'],
 'deb_2005_04_22': ['HOWARD'],
 'deb_2005_04_28': ['KENNEDY', 'HOWARD', 'BLAIR'],
 'deb_2010_04_15': ['CLEGG', 'CAMERON', 'BROWN'],
 'deb_2010_04_22': ['CLEGG', 'CAMERON', 'BROWN'],
 'deb_2010_04_29': ['CAMERON', 'CLEGG', 'BROWN'],
 'deb_2015_03_26': ['CAMERON', 'MILIBAND'],
 'deb_2015_04_02': ['BENNETT',
  'CLEGG',
  'FARAGE',
  'MILIBAND',
  'WOOD',
  'STURGEON',
  'CAMERON'],
 'deb_2015_04_16': ['WOOD', 'FARAGE', 'MILIBAND', 'STURGEON', 'BENNETT'],
 'deb_2015_04_30': ['CAMERON', 'MILIBAND', 'CLEGG'],
 'deb_2017_05_18': ['LUCAS', 'WOOD', 'STURGEON', 'NUTTALL', 'FARRON'],
 'deb_2017_05_29': ['CORBYN', 'MAY'],
 'deb_2017_05_31': ['WOOD',
  'LUCAS',
  'RUDD',
  'CORBYN',
  'NUTTALL',
  'ROBERTSON',
  'FARRON'],
 'deb_2017_06_02': ['MAY', 'CORBYN'],
 'deb_2017_06_05': ['FARRON', 'STURGEON'],
 'deb_2017_06_06': ['ZAHAWI',
  'CHAMPION',
  'FORBES',
  'KURTEN',
  'PADDOCK',
  'ELIN',
  'BARTLEY'],
 'deb_2019_11_19': ['JOHNSON', 'CORBYN'],
 'deb_2019_11_22': ['CORBYN', 'STURGEON', 'SWINSON', 'JOHNSON'],
 'deb_2019_11_28': ['BERRY', 'CORBYN', 'PRICE', 'STURGEON', 'SWINSON'],
 'deb_2019_11_29': ['SWINSON',
  'STURGEON',
  'TICE',
  'SUNAK',
  'LONG-BAILEY',
  'LUCAS',
  'PRICE'],
 'deb_2019_12_01': ['SWINSON',
  'FARAGE',
  'BURGON',
  'SUNAK',
  'BERRY',
  'PRICE',
  'STURGEON'],
 'deb_2019_12_06': ['JOHNSON', 'CORBYN'],
 'deb_2019_12_09': ['JENRICK',
  'FARAGE',
  'RAYNER',
  'YOUSAF',
  'SWINSON',
  'PRICE',
  'BARTLEY'],
 'deb_2024_06_04': ['SUNAK', 'STARMER'],
 'deb_2024_06_04_01': ['DAVEY', 'FLYNN', 'TICE', 'RAMSAY'],
 'deb_2024_06_07': ['MORDAUNT',
  'FARAGE',
  'RAYNER',
  'IORWERTH',
  'DENYER',
  'COOPER',
  'FLYNN'],
 'deb_2024_06_12': ['SUNAK', 'STARMER'],
 'deb_2024_06_13': ['RAYNER',
  'COOPER',
  'MORDAUNT',
  'DENYER',
  'FARAGE',
  'FLYNN',
  'IORWERTH'],
 'deb_2024_06_18': ['PHILP',
  'THOMAS-SYMONDS',
  'COOPER',
  'TICE',
  'DENYER',
  'BROWN',
  'IORWERTH'],
 'deb_2024_06_20': ['DAVEY', 'SWINNEY', 'STARMER', 'SUNAK'],
 'deb_2024_06_24': ['SUNAK', 'STARMER'],
 'deb_2024_06_26': ['SUNAK', 'STARMER']}

In [12]:
find_debate('deb_2024_06_04', 'separate', 'raw', 'turns', 'SUNAK')

["Uncertain times call for a clear plan and bold action. So I'll keep this simple. In five weeks, either Keir Starmer or I will be Prime Minister. Beyond raising your taxes and raiding your pensions, no-one knows what Labour would actually do. But you know what I would do? I'll cut your taxes, protect your pension, and reduce immigration. I have a clear plan for a more secure future for you and your family.",
 "Well, Paula, I know how much of a strain the last few years have put on your family finances, the family finances of everyone in our country. And that's why my priority has always been to do what I can to support you. That started with bold action, like the furlough scheme during the pandemic, and more recently, my clear plan to bring inflation back to normal. And now, our economy is growing again, wages are rising, and crucially, we are able to now start cutting your taxes. But I know you're only just starting to see the benefits of that, as you described. So the choice at this election is with my clear plan and bold action to keep cutting your taxes to give you financial security, or put all that progress at risk with higher taxes, £2,000 worth of higher taxes under the Labour Party.",
 "I think it's slightly ironic, because from the moment I got this job, Keir Starmer was telling me, call an election, call an election. And now that we've called an election, he's saying, oh, no, don't have an election, because I don't want to tell you what I'm going to do. And this is the choice for everybody. The plan is working, of course I know. Everyone is only just starting to feel the benefits of it, but inflation is back to normal, wages are growing, taxes are now being cut. Keir Starmer would put all that progress at risk. He would put up everyone's taxes by £2,000. £2,000 in higher taxes for every working family in our country after all the hard work and sacrifice we've been through. That's not the right course of action. I don't know why you want to put up people's taxes.",
 "If people are struggling with their bills, why do you want to make it harder for them by saddling them with £2,000 worth of higher taxes? How is that going to make Paula or anyone's life easier? Could you respond directly to Rishi Sunak?",
 "I know you're going to hear a lot about the past. in this election, but this election is about the future. This election is about the future and I'm clear that I'm going to keep cutting people's taxes as we now are. You want to put everyone's taxes up by £2,000 and this is really important. Independent Treasury officials have costed Labour's policies and they amount to a £2,000 tax rise. Mark my words, Labour will raise your taxes, it's in their DNA, your work, your car, your pension, you name it, Labour will tax it.",
 "Well, I'd ask everyone to judge me by my actions. You saw what I did during the pandemic. When disaster struck our country, I implemented the furlough scheme because I knew the devastating impact it would have on people. And you know what? Every week when I'm out and about, someone comes up to me and tells me how furlough saved their family, saved their home, because that's who I am. And I don't want to put that progress at risk. I want to keep delivering financial security by cutting people's taxes. Thank you. Whereas the Labour Party want to keep putting people's taxes up, and that's not going to help anyone overcome the challenges they're facing.",
 "Because this election is about the future and making people's lives better. Now, I've got a clear plan to ease those anxieties that Paula and everyone is facing. Because things are tough, I want to make them easier by continuing to cut your taxes. The difference of this election is Keir Starmer is going to put your taxes up by £2,000. Thank you. So if people are worried about their electricity bill, their food bill, taking their kids on a holiday, £2,000 worth of tax rises are not going to help with any of those things. I'll ask again, why do you want to put everyone's taxes up?",
 "Well, Janet, thank you for sharing your story. And I'm glad that you've recovered. And I'm sorry for your loss as well. Now, my dad was a GP. My mum was a pharmacist. So I'm speaking as someone who was brought up in the NHS, surrounded by people who dedicated their lives to it. And the evenings in my house, growing up, my parents spoke about how they could provide more care for their patients, like you. And that's how I think about the NHS. And of course it's difficult, and you're right, and we have to be honest. about the damage that Covid has done and the time it will take to recover from that. But we've put record funding in, we're training more doctors and nurses, we're doing more checks and scans, and what I want you to know is that the NHS is safe in my hands. I will always stand up for it to give you and everyone else the peace of mind that it will be there for you and your families when you need it.",
 "As Janet knows, and everyone knows, the NHS is still recovering from COVID. We went through the best part of two years where the NHS couldn't conduct all the treatments it normally would. And it is going to take time to recover from that. But we are now making progress. The waiting lists are coming down. But what Keir Starmer didn't mention to you, which you did, Julie...",
 'Yeah, they are now coming down. They are now coming down.',
 'Because they were coming down from where they were when they were hired.',
 "And they're now on their way down. They are down. Yes, because the NHS was impacted by industrial action. And if it wasn't for that, half a million appointments would have been saved. So it's somebody else's fault. No, no. But let me address the question, because as you said, Julie, the NHS is devolved. So different parties are responsible for the NHS in different parts of the United Kingdom. Keir Starmer's party are responsible for it in Wales. Now, the NHS has been impacted by COVID everywhere. But things are difficult in England, I know that. But if you were in Wales, you would be waiting 40% longer for treatment. Ambulance and A&E times are the worst in Great Britain, and one in four people are on a waiting list. So yes, the NHS has challenges, but it has challenges everywhere regardless of the party that's in charge.",
 "I'm really grateful for everyone in the NHS for working so hard and we have now settled pay rises with everyone in the NHS except for the junior doctors and of course I want to do that to make sure it's fair and affordable though but despite being offered the most generous pay settlement anywhere in the NHS and indeed the public sector the Union are demanding a 35% pay rise and I don't want to raise your taxes to pay for that because I don't think it's right but I will say this So when Keir Starmer says he'll resolve it, he hasn't explained to you how, but I will say this... OK, perhaps you can answer that, Keir Starmer.",
 'So what would you do?',
 "So you're not going to give them the 35% pay rise that they're asking for, so how would you resolve it? Just standing there and saying, I'll resolve it, isn't an answer. That's not a plan. Prime Minister... How would you resolve it? Prime Minister, your record is... Well, no, no, how would you resolve it? You want to be Prime Minister. How would you resolve the strike? How would you resolve them?",
 "Yes, well, we've already implemented charging reform. Pilots are in place to implement the reforms. They will be rolled out later this year.",
 "We've already given social care an extra $8 billion because the pressures are immediate. And the pilot reforms are there for charging.",
 "because it is important, because there's no way to get Janet and everyone else the care they need without a workforce. OK. But the British Medical Association... All right, thank you. ..has warned that Keir Starmer's pension tax... OK. ..risks an exodus of doctors. We're talking about doctors from the NHS. OK, we are going to... Gentlemen, please. Gentlemen, actually... It's all joined up.",
 "Yes, well, I think education is the most powerful way that you can transform people's lives. That was something that my parents raised me with, and I'm grateful to all our teachers for what they're doing, which is why we're backing our schools with record investment at the moment, but also reforming how we teach our kids, which is why I'm proud that, right now, English schoolchildren are the best readers anywhere in the Western world, and that is testament to the hard work of teachers and the reforms of this Conservative government.",
 "I don't agree with it, because I think people who work hard and aspire to provide that education for their kids should have that freedom. That's what my parents did, and I'll support it. But you heard it. Keir Starmer is going to raise taxes. But that's just the start, because there's a long list of other things that he needs to find the money for. So it's not just going to start and stop there. There are £2,000 worth of tax rises coming for every working family in this country. And as I said, he's saying to you he's going to raise taxes.",
 "Yes, well, we have already scrapped the Nondon regime and we have a £0.75 tax on energy companies, but independent Treasury civil servants have costed Labour's policies and it's £2,000. But you asked for specifics, Julie, so let's have a specific difference.",
 "The Triple Lock Plus, so that we raise the personal allowance for pensioners and ensure that the state pension is never subject to tax. That's all you'll get under a future Conservative government. Keir Starmer hasn't matched that pledge, which means for the first time in our country's history, if Labour are elected, pensioners will pay tax. I do not think that is right, and you should explain to everyone why you think pensioners will be paying a retirement tax under your government.",
 "Thank you, not over each other. Thank you, not over each other. We've committed to the Triple Lock Plus. Under us, the state pension will never pay tax. Under you, there's a retirements tax coming for British pensioners. I think it's appalling. Explain to people why pensioners should pay tax on the state pension.",
 "You asked about it. It's very clear, pensioners under Keir Starmer will pay tax on the state pension for the first time in our country's history. It is a retirement tax and Keir Starmer can talk about the past all he wants but in the future pensioners have got a tax rise coming under your government. Why do you want to put up their taxes?",
 "We're going to continue investing record sums in public services.",
 "Stephen, immigration is too high, and we will need to take bold action to bring it down, whether that's legal migration, where we're going to introduce a new legal cap to guarantee that it will come down every year, or the boats, which you mentioned, where we got the numbers down last year by a third, and now we have a deterrent ready to go. Migrants have been detained, the flights will go in July, but only if I'm your Prime Minister. If Keir Starmer's elected, All those people will be released, the flights will be cancelled and we will have no deterrent to stop the unfairness of people crossing in boats. So that's the choice for you at this election. Stick to our plan and illegal migrants will be on those planes. With Labour, they will be out on our streets.",
 "Over the last 12 months, the number of crossings have down a third because the plans we've put in place are starting to make a difference. But the choice of this election is about the future. I believe you need to have a deterrent. The only way to stop this problem is to say to people who come here illegally, they cannot stay and they will be removed. If I'm your Prime Minister, the planes will go to Rwanda, we will have a deterrent. So the simple question for Keir Starmer is, what will you do with people who come here illegally?",
 "Very simply, what will you do with them? That's what I'm going to do. We'll have a deterrent.",
 "Phil, Keir Starmer said, smash the gangs. We put new laws in Parliament that have now led to almost 1,000 criminals and people smugglers being arrested, serving hundreds of years in jail. Because we do need to smash the gangs. Keir Starmer voted against those laws. So as ever, you say one thing here, but your track record says something completely different, and you can't be trusted to tackle immigration.",
 'Because this is a challenge.',
 "This is a growing challenge, but I've got a plan to deal with it, because I'm going to put people on planes. What are you going to do with them? I can tell everyone what I'm going to do. You might not like it, but I've got a plan, because we've got to have a deterrent. What are you going to do? Just tell everybody. What are you going to do with illegal migrants who arrive?",
 "I've been crystal clear. I believe all our plans are compliant with our international obligations, but if I am forced to choose between securing our borders and our country's security or a foreign court, I'm going to choose our country's security every single time.",
 "I've been crystal clear. I will choose our country's security ahead of membership of a foreign court every single time.",
 "Of course we should have safe routes. But when we've controlled our borders, we will be able to have a conversation about the right number to accept. We've been a very generous, compassionate country. But we talk about European conventions. Thank you. 20 European countries almost now have agreed with my approach. Believe that you need to be able to return people to a safe country, otherwise you can't solve this problem. We still haven't heard from Keir Starmer and this is meant to be a debate about the future. I will put people on planes to create that deterrent. Multiple other European countries agree with that. What will you do with illegal migrants who come here? What will you do with them?",
 'I thought we were not going to talk over each other. So you do now agree with third-country deals?',
 "Yes, Omar, it's an awful situation. And I'm pleased, actually, that Keir Starmer supported, alongside me, Israel's right to defend itself in the face of the atrocious attack that they suffered. But right now, you're seeing that US have put a deal on the table, which we strongly support, together with our allies, to bring an immediate end to the hostilities, release hostages, get more aid in, and then build towards a lasting settlement with a two-state solution. We've led in providing more aid to Gaza, something I'm proud that we've done. Our troops have helped build the port that's being established. But more generally, the world is a more uncertain place. What Hamas is doing is indicative of the dangers we face, which is why I've made the bold decision also to lead, to increase investment in our country's defence, because I think that's necessary to keep you safe, everyone safe. It's something that the Labour Party have not matched.",
 "I don't think the Labour Party can be trusted to keep this country as safe as the Conservatives. The world is a more dangerous and uncertain place than at any point since the end of the Cold War. I've made the decision to invest more in our defence, taking it up to 2.5% of GDP. Labour Party have not matched that. And worse than that, the person who would be Deputy Prime Minister under Keir Starmer does not believe in our nuclear deterrent, the ultimate guarantor of our security. So no, you can trust the Conservatives with our country's security, and my track record and our commitments prove that.",
 'This is shocking.',
 "I'd have rather had my job than work for extremists like Abu Qatada and Hizb ut-Tahrir.",
 "No, no, Abu Qatada and Hizb ut-Tahrir are who you work for as well, so people can Google that and have a look. But there's a clear choice. Desperate. I'm investing more in our country's defence, up to 2.5% of GDP. OK. You are not doing that. So how can you tell people you will keep them safe when you're not willing to invest more in our country's security? Thank you.",
 'Yes, because having a strong relationship with our closest partner and ally in the United States is critical for keeping everyone in our country safe.',
 "Well Clare, I have two young girls and this is what they talk to me about more than anything else. And of course we're going to tackle climate change and get to net zero. This election is about how we do it. And I don't think that British people should solve a global problem all by themselves, which is why I'm also prioritising our country's energy security, and your bills. We've heard a lot about the cost of living challenges today. So I have made some decisions, bold decisions, that will mean that we can save all of you thousands of pounds, still meet our targets, and we can ensure our country's energy security. The contrast is clear at this election, because Keir Starmer will reverse all of the changes I've made. That's going to cost everyone and you thousands of pounds and make our country less energy secure by banning North Sea energy. And that, I don't think, is the right course for our country.",
 "No, we're going to stick to the targets we've put in place, but we're going to do it in a way that saves you all money. I'm not going to impose thousands of pounds of costs on you to arbitrarily rip out your boiler, change your car, convert your home. When we've been talking about the cost of living challenges earlier in this debate, I don't think adding thousands of pounds of costs to you is the right thing. Now, Keir Starmer is going to reverse those changes that I made. So everyone is facing thousands of pounds of higher bills. That is the choice at this election.",
 "So it's completely head in the sand stuff. Keir Starmer's going to reverse the changes I made. To install a heat pump now, if you don't need to, costs about £7,000 or £10,000. To convert your home, again, if you're in a terraced house in Darlington, £10,000. Changing your car sooner than America, Canada, Sweden, France, Germany, as he wants you to do, thousands of pounds. OK, let Keir Starmer respond... There's a simple choice at this election. Thank you. If you think Labour are going to win, start saving.",
 "Anyone can go online when they get home. Go and see how much it will cost to convert your home. Go and see how much it will cost to install the heat pump. Go and see how much it will cost to change your car. Those are all the things that he's going to force you to do sooner than is necessary. You can go and see tonight the thousands of pounds that's going to cost you. I said it before, I'll say it again. He is going to put up your taxes, put up your bills as clear as night follows day.",
 "You know, we have an enormous amount to be proud of as a country, but we do need to do more to make sure our young people, like you, Miles, get the opportunities that they deserve. So that's why we will introduce a modern form of national service. And I think it's going to be transformational for young people in our country, giving them the skills. and opportunities they need to succeed in life, fostering a culture of service in our society, bringing it together, but also strengthening our resilience and security for the future. And I think it is going to be something that's incredibly positive. But beyond that, I want you to have financial security. So when you get that job, when you save for that house, we make it easier, which is why I want to keep cutting your taxes so you can keep more of your money, build for a deposit for that first house, and not saddle you with £2,000 of higher taxes.",

In [15]:
df_labels = pd.read_csv("../Identifying Topics/final_labels_stage_1.csv")
df_labels

,id,reasoning,supercategories,claim_labels
0,344,The excerpt discusses economic policy choices ...,"[100, 300]","[100, 105, 300, 301]"
1,345,"The excerpt discusses immigration policy, incl...",[200],"[200, 230]"
2,346,The excerpt discusses the need for increased f...,"[100, 1300]","[100, 105, 107, 1300, 1302]"
3,347,The excerpt discusses the release of a terrori...,"[1200, 1600]","[1200, 1205, 1600, 1627]"
4,348,The text discusses the financial implications ...,"[1900, 100]","[1900, 1910, 100, 105]"
...,...,...,...,...
3314,3683,The excerpt discusses the National Health Serv...,"[300, 100]","[300, 100, 301, 105]"
3315,3684,The excerpt expresses regret for causing harm ...,[1600],"[1600, 1609]"
3316,3685,The excerpt discusses a change in someone's op...,[],[]
3317,3686,The text discusses the issue of people using p...,"[100, 1300]","[100, 108, 1300, 1302]"
3318,3687,The text discusses tuition fees and implies a ...,[600],"[600, 601]"

In [18]:
def create_debate_dataframe(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
        
    pattern = r'^(\d+)\n(.*?)(?=\n\d+\n|\Z)'

    matches = re.findall(pattern, content, re.DOTALL | re.MULTILINE)

    df = pd.DataFrame(matches, columns=['id', 'text'])
    
    df['text'] = df['text'].str.strip()
    
    df['id'] = df['id'].astype(int)
    
    return df

In [24]:
val_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 351, 361, 388, 394, 404, 416, 429, 432, 447, 455, 484, 624, 628, 671, 737, 748, 998, 1222, 1361, 1420, 1426, 1756, 2601, 3070, 3356]

df_turns = create_debate_dataframe('../Identifying Topics/all_turns_shuffled.txt')
df_turns = df_turns[~df_turns['id'].isin(val_list)]
train_df = df_labels.merge(df_turns[['id', 'text']], on='id', how='left')
train_df = train_df.drop(columns=['id', 'reasoning', 'supercategories'])
train_df

,claim_labels,text
0,"[100, 105, 300, 301]",Ed Miliband. You've heard tonight from five di...
1,"[200, 230]","Of course, we have to improve the system, but ..."
2,"[100, 105, 107, 1300, 1302]","I've never been called timid in my life, but c..."
3,"[1200, 1205, 1600, 1627]","Well, Darren, in answer to your question, obvi..."
4,"[1900, 1910, 100, 105]",It isn't a question of what it's worth paying ...
...,...,...
3314,"[300, 100, 301, 105]","Nigel Farage. Well, I mean, the fact that ther..."
3315,"[1600, 1609]","Yeah, I was incredibly sad to have caused peop..."
3316,[],"...that he wasn't originally in favour, er, he..."
3317,"[100, 108, 1300, 1302]",There are lots of people who go for private he...
3318,"[600, 601]","And it wasn't tripled, and we didn't triple tu..."

In [17]:
test_df = pd.read_csv('../Identifying Topics/test_df.csv', index_col=0)
test_df

,text,claim_labels
0,"So knife crime's going to go up, because the e...","[1200, 1211]"
1,Of course Gordon Brown's right to say there's ...,"[100, 107, 1300, 1302, 600, 602, 603, 1200, 1208]"
2,"You won't admit the truth, will you? The truth...",[]
3,"I tell you how we pay for it. We would, for in...","[100, 107]"
4,"You just, look, there's no point in speculatin...",[]
...,...,...
364,I think the lady makes a very important point....,"[100, 103, 1200, 1207, 1900, 1910, 500, 506]"
365,I've met some of the people who have rightly c...,"[1200, 1207]"
366,"Well, I share the frustration of both our ques...","[1900, 1910, 400, 406, 200, 202, 230]"
367,You're saying people voted for 10% tariffs on ...,"[1000, 1006]"
368,I think this question of enthusiasm is really ...,"[2000, 2032, 1200, 1208]"

In [26]:
topics_df = pd.concat([test_df, train_df], axis=0)
topics_df

,text,claim_labels
0,"So knife crime's going to go up, because the e...","[1200, 1211]"
1,Of course Gordon Brown's right to say there's ...,"[100, 107, 1300, 1302, 600, 602, 603, 1200, 1208]"
2,"You won't admit the truth, will you? The truth...",[]
3,"I tell you how we pay for it. We would, for in...","[100, 107]"
4,"You just, look, there's no point in speculatin...",[]
...,...,...
3314,"Nigel Farage. Well, I mean, the fact that ther...","[300, 100, 301, 105]"
3315,"Yeah, I was incredibly sad to have caused peop...","[1600, 1609]"
3316,"...that he wasn't originally in favour, er, he...",[]
3317,There are lots of people who go for private he...,"[100, 108, 1300, 1302]"
3318,"And it wasn't tripled, and we didn't triple tu...","[600, 601]"

In [27]:
topics_df.to_csv('topics_df.csv')

In [41]:
find_debate('deb_2024_06_04', 'separate', 'raw', 'turns', 'SUNAK')[0]

"Uncertain times call for a clear plan and bold action. So I'll keep this simple. In five weeks, either Keir Starmer or I will be Prime Minister. Beyond raising your taxes and raiding your pensions, no-one knows what Labour would actually do. But you know what I would do? I'll cut your taxes, protect your pension, and reduce immigration. I have a clear plan for a more secure future for you and your family."

In [36]:
ast.literal_eval(topics_df.loc[x.cont(topics_df['text']), 'claim_labels'].values[0])

AttributeError: 'str' object has no attribute 'isin'

Metrics:  
* Proportion of turns on topic
* Proportion of words on topic
* Average length of turns on topic (mean words per turn)
* Rank of topic by turns
* Rank of topic by words
* Lexical diversity when discussing topic(TTR or MSTTR)
    * not used because of extremely different text lengths
* Sentiment when discussing topic t

In [ ]:
find_debate(deb, 'separate', 'raw', 'turns', candidate)

In [185]:
# creating a dataframe of 'topic focus metrics'
topic_focus_metrics =  []

debates = []
candidates = []
all_topics = []

# proportion of turns on topic = no of turns with that topic / total no of turns
prop_turns = []

In [223]:
topic_focus_metrics =  []
for deb in deb_options:    
    for candidate in participants[deb]:
        no_of_turns = 0
        turns_per_topic = {}
        
        total_word_count = 0
        words_per_topic = {}
        lengths_per_topic = {}
        
        for turn in find_debate(deb, 'separate', 'raw', 'turns', candidate):   
            no_of_turns+=1
            total_word_count += len(turn.split())
            for topic in ast.literal_eval(topics_df.loc[topics_df['text'] == turn, 'claim_labels'].values[0]):
                if topic in turns_per_topic:
                    turns_per_topic[topic]+=1
                else:
                    turns_per_topic[topic] = 1
                    
                if topic in words_per_topic:
                    words_per_topic[topic] += len(turn.split())
                else:
                    words_per_topic[topic]=len(turn.split())
                
                if topic in lengths_per_topic:
                    lengths_per_topic[topic].append(len(turn.split()))
                else:
                    lengths_per_topic[topic] = [len(turn.split())]
        
        # create rankings of turns per topic
        rank_turns = {}
        sorted_items = sorted(turns_per_topic.items(), key=lambda x: x[1], reverse=True)        
        rank = 1        
        for value, group in groupby(sorted_items, lambda x: x[1]):
            group_list = list(group)
            for key, val in group_list:
                rank_turns[key] = rank            
            rank += len(group_list)
        # create rankings of words per topic
        rank_words = {}
        sorted_items = sorted(words_per_topic.items(), key=lambda x: x[1], reverse=True)        
        rank = 1        
        for value, group in groupby(sorted_items, lambda x: x[1]):
            group_list = list(group)
            for key, val in group_list:
                rank_words[key] = rank            
            rank += len(group_list)
        
        
        # done with candidate, add metrics        
        for t in turns_per_topic:
            new_row = {}
            new_row['debate']=deb
            new_row['participant']=candidate
            new_row['topic']=t
            
            # calculate proportion of turns in which each topic was present
            prop_turns = turns_per_topic[t]/no_of_turns             
            new_row['prop_turns']=prop_turns
            # calculate proportion of words on topic
            prop_words = words_per_topic[t]/total_word_count
            new_row['prop_words']=prop_words
            # calculate average len of turn on topic
            avg_turn_length = np.mean(lengths_per_topic[t])
            new_row['avg_turn_length'] = avg_turn_length
            # get rank of topic by turns
            new_row['turn_rank']=rank_turns[t]
            # get rank of topic by words
            new_row['word_rank']=rank_words[t]
            
            
            topic_focus_metrics.append(new_row)

In [224]:
focus_df = pd.DataFrame(topic_focus_metrics)
focus_df

,debate,participant,topic,prop_turns,prop_words,avg_turn_length,turn_rank,word_rank
0,deb_2005_04_18,KENNEDY,2000,0.113636,0.125430,34.000000,2,4
1,deb_2005_04_18,KENNEDY,2012,0.083333,0.087801,32.454545,3,10
2,deb_2005_04_18,KENNEDY,100,0.128788,0.241515,57.764706,1,1
3,deb_2005_04_18,KENNEDY,107,0.068182,0.106493,48.111111,5,7
4,deb_2005_04_18,KENNEDY,500,0.015152,0.033448,68.000000,19,21
...,...,...,...,...,...,...,...,...
3571,deb_2024_06_26,STARMER,1803,0.020408,0.035435,231.000000,27,36
3572,deb_2024_06_26,STARMER,1910,0.061224,0.056450,122.666667,14,22
3573,deb_2024_06_26,STARMER,1920,0.020408,0.035435,231.000000,27,36
3574,deb_2024_06_26,STARMER,1806,0.020408,0.023163,151.000000,27,43
3575,deb_2024_06_26,STARMER,1306,0.020408,0.037122,242.000000,27,34

In [225]:
focus_df['word_rank'].hasnans

False

In [228]:
focus_df.to_csv('focus_df.csv')

In [227]:
titles = {
    100: "Macroeconomics",
    101: "Inflation, prices, and interest rates",
    103: "Unemployment rate",
    104: "Monetary Supply, Central Bank, and the Treasury",
    105: "National Budget, Debt, public spending",
    107: "Taxation, Tax policy, and Tax Reform",
    108: "Industrial Policy, Privatisation, Nationalisation",
    200: "Civil Rights",
    201: "Ethnic Minority and Racial Group Discrimination",
    202: "Gender and Sexual Orientation Discrimination",
    207: "Freedom of Speech & Religion",
    208: "Right to Privacy and Access to Government Information",
    230: "Immigration",
    300: "Health",
    301: "Health Care Reform",
    321: "Regulation of Drug Industry, Medical Devices, and Clinical Labs",
    325: "Health Manpower and Training",
    331: "Prevention, Communicable Diseases and Health Promotion",
    332: "Infants and Children",
    334: "Long-Term Care, Home Health, and Rehabilitation",
    344: "Drug and Alcohol or Substance Abuse Treatment",
    400: "Agriculture",
    401: "Agricultural Trade",
    406: "Animal Welfare",
    408: "Fisheries and Fishing",
    500: "Labour and Employment",
    502: "Employment Training and Workforce Development",
    503: "Employee Benefits",
    504: "Employee Relations and Labour Unions",
    505: "Fair Labour Standards",
    506: "Youth Employment and Child Labour",
    508: "Parental Leave and Child Care",
    529: "Migrant and Seasonal Workers",
    600: "Education",
    601: "Higher Education",
    602: "Elementary and Secondary Education",
    603: "Education of Underprivileged Students",
    604: "Vocational Education",
    606: "Special Education",
    700: "Environment",
    701: "Water Pollution",
    703: "Waste Disposal",
    705: "Air Pollution, Global Warming, and Noise Pollution",
    709: "Species and Forest Protection",
    800: "Energy",
    801: "Nuclear Energy and Nuclear Regulatory Issues",
    803: "Natural Gas and Oil",
    805: "Coal",
    806: "Alternative and Renewable Energy",
    807: "Energy Conservation",
    1000: "Transportation",
    1001: "Mass and Public Transportation and Safety",
    1002: "Highway (Road) Construction, Maintenance, and Safety",
    1003: "Airports, Airlines, Air Traffic Control and Safety",
    1005: "Railroad Transportation and Safety",
    1006: "Truck and Automobile Transportation and Safety",
    1200: "Law, Crime, and Family Issues",
    1202: "White Collar Crime and Organized Crime",
    1203: "Illegal Drug Production, Trafficking, and Control",
    1205: "Prison System",
    1206: "Juvenile Crime and the Juvenile Justice System",
    1207: "Child Abuse",
    1208: "Family Issues",
    1209: "Police, Fire, and Weapons Control",
    1211: "Riots and Crime Prevention",
    1300: "Social Welfare",
    1302: "Poverty and Assistance for Low-Income Families",
    1303: "Elderly Issues and Elderly Assistance Programs, State Pensions",
    1304: "Assistance to the Disabled and Handicapped",
    1305: "Social Services and Volunteer Associations",
    1400: "Planning and Housing Issues",
    1401: "Housing and Community Development",
    1406: "Low and Middle Income Housing Programs and Needs",
    1407: "Veterans Housing Assistance and Military Housing Programs",
    1409: "Housing Assistance for Homeless and Homeless Issues",
    1410: "Mortgages",
    1500: "Finance and Domestic Commerce",
    1501: "Banking System and Financial Institution Regulation",
    1521: "Small Business Issues",
    1524: "Tourism",
    1600: "Defence",
    1603: "Military Intelligence, Intelligence Services, Espionage",
    1608: "Manpower, Military Personnel and Dependents",
    1609: "Veterans Issues",
    1610: "Military Procurement and Weapons System Acquisitions and Evaluation",
    1627: "Domestic and International Terrorism",
    1800: "Foreign Trade",
    1803: "Export Promotion and Regulation, Export Credit Agencies",
    1806: "Productivity and Competitiveness of U.K. Business, U.K. Balance of Payments",
    1900: "International Affairs",
    1901: "Foreign Aid",
    1907: "China",
    1909: "Eastern Europe",
    1910: "Western Europe, Common Market Issues",
    1911: "Africa",
    1920: "Middle East",
    1926: "International Organizations other than Finance",
    1930: "North America and North Atlantic Ocean",
    2000: "Government Operations",
    2001: "Intergovernmental Relations",
    2011: "Executive-Legislative Relations and Parliamentary Operations",
    2012: "Political Parties, Campaigns, and Voter Registration",
    2032: "Prime Ministerial or Ministerial Scandals and Resignations"
}

In [1]:
def enter_title(topic):
    try:
        return titles[topic]
    except KeyError:
        print(topic)
        return None

In [232]:
focus_df['topic_title'] = focus_df['topic'].apply(enter_title)
focus_df = focus_df.dropna(subset=['topic_title'])
focus_df

1906
1212
1906
1906
2007
1601
1009
1306
203
1309
1301
203
1306
608
706
203
1306
1402
1301
1903
1906
1906
1906
1906
1906
1906
399
1309
1903
1306
1201
1306
2007
1309
106
1402
1906
1903
1906
1306

,debate,participant,topic,prop_turns,prop_words,avg_turn_length,turn_rank,word_rank,topic_title
0,deb_2005_04_18,KENNEDY,2000,0.113636,0.125430,34.000000,2,4,Government Operations
1,deb_2005_04_18,KENNEDY,2012,0.083333,0.087801,32.454545,3,10,"Political Parties, Campaigns, and Voter Regist..."
2,deb_2005_04_18,KENNEDY,100,0.128788,0.241515,57.764706,1,1,Macroeconomics
3,deb_2005_04_18,KENNEDY,107,0.068182,0.106493,48.111111,5,7,"Taxation, Tax policy, and Tax Reform"
4,deb_2005_04_18,KENNEDY,500,0.015152,0.033448,68.000000,19,21,Labour and Employment
...,...,...,...,...,...,...,...,...,...
3570,deb_2024_06_26,STARMER,1900,0.061224,0.056450,122.666667,14,22,International Affairs
3571,deb_2024_06_26,STARMER,1803,0.020408,0.035435,231.000000,27,36,"Export Promotion and Regulation, Export Credit..."
3572,deb_2024_06_26,STARMER,1910,0.061224,0.056450,122.666667,14,22,"Western Europe, Common Market Issues"
3573,deb_2024_06_26,STARMER,1920,0.020408,0.035435,231.000000,27,36,Middle East
3574,deb_2024_06_26,STARMER,1806,0.020408,0.023163,151.000000,27,43,Productivity and Competitiveness of U.K. Busin...

In [233]:
focus_df.to_csv('focus_df.csv')

In [ ]:
# can create graphs demonstrating level of focus and comparing between candidates

In [ ]:
deb_options

In [8]:
df = pd.read_csv('focus_df.csv',index_col=0)
df

,debate,participant,topic,prop_turns,prop_words,avg_turn_length,turn_rank,word_rank,topic_title
0,deb_2005_04_18,KENNEDY,2000,0.113636,0.125430,34.000000,2,4,Government Operations
1,deb_2005_04_18,KENNEDY,2012,0.083333,0.087801,32.454545,3,10,"Political Parties, Campaigns, and Voter Regist..."
2,deb_2005_04_18,KENNEDY,100,0.128788,0.241515,57.764706,1,1,Macroeconomics
3,deb_2005_04_18,KENNEDY,107,0.068182,0.106493,48.111111,5,7,"Taxation, Tax policy, and Tax Reform"
4,deb_2005_04_18,KENNEDY,500,0.015152,0.033448,68.000000,19,21,Labour and Employment
...,...,...,...,...,...,...,...,...,...
3570,deb_2024_06_26,STARMER,1900,0.061224,0.056450,122.666667,14,22,International Affairs
3571,deb_2024_06_26,STARMER,1803,0.020408,0.035435,231.000000,27,36,"Export Promotion and Regulation, Export Credit..."
3572,deb_2024_06_26,STARMER,1910,0.061224,0.056450,122.666667,14,22,"Western Europe, Common Market Issues"
3573,deb_2024_06_26,STARMER,1920,0.020408,0.035435,231.000000,27,36,Middle East
3574,deb_2024_06_26,STARMER,1806,0.020408,0.023163,151.000000,27,43,Productivity and Competitiveness of U.K. Busin...

In [6]:
import seaborn as sns
import matplotlib.pyplot as plt